import { useEffect, useMemo, useRef, useState } from 'react'
import { Eye, EyeOff, Lock, LockOpen } from 'lucide-react'
import './openworld-builder.css'

// Openworld Builder — an art-generation authoring tool: every real Kingdom/
// realm component (buildings, zones, hotspots, portals, harvest nodes,
// stations, districts, lanes) on a Google-Maps-style zoom/pan canvas, with
// real draw tools (marker/zone/boundary/sprite/measure), a type-aware
// Inspector that captures what a PIXEL AGENT needs to generate each asset,
// an editable Prompt Starter brief, and an export that bundles the map
// snapshot + full prompt into one self-contained HTML file.
//
// Populated from openworld-manifest.json — generated by
// apps/lashira/web/scripts/gen-map-inventory.mjs from the REAL game source
// (farm-map.js, world-map-registry.js, realms/*.js), copied into this app's
// public/farm-art/ alongside the map PNGs. Re-run `npm run map:sync` in
// apps/lashira/web after touching any map/realm coordinates, then reload.
//
// See docs/lashirabloom/Openworld Bloom Concept/
// HANDOFF-openworld-builder-v2-pixel-inspector.md for the full spec this
// implements.

const TP = 22 // px per tile at zoom 1 (the GAME renders at 48px/tile)

// ---------------- pixel-agent asset model ----------------
type AnimType = 'none' | 'idle-loop' | 'state-toggle' | 'walk' | 'one-shot'
type GenType = 'map-object' | 'character' | 'tileset' | 'none'
type ViewType = 'low top-down' | 'high top-down' | 'side'
type AssetSpec = {
  gen: GenType
  dirs: 1 | 4 | 8
  view: ViewType
  anim: AnimType
  loop?: string
  states?: string[]
  actions?: string[]
  prompt?: string
  status: 'has-art' | 'needs-art' | 'placeholder'
}
type Annot = { name?: string; desc?: string; intent?: string }

type Obj = Annot & {
  id: string; kind: string; x: number; y: number; w?: number; h?: number; hitR?: number
  icon?: string; color?: string; note?: string; subtype?: string
  asset?: AssetSpec
}
type Zone = Annot & {
  id: string; x: number; y: number; w: number; h: number; c: string; l: string
  role?: 'label' | 'terrain' | 'trigger'
  asset?: AssetSpec
}
type BoundaryRegion = Annot & { id: string; tiles: string[]; mode: 'block' | 'clear' }
type MapData = {
  id: string; name: string; sub: string; swatch: string; image: string
  W: number; H: number
  zones: Zone[]
  objects: Obj[]
  scene: string
}

const MAP_META: Record<string, { name: string; sub: string; swatch: string }> = {
  kingdom: { name: 'Kingdom', sub: 'hub · launcher', swatch: '#7c6cff' },
  lashira_keep: { name: 'Lashira Keep', sub: 'city · stronghold', swatch: '#7c6cff' },
  bloomwall_pass: { name: 'Bloomwall Pass', sub: 'defense · adventure', swatch: '#2ca64e' },
  hearthrush_kitchen: { name: 'Hearthrush Kitchen', sub: 'cooking · service', swatch: '#f6a42c' },
  fountain_festival: { name: 'Fountain Festival', sub: 'puzzle · events', swatch: '#e53770' },
  emberring_arena: { name: 'Emberring Arena', sub: 'social competition', swatch: '#da2a31' },
}
const MAP_ORDER = ['kingdom', 'lashira_keep', 'bloomwall_pass', 'hearthrush_kitchen', 'fountain_festival', 'emberring_arena']
const MAP_ICON: Record<string, string> = {
  kingdom: '👑', lashira_keep: '🏰', bloomwall_pass: '🛡', hearthrush_kitchen: '🍽', fountain_festival: '✨', emberring_arena: '⚔',
}
const PORTAL_ICON: Record<string, string> = {
  lashira_keep: '🏰', bloomwall_pass: '🛡', hearthrush_kitchen: '🍽', fountain_festival: '✨', emberring_arena: '⚔',
}
const KIND_LABEL: Record<string, string> = {
  portal: 'Portal', building: 'Building', shop: 'Shop', sell: 'Market', dungeon: 'Dungeon', dock: 'Dock',
  pvprank: 'PvP Board', castle: 'Castle', ore: 'Ore node', tree: 'Tree node', placement: 'Prop', station: 'Station',
  district: 'District', core: 'Objective', spawn: 'Spawn', npc: 'NPC', sprite: 'Sprite', zone: 'Zone', boundary: 'Boundary',
}
const ZONE_COLORS = ['#7a5a34', '#5fa06a', '#6b6f86', '#4f8f86', '#3f6fa8', '#8a7038', '#9a8f6a', '#8a5a8f']

// Sprite catalog — picking a type auto-sets its default animation (§5 of the
// handoff). Operator can still clear/override it in the Inspector.
const SPRITE_CATALOG: { id: string; icon: string; label: string; anim: AnimType; loop?: string }[] = [
  { id: 'tree', icon: '🌳', label: 'Tree', anim: 'idle-loop', loop: 'sway' },
  { id: 'bush', icon: '🌿', label: 'Bush', anim: 'none' },
  { id: 'flowerbed', icon: '🌸', label: 'Flower bed', anim: 'none' },
  { id: 'lamp', icon: '💡', label: 'Lamp post', anim: 'idle-loop', loop: 'flicker' },
  { id: 'lantern', icon: '🏮', label: 'Lantern', anim: 'idle-loop', loop: 'flicker' },
  { id: 'bench', icon: '🪑', label: 'Bench', anim: 'none' },
  { id: 'rock', icon: '🪨', label: 'Rock', anim: 'none' },
  { id: 'fence', icon: '🚧', label: 'Fence', anim: 'none' },
  { id: 'crate', icon: '📦', label: 'Crate', anim: 'none' },
  { id: 'barrel', icon: '🛢', label: 'Barrel', anim: 'none' },
  { id: 'signpost', icon: '🪧', label: 'Signpost', anim: 'none' },
  { id: 'banner', icon: '🚩', label: 'Banner', anim: 'idle-loop', loop: 'wave' },
  { id: 'fountain', icon: '⛲', label: 'Fountain', anim: 'idle-loop', loop: 'flow' },
  { id: 'well', icon: '🪣', label: 'Well', anim: 'none' },
  { id: 'stall', icon: '🛒', label: 'Cart / Stall', anim: 'none' },
  { id: 'statue', icon: '🗿', label: 'Statue', anim: 'none' },
  { id: 'needsart', icon: '❓', label: 'Custom…', anim: 'none' },
]

// Marker types placeable with the Marker tool.
const MARKER_KINDS: { id: string; label: string; icon: string }[] = [
  { id: 'station', label: 'Station', icon: '🧺' }, { id: 'pad', label: 'Pad', icon: '＋' },
  { id: 'spawn', label: 'Spawn', icon: '◎' }, { id: 'district', label: 'District', icon: '🏘' },
  { id: 'core', label: 'Objective', icon: '💎' }, { id: 'npc', label: 'NPC', icon: '🧑' },
]
const STATION_SUBTYPES: Record<string, string[]> = {
  pantry: ['stocked', 'empty'], stove: ['off', 'cooking'], serve: ['empty', 'plated'],
  prep: ['clean', 'dirty'], sink: ['clean', 'dirty'], oven: ['off', 'baking'],
}

// Default AssetSpec per kind (§4 of the handoff) — the operator overrides
// from here, never starts from a blank sheet.
const ASSET_DEFAULTS: Record<string, Partial<AssetSpec>> = {
  portal: { gen: 'map-object', dirs: 1, view: 'high top-down', anim: 'idle-loop', loop: 'pulse' },
  station: { gen: 'map-object', dirs: 1, view: 'high top-down', anim: 'state-toggle', states: ['idle', 'active'] },
  pad: { gen: 'map-object', dirs: 1, view: 'high top-down', anim: 'none' },
  district: { gen: 'map-object', dirs: 1, view: 'high top-down', anim: 'none' },
  core: { gen: 'map-object', dirs: 1, view: 'high top-down', anim: 'idle-loop', loop: 'pulse' },
  spawn: { gen: 'none', dirs: 1, view: 'high top-down', anim: 'none' },
  npc: { gen: 'character', dirs: 8, view: 'low top-down', anim: 'walk', actions: ['idle', 'walk'] },
  ore: { gen: 'map-object', dirs: 1, view: 'high top-down', anim: 'state-toggle', states: ['ready', 'depleted'] },
  tree: { gen: 'map-object', dirs: 1, view: 'high top-down', anim: 'state-toggle', states: ['ready', 'stump'] },
  building: { gen: 'map-object', dirs: 1, view: 'high top-down', anim: 'none' },
  placement: { gen: 'map-object', dirs: 1, view: 'high top-down', anim: 'none' },
  sprite: { gen: 'map-object', dirs: 1, view: 'high top-down', anim: 'none' },
}
function defaultAsset(kind: string, status: AssetSpec['status'] = 'needs-art'): AssetSpec {
  const d = ASSET_DEFAULTS[kind] || { gen: 'map-object', dirs: 1, view: 'high top-down', anim: 'none' }
  return {
    gen: d.gen || 'map-object', dirs: d.dirs || 1, view: d.view || 'high top-down', anim: d.anim || 'none',
    loop: d.loop, states: d.states ? [...d.states] : undefined, actions: d.actions ? [...d.actions] : undefined, status,
  }
}
function animOptionsFor(kind: string): AnimType[] {
  if (kind === 'npc') return ['none', 'walk']
  if (kind === 'spawn') return ['none']
  return ['none', 'idle-loop', 'state-toggle', 'one-shot']
}
function ensureAsset(o: Obj | Zone, kind: string) { if (!o.asset) o.asset = defaultAsset(kind, 'needs-art') }

// ---------------- Prompt Starter defaults (§7) — reused verbatim from
// roadmap-and-build-plan.md's style anchor + per-realm Scene text, and the
// Kingdom description from MAP-full-element-inventory.md's visual read. ----
const PROJECT_LINE = 'LashiraBloom — cozy Stardew-inspired top-down farming RPG, kid-safe.'
const STYLE_ANCHOR = 'Cozy-cute fantasy pixel art, same style as the LashiraBloom kingdom hub, bright saturated but soft palette, top-down 3/4 RPG perspective, painterly pixel detail, lush nature borders, warm paths, clean navigable spaces, kid-safe, no UI baked into art.'
const GRID_NOTE = '60×48 tiles. [0,0]=top-left. x→right, y→down. Coordinates are TILE units; game renders 48px/tile.'
const READ_NOTE = 'Each row below is one authored element. intent= is the instruction; the rest is positional/visual data.'
const MAP_SCENE: Record<string, string> = {
  kingdom: 'The Kingdom hub: a farm plot (NW) with tilled soil, a garden + greenhouse (W) with cherry blossoms, a central plaza with a fountain and radiating stone roads to the castle, a mine with blue/purple crystals (E), fenced animal pens for cow/sheep/chicken (NE), a lily-pad pond with a wooden bridge (SW), a lumber grove with stumps and log piles (S-center), and a circular stone mandala arena (SE).',
  lashira_keep: 'The castle at the center with empty district plots around it, connected by soft stone roads: farm, market, kitchen, academy, defense, workshop, housing, and garden districts, each with a foundation pad, corner watchtowers and a south gate.',
  bloomwall_pass: 'A fortified south gate outside the kingdom wall: one winding dirt road from the upper-left forest entrance to a glowing Bloom Core near the lower-right gate, stone tower pads beside the path, small stone walls, banners, flowers, lamp posts, and a side cave/ruin entrance for boss encounters.',
  hearthrush_kitchen: 'A warm tavern-market kitchen connected to a small serving hall: ingredient pantry on the left, prep counters, cooking stoves, a plating counter, a serving window, customer tables on the right, and clear walking lanes between stations.',
  fountain_festival: 'A central fountain plaza with a glowing portal ring, cozy garden paths, flower beds, festival stalls and event booths, a rectangular puzzle-board plaza, a trellis arch, seed crates and flower carts, banners and lanterns.',
  emberring_arena: 'A safe circular training arena with symmetrical cover blocks, bushes, low walls, two entrance lanes, spawn corners, a central glowing objective circle, spectator banners, and torchlight around the rim.',
}

function iconForPlacement(key: string): string {
  const k = key.toLowerCase()
  if (k.includes('tree')) return '🌲'
  if (k.includes('flower')) return '🌸'
  if (k.includes('shop')) return '🏪'
  if (k.includes('ore') || k.includes('boulder')) return '⛏'
  if (k.includes('fountain')) return '⛲'
  if (k.includes('fish')) return '🎣'
  if (k.includes('trough')) return '🥣'
  if (k.includes('mushroom')) return '🍄'
  if (k.includes('bush')) return '🌿'
  if (k.includes('greenhouse')) return '🏡'
  if (k.includes('windmill')) return '🌬'
  if (k.includes('scarecrow')) return '🧑‍🌾'
  if (k.includes('wall') || k.includes('scoreboard') || k.includes('signpost')) return '🚩'
  return '📦'
}
function iconForHotspotKind(kind: string): string {
  return { shop: '🏪', sell: '💰', dungeon: '⚔', dock: '🎣', pvprank: '🏆', castle: '🏰' }[kind] || '📍'
}

// ---------- manifest -> per-map normalized MapData ----------
// Manifest-origin elements (real, already-shipped art) default asset.status
// to 'has-art' — they're excluded from the PIXEL ASSETS export automatically.
// Anything the operator places NEW (marker/zone/sprite/boundary) defaults to
// 'needs-art' via defaultAsset()'s own default.
function normalize(manifest: any): Record<string, MapData> {
  const out: Record<string, MapData> = {}
  for (const id of MAP_ORDER) {
    const m = manifest?.maps?.[id]
    const meta = MAP_META[id]
    if (!m) { out[id] = { id, name: meta.name, sub: meta.sub, swatch: meta.swatch, image: '', W: 60, H: 48, zones: [], objects: [], scene: MAP_SCENE[id] || '' }; continue }
    const zones: Zone[] = []
    const objects: Obj[] = []

    if (id === 'kingdom') {
      let zi = 0
      for (const [key, r] of Object.entries<any>(m.zones || {})) {
        zones.push({ id: key, x: r.x0, y: r.y0, w: r.x1 - r.x0 + 1, h: r.y1 - r.y0 + 1, c: ZONE_COLORS[zi++ % ZONE_COLORS.length], l: key, role: 'label' })
      }
      for (const b of m.buildings || []) objects.push({ id: b.key, kind: 'building', x: b.tx, y: b.ty, w: b.w, h: b.h, icon: '🏠', color: '#8b7dff', asset: defaultAsset('building', 'has-art') })
      for (const p of m.placements || []) objects.push({ id: p.key + '@' + p.tx + ',' + p.ty, kind: 'placement', x: p.tx, y: p.ty, w: p.w, h: p.h, icon: iconForPlacement(p.key), color: '#8fae7a', asset: defaultAsset('placement', 'has-art') })
      for (const h of m.hotspots || []) {
        if (h.kind === 'realm') continue
        const cx = Math.round((h.rect.x0 + h.rect.x1) / 2), cy = Math.round((h.rect.y0 + h.rect.y1) / 2)
        objects.push({ id: h.id, kind: h.kind, x: cx, y: cy, hitR: Math.max(1, (h.rect.x1 - h.rect.x0 + 1) / 2), icon: iconForHotspotKind(h.kind), color: h.ported === false ? '#e5533d' : '#3fd07a', note: h.ported === false ? 'not wired yet' : undefined, asset: defaultAsset(h.kind, 'has-art') })
      }
      for (const p of m.portals || []) {
        const r = p.hqHotspot
        const cx = Math.round((r.x0 + r.x1) / 2), cy = Math.round((r.y0 + r.y1) / 2)
        objects.push({ id: p.id, kind: 'portal', x: cx, y: cy, hitR: 1.6, icon: PORTAL_ICON[p.id] || '📍', color: p.color, asset: defaultAsset('portal', 'has-art') })
      }
      for (const o of m.harvestNodes?.ore || []) objects.push({ id: `ore@${o.x},${o.y}`, kind: 'ore', x: o.x, y: o.y, icon: '⛏', color: '#c9a24a', asset: defaultAsset('ore', 'has-art') })
      for (const t of m.harvestNodes?.trees || []) objects.push({ id: `tree@${t.x},${t.y}`, kind: 'tree', x: t.x, y: t.y, icon: t.hard ? '🌳' : '🌲', color: '#4a8f4f', asset: defaultAsset('tree', 'has-art') })
    } else {
      for (const o of m.objects || []) {
        objects.push({ id: o.id, kind: o.kind, x: o.tile[0], y: o.tile[1], w: o.size?.[0], h: o.size?.[1], icon: o.icon || KIND_LABEL[o.kind]?.[0] || '◆', color: '#8b7dff', asset: defaultAsset(o.kind, 'has-art') })
      }
      if (id === 'bloomwall_pass' && Array.isArray(m.lane)) {
        m.lane.forEach(([x, y]: [number, number], i: number) => {
          objects.push({ id: `lane_${i}`, kind: 'sprite', x, y, icon: '·', color: '#cdb384', note: i === 0 ? 'lane start' : undefined, asset: defaultAsset('sprite', 'has-art') })
        })
      }
    }
    // m.image is already fully relative to public/farm-art/ — 'basemap.png'
    // for Kingdom, 'Worldmap/lashira-keep.png' etc. for realms.
    out[id] = { id, name: meta.name, sub: meta.sub, swatch: meta.swatch, image: m.image ? `/farm-art/${m.image}` : '', W: (m.grid?.[0]) || 60, H: (m.grid?.[1]) || 48, zones, objects, scene: MAP_SCENE[id] || '' }
  }
  return out
}

type Tool = 'select' | 'marker' | 'zone' | 'collision' | 'sprite' | 'measure'
const TOOLS: { id: Tool; icon: string; label: string }[] = [
  { id: 'select', icon: '↖', label: 'Select' }, { id: 'marker', icon: '📍', label: 'Marker' },
  { id: 'zone', icon: '▭', label: 'Zone' }, { id: 'collision', icon: '🧱', label: 'Boundary' },
  { id: 'sprite', icon: '🌳', label: 'Sprite' }, { id: 'measure', icon: '📏', label: 'Measure' },
]
const HINTS: Record<Tool, string> = {
  select: 'Select / Pan — drag empty space to pan, drag a marker to move it',
  marker: 'Marker — pick a type below, then click the map to drop it',
  zone: 'Zone / Label — drag a rectangle to draw a named region',
  collision: 'Boundary — drag to paint a named blocked region; brush + mode in the Inspector',
  sprite: 'Sprite — pick a sprite type in the Inspector, then click to stamp it',
  measure: 'Measure — click two points to read the tile distance (not exported)',
}
const LAYER_DEFS: { id: 'base' | 'grid' | 'zones' | 'collision' | 'objects' | 'sprites'; label: string; color: string }[] = [
  { id: 'base', label: 'Base', color: '#64748b' },
  { id: 'grid', label: 'Grid', color: '#94a3b8' },
  { id: 'zones', label: 'Zones', color: '#16a34a' },
  { id: 'collision', label: 'Boundary', color: '#dc2626' },
  { id: 'objects', label: 'Objects', color: '#6366f1' },
  { id: 'sprites', label: 'Sprites', color: '#0d9488' },
]

// Small reusable chip-list editor (States / Actions) — a top-level component
// so its own useState survives parent re-renders.
function ChipEditor({ label, items, onChange }: { label: string; items: string[]; onChange: (v: string[]) => void }) {
  const [draft, setDraft] = useState('')
  return (
    <div className="owb-chipeditor">
      <label className="fl">{label}</label>
      <div className="chiprow">
        {items.map((it, i) => (
          <span key={it + i} className="chip removable" onClick={() => onChange(items.filter((_, j) => j !== i))}>{it} ✕</span>
        ))}
        {!items.length && <span className="chip-empty">none yet</span>}
      </div>
      <input
        className="owb-input sm" placeholder={`add ${label.toLowerCase()}, Enter`} value={draft}
        onChange={(e) => setDraft(e.target.value)}
        onKeyDown={(e) => { if (e.key === 'Enter' && draft.trim()) { onChange([...items, draft.trim()]); setDraft('') } }}
      />
    </div>
  )
}

export function OpenworldBuilder() {
  const [maps, setMaps] = useState<Record<string, MapData> | null>(null)
  const [activeId, setActiveId] = useState('kingdom')
  const [tool, setTool] = useState<Tool>('select')
  const [rev, setRev] = useState<Record<string, number>>({})
  const [, bump] = useState(0)
  const forceRender = () => bump((n) => (n + 1) & 0xffff)
  const [briefOpen, setBriefOpen] = useState(false)

  const layerVis = useRef<Record<string, boolean>>({ base: true, grid: true, zones: true, collision: true, objects: true, sprites: true })
  const layerLock = useRef<Record<string, boolean>>({ base: false, grid: false, zones: false, collision: false, objects: false, sprites: false })
  const collision = useRef<Record<string, BoundaryRegion[]>>({})
  const paintingRegionRef = useRef<BoundaryRegion | null>(null)
  const camRef = useRef({ x: 0, y: 0, zoom: 1 })
  const selRef = useRef<{ kind: 'object'; obj: Obj } | { kind: 'zone'; zone: Zone } | { kind: 'boundary'; region: BoundaryRegion } | null>(null)
  const hoverRef = useRef<{ tx: number; ty: number } | null>(null)
  const brushRef = useRef({ size: 1 as 1 | 3 | 5, mode: 'block' as 'block' | 'clear' })
  const activeSpriteRef = useRef('tree')
  const markerKindRef = useRef('station')
  const zoneDraftRef = useRef<{ x0: number; y0: number; x1: number; y1: number } | null>(null)
  const measureRef = useRef<{ a: { tx: number; ty: number } | null; b: { tx: number; ty: number } | null }>({ a: null, b: null })

  const canvasRef = useRef<HTMLCanvasElement>(null)
  const stageRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    fetch('/farm-art/openworld-manifest.json').then((r) => r.json()).then((m) => {
      setMaps(normalize(m))
      setRev(Object.fromEntries(MAP_ORDER.map((id) => [id, 1])))
    }).catch(() => { setMaps(normalize(null)) })
  }, [])

  const map = maps?.[activeId]
  const [, setTick] = useState(0) // cheap re-render trigger for inspector/layers/objlist after ref mutations

  function markDirty() { setRev((r) => ({ ...r, [activeId]: (r[activeId] || 1) + 1 })); setTick((t) => (t + 1) & 0xffff) }

  // ---------- canvas geometry ----------
  function w2s(wx: number, wy: number) { const c = camRef.current; return { x: wx * c.zoom - c.x, y: wy * c.zoom - c.y } }
  function s2w(sx: number, sy: number) { const c = camRef.current; return { x: (sx + c.x) / c.zoom, y: (sy + c.y) / c.zoom } }
  function s2tile(sx: number, sy: number) { const w = s2w(sx, sy); return { tx: Math.floor(w.x / TP), ty: Math.floor(w.y / TP) } }
  function fit() {
    if (!map || !stageRef.current) return
    const r = stageRef.current.getBoundingClientRect()
    const mw = map.W * TP, mh = map.H * TP
    const z = Math.min(r.width / mw, r.height / mh) * 0.92
    camRef.current = { zoom: z, x: (mw * z - r.width) / 2, y: (mh * z - r.height) / 2 }
  }
  function resizeCanvas() {
    const canvas = canvasRef.current, wrap = stageRef.current
    if (!canvas || !wrap) return
    const dpr = Math.min(2, window.devicePixelRatio || 1)
    const r = wrap.getBoundingClientRect()
    canvas.width = Math.max(1, Math.floor(r.width * dpr)); canvas.height = Math.max(1, Math.floor(r.height * dpr))
    canvas.style.width = r.width + 'px'; canvas.style.height = r.height + 'px'
    draw()
  }

  const imgCacheRef = useRef<Record<string, HTMLImageElement>>({})
  function getImg(src: string): HTMLImageElement | null {
    if (!src) return null
    let img = imgCacheRef.current[src]
    if (!img) { img = new Image(); img.src = src; imgCacheRef.current[src] = img }
    return img.complete && img.naturalWidth ? img : null
  }

  function objColor(o: Obj) { return o.color || '#8b7dff' }
  function shade(hex: string, p: number) {
    const n = parseInt(hex.slice(1), 16); let r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255
    r = Math.round(r + (p < 0 ? r * p : (255 - r) * p)); g = Math.round(g + (p < 0 ? g * p : (255 - g) * p)); b = Math.round(b + (p < 0 ? b * p : (255 - b) * p))
    return `rgb(${r},${g},${b})`
  }
  function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
    ctx.beginPath(); ctx.moveTo(x + r, y); ctx.arcTo(x + w, y, x + w, y + h, r); ctx.arcTo(x + w, y + h, x, y + h, r)
    ctx.arcTo(x, y + h, x, y, r); ctx.arcTo(x, y, x + w, y, r); ctx.closePath()
  }

  // draw() is parametrized so it can also render into an offscreen canvas at
  // scale=1 for the HTML export snapshot (§ export). With no `target`, it
  // draws the live viewport exactly as before.
  function draw(target?: { ctx: CanvasRenderingContext2D; vw: number; vh: number; clean?: boolean }) {
    const canvas = canvasRef.current, m = map
    if ((!canvas && !target) || !m) return
    const ctx = target?.ctx ?? canvas!.getContext('2d')!
    const dpr = target ? 1 : Math.min(2, window.devicePixelRatio || 1)
    if (!target) ctx.setTransform(dpr, 0, 0, dpr, 0, 0)
    const vw = target?.vw ?? stageRef.current!.getBoundingClientRect().width
    const vh = target?.vh ?? stageRef.current!.getBoundingClientRect().height
    ctx.clearRect(0, 0, vw, vh)
    const cam = camRef.current
    const mw = m.W * TP, mh = m.H * TP
    const tl = w2s(0, 0), br = w2s(mw, mh)

    if (layerVis.current.base || target?.clean) {
      const img = getImg(m.image)
      if (img) ctx.drawImage(img, tl.x, tl.y, br.x - tl.x, br.y - tl.y)
      else { ctx.fillStyle = '#6fae5a'; ctx.fillRect(tl.x, tl.y, br.x - tl.x, br.y - tl.y) }
      ctx.strokeStyle = '#3d6b34'; ctx.lineWidth = 2; ctx.strokeRect(tl.x, tl.y, br.x - tl.x, br.y - tl.y)
    }
    if (layerVis.current.zones || target?.clean) for (const z of m.zones) {
      const a = w2s(z.x * TP, z.y * TP)
      ctx.fillStyle = z.c + 'b3'; roundRect(ctx, a.x, a.y, z.w * TP * cam.zoom, z.h * TP * cam.zoom, 8 * cam.zoom); ctx.fill()
      const isSel = selRef.current?.kind === 'zone' && selRef.current.zone === z
      ctx.strokeStyle = isSel ? '#fff' : '#0004'; ctx.lineWidth = isSel ? 3 : 1; ctx.stroke()
      if (cam.zoom > 0.5 || target?.clean) { ctx.fillStyle = '#fff'; ctx.font = `700 ${Math.min(14, 10 * cam.zoom)}px system-ui,sans-serif`; ctx.textAlign = 'left'; ctx.textBaseline = 'top'; ctx.fillText(z.l, a.x + 6, a.y + 5) }
    }
    if (!target?.clean) {
      const zd = zoneDraftRef.current
      if (zd) {
        const x0 = Math.min(zd.x0, zd.x1), y0 = Math.min(zd.y0, zd.y1), x1 = Math.max(zd.x0, zd.x1), y1 = Math.max(zd.y0, zd.y1)
        const a = w2s(x0 * TP, y0 * TP)
        ctx.fillStyle = '#ffffff33'; ctx.fillRect(a.x, a.y, (x1 - x0 + 1) * TP * cam.zoom, (y1 - y0 + 1) * TP * cam.zoom)
        ctx.strokeStyle = '#fff'; ctx.setLineDash([5, 4]); ctx.lineWidth = 2; ctx.strokeRect(a.x, a.y, (x1 - x0 + 1) * TP * cam.zoom, (y1 - y0 + 1) * TP * cam.zoom); ctx.setLineDash([])
      }
    }
    if (layerVis.current.collision || target?.clean) {
      const regions = collision.current[activeId] || []
      for (const region of regions) {
        const isSel = selRef.current?.kind === 'boundary' && selRef.current.region === region
        for (const k of region.tiles) {
          const [x, y] = k.split(',').map(Number); const a = w2s(x * TP, y * TP)
          ctx.fillStyle = '#e5533d55'; ctx.fillRect(a.x, a.y, TP * cam.zoom, TP * cam.zoom)
          ctx.strokeStyle = isSel ? '#fff' : '#e5533d'; ctx.lineWidth = isSel ? 2 : 1; ctx.strokeRect(a.x, a.y, TP * cam.zoom, TP * cam.zoom)
        }
      }
    }
    if ((layerVis.current.grid && !target?.clean) && cam.zoom > 0.28) {
      ctx.lineWidth = 1
      for (let x = 0; x <= m.W; x++) { const s = w2s(x * TP, 0), e = w2s(x * TP, mh); ctx.strokeStyle = x % 5 === 0 ? '#ffffff40' : '#ffffff18'; ctx.beginPath(); ctx.moveTo(s.x, s.y); ctx.lineTo(e.x, e.y); ctx.stroke() }
      for (let y = 0; y <= m.H; y++) { const s = w2s(0, y * TP), e = w2s(mw, y * TP); ctx.strokeStyle = y % 5 === 0 ? '#ffffff40' : '#ffffff18'; ctx.beginPath(); ctx.moveTo(s.x, s.y); ctx.lineTo(e.x, e.y); ctx.stroke() }
    }
    if (!target?.clean && hoverRef.current && cam.zoom > 0.28) {
      const hv = hoverRef.current
      const rad = tool === 'collision' ? brushRef.current.size : 1
      const off = Math.floor(rad / 2)
      const hOff = w2s((hv.tx - off) * TP, (hv.ty - off) * TP)
      ctx.fillStyle = '#fff2'; ctx.fillRect(hOff.x, hOff.y, rad * TP * cam.zoom, rad * TP * cam.zoom)
      const hA = w2s(hv.tx * TP, hv.ty * TP)
      ctx.strokeStyle = '#fff'; ctx.lineWidth = 1.5; ctx.strokeRect(hA.x, hA.y, TP * cam.zoom, TP * cam.zoom)
    }
    if (layerVis.current.sprites || target?.clean) for (const o of m.objects.filter((o) => o.kind === 'sprite')) drawMarker(ctx, o, true, cam)
    if (layerVis.current.objects || target?.clean) for (const o of m.objects.filter((o) => o.kind !== 'sprite')) drawMarker(ctx, o, false, cam)

    if (!target?.clean) {
      const mr = measureRef.current
      if (mr.a) {
        const a = w2s((mr.a.tx + 0.5) * TP, (mr.a.ty + 0.5) * TP)
        ctx.beginPath(); ctx.arc(a.x, a.y, 5, 0, 7); ctx.fillStyle = '#fff'; ctx.fill(); ctx.strokeStyle = '#000a'; ctx.stroke()
        const b2 = mr.b || hoverRef.current
        if (b2) {
          const b = w2s((b2.tx + 0.5) * TP, (b2.ty + 0.5) * TP)
          ctx.setLineDash([6, 4]); ctx.strokeStyle = '#fff'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke(); ctx.setLineDash([])
          const dist = Math.hypot(mr.a.tx - b2.tx, mr.a.ty - b2.ty).toFixed(1)
          const mx = (a.x + b.x) / 2, my = (a.y + b.y) / 2
          ctx.font = '700 11px system-ui,sans-serif'; const tw = ctx.measureText(dist + ' tiles').width
          ctx.fillStyle = '#0b0d1cd0'; roundRect(ctx, mx - tw / 2 - 6, my - 18, tw + 12, 17, 8); ctx.fill()
          ctx.fillStyle = '#fff'; ctx.textAlign = 'center'; ctx.fillText(dist + ' tiles', mx, my - 6); ctx.textAlign = 'start'
        }
      }
    }
  }

  function drawMarker(ctx: CanvasRenderingContext2D, o: Obj, isSprite: boolean, cam: { zoom: number }) {
    const c = w2s((o.x + (o.w ? o.w / 2 : 0.5)) * TP, (o.y + (o.h ? o.h / 2 : 0.5)) * TP)
    const R = isSprite ? Math.max(9, TP * cam.zoom * 0.38) : Math.max(11, (o.hitR || 1) * TP * cam.zoom * 0.55)
    const col = objColor(o), isSel = selRef.current?.kind === 'object' && selRef.current.obj === o
    if (!isSprite) { ctx.beginPath(); ctx.arc(c.x, c.y, (o.hitR || 1) * TP * cam.zoom, 0, 7); ctx.fillStyle = col + '1e'; ctx.fill() }
    ctx.beginPath(); ctx.ellipse(c.x, c.y + R * 0.8, R * 0.7, R * 0.28, 0, 0, 7); ctx.fillStyle = '#0004'; ctx.fill()
    const grad = ctx.createRadialGradient(c.x - R * 0.35, c.y - R * 0.4, R * 0.2, c.x, c.y, R)
    grad.addColorStop(0, '#ffffffcc'); grad.addColorStop(0.32, col); grad.addColorStop(1, shade(col, -0.4))
    ctx.beginPath(); ctx.arc(c.x, c.y, R, 0, 7); ctx.fillStyle = grad; ctx.fill()
    ctx.lineWidth = isSel ? 3 : 1.4; ctx.strokeStyle = isSel ? '#fff' : shade(col, -0.25); ctx.stroke()
    if (isSel) { ctx.beginPath(); ctx.arc(c.x, c.y, R + 4, 0, 7); ctx.strokeStyle = '#6366f1'; ctx.lineWidth = 2; ctx.stroke() }
    ctx.font = `${R}px system-ui,sans-serif`; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText(o.icon || '◆', c.x, c.y + R * 0.05)
    if (!isSprite && cam.zoom > 0.55) {
      const label = o.name || o.id
      ctx.font = '700 10px system-ui,sans-serif'; const tw = ctx.measureText(label).width
      ctx.fillStyle = '#0b0d1cd0'; roundRect(ctx, c.x - tw / 2 - 5, c.y + R + 3, tw + 10, 15, 7); ctx.fill()
      ctx.fillStyle = '#fff'; ctx.fillText(label, c.x, c.y + R + 10)
    }
    if (o.note) { ctx.beginPath(); ctx.arc(c.x + R * 0.7, c.y - R * 0.7, 5, 0, 7); ctx.fillStyle = '#d97706'; ctx.fill() }
    if (o.asset?.status === 'needs-art') {
      ctx.beginPath(); ctx.arc(c.x - R * 0.7, c.y - R * 0.7, 5, 0, 7); ctx.fillStyle = '#8b5cf6'; ctx.fill()
      ctx.fillStyle = '#fff'; ctx.font = '900 8px system-ui'; ctx.fillText('?', c.x - R * 0.7, c.y - R * 0.68)
    }
  }

  function pick(sx: number, sy: number): { kind: 'object'; obj: Obj } | { kind: 'zone'; zone: Zone } | null {
    if (!map) return null
    const cam = camRef.current
    for (let i = map.objects.length - 1; i >= 0; i--) {
      const o = map.objects[i]; const c = w2s((o.x + (o.w ? o.w / 2 : 0.5)) * TP, (o.y + (o.h ? o.h / 2 : 0.5)) * TP)
      const R = Math.max(11, (o.hitR || 1) * TP * cam.zoom * 0.55)
      if (Math.hypot(sx - c.x, sy - c.y) <= R + 4) return { kind: 'object', obj: o }
    }
    for (const z of map.zones) {
      const a = w2s(z.x * TP, z.y * TP)
      if (sx >= a.x && sx <= a.x + z.w * TP * cam.zoom && sy >= a.y && sy <= a.y + z.h * TP * cam.zoom) return { kind: 'zone', zone: z }
    }
    return null
  }

  // ---------- effects: boot, resize, raf ----------
  useEffect(() => { if (map) { fit(); resizeCanvas() } }, [activeId, maps])
  useEffect(() => {
    let raf = 0
    const loop = () => { draw(); raf = requestAnimationFrame(loop) }
    raf = requestAnimationFrame(loop)
    const onResize = () => resizeCanvas()
    window.addEventListener('resize', onResize)
    return () => { cancelAnimationFrame(raf); window.removeEventListener('resize', onResize) }
  }, [maps, activeId])

  // ---------- pointer interaction ----------
  // MUST be refs, not plain `let` locals: onPointerDown sets these then calls
  // forceRender() synchronously, which re-runs this component body before the
  // browser's next pointermove fires — a plain local would be reset to null
  // right there, so panning (and object drag) would set state and then
  // immediately discard it. Refs survive the re-render.
  const panStateRef = useRef<{ sx: number; sy: number; cx: number; cy: number } | null>(null)
  const dragObjRef = useRef<Obj | null>(null)

  function onPointerDown(e: React.PointerEvent<HTMLCanvasElement>) {
    if (!map) return
    const canvas = canvasRef.current!; canvas.setPointerCapture(e.pointerId)
    const rect = canvas.getBoundingClientRect(); const sx = e.clientX - rect.left, sy = e.clientY - rect.top
    const t = s2tile(sx, sy)
    if (tool === 'select') {
      const hit = pick(sx, sy)
      if (hit) { selRef.current = hit; dragObjRef.current = hit.kind === 'object' ? hit.obj : null; forceRender() }
      else { panStateRef.current = { sx: e.clientX, sy: e.clientY, cx: camRef.current.x, cy: camRef.current.y }; selRef.current = null; forceRender() }
    } else if (tool === 'marker') { addMarker(t.tx, t.ty) }
    else if (tool === 'zone' && !layerLock.current.zones) { zoneDraftRef.current = { x0: t.tx, y0: t.ty, x1: t.tx, y1: t.ty } }
    else if (tool === 'collision' && !layerLock.current.collision) { paintCollision(t.tx, t.ty) }
    else if (tool === 'sprite' && !layerLock.current.sprites) { stampSprite(t.tx, t.ty) }
    else if (tool === 'measure') {
      const mr = measureRef.current
      if (!mr.a || mr.b) { measureRef.current = { a: t, b: null } } else { measureRef.current = { a: mr.a, b: t } }
    }
  }
  function onPointerMove(e: React.PointerEvent<HTMLCanvasElement>) {
    const canvas = canvasRef.current; if (!canvas || !map) return
    const rect = canvas.getBoundingClientRect(); const sx = e.clientX - rect.left, sy = e.clientY - rect.top
    const t = s2tile(sx, sy); hoverRef.current = t
    if (dragObjRef.current) { dragObjRef.current.x = Math.max(0, Math.min(map.W - 1, t.tx)); dragObjRef.current.y = Math.max(0, Math.min(map.H - 1, t.ty)); markDirty() }
    else if (panStateRef.current) { const ps = panStateRef.current; camRef.current = { ...camRef.current, x: ps.cx - (e.clientX - ps.sx), y: ps.cy - (e.clientY - ps.sy) } }
    else if (zoneDraftRef.current) { zoneDraftRef.current.x1 = t.tx; zoneDraftRef.current.y1 = t.ty }
    else if (paintingRegionRef.current) { paintCollision(t.tx, t.ty) }
    // Unconditional: even plain hover (no drag/pan/paint) needs a re-render so
    // the "tile [x,y]" stagebar chip (read from hoverRef in JSX) stays live.
    forceRender()
  }
  function onPointerUp() {
    dragObjRef.current = null; panStateRef.current = null
    if (zoneDraftRef.current) { commitZone(); zoneDraftRef.current = null }
    if (paintingRegionRef.current) { selRef.current = { kind: 'boundary', region: paintingRegionRef.current }; paintingRegionRef.current = null }
    forceRender(); markDirty()
  }
  function onWheel(e: React.WheelEvent<HTMLCanvasElement>) {
    e.preventDefault()
    const canvas = canvasRef.current!; const rect = canvas.getBoundingClientRect()
    const sx = e.clientX - rect.left, sy = e.clientY - rect.top
    const before = s2w(sx, sy)
    const cam = camRef.current
    const nz = Math.max(0.25, Math.min(4, cam.zoom * (e.deltaY < 0 ? 1.12 : 0.89)))
    camRef.current = { ...cam, zoom: nz }
    const after = w2s(before.x, before.y)
    camRef.current = { zoom: nz, x: cam.x + (after.x - sx), y: cam.y + (after.y - sy) }
    forceRender()
  }

  const addN = useRef(1)
  function addMarker(x: number, y: number) {
    if (!map) return
    const kind = markerKindRef.current
    const meta = MARKER_KINDS.find((k) => k.id === kind)
    map.objects.push({ id: kind + '_' + addN.current++, kind, x, y, color: '#8b7dff', icon: meta?.icon || '◆', hitR: 1.2, asset: defaultAsset(kind) })
    markDirty()
  }
  function stampSprite(x: number, y: number) {
    if (!map) return
    const s = SPRITE_CATALOG.find((s) => s.id === activeSpriteRef.current)!
    map.objects.push({
      id: 'sprite_' + addN.current++, kind: 'sprite', x, y, color: '#8fae7a', icon: s.icon,
      note: s.id === 'needsart' ? 'NEEDS_ART' : undefined,
      asset: { gen: 'map-object', dirs: 1, view: 'high top-down', anim: s.anim, loop: s.loop, status: 'needs-art' },
    })
    markDirty()
  }
  function paintCollision(cx: number, cy: number) {
    if (!map) return
    const size = brushRef.current.size, off = Math.floor(size / 2)
    const keys: string[] = []
    for (let dx = 0; dx < size; dx++) for (let dy = 0; dy < size; dy++) {
      const x = Math.max(0, Math.min(map.W - 1, cx - off + dx)), y = Math.max(0, Math.min(map.H - 1, cy - off + dy))
      keys.push(x + ',' + y)
    }
    const regions = collision.current[activeId] || (collision.current[activeId] = [])
    if (brushRef.current.mode === 'clear') {
      for (const r of regions) r.tiles = r.tiles.filter((k) => !keys.includes(k))
      collision.current[activeId] = regions.filter((r) => r.tiles.length > 0)
    } else {
      let region = paintingRegionRef.current
      if (!region) { region = { id: 'boundary_' + addN.current++, tiles: [], mode: 'block' }; paintingRegionRef.current = region; regions.push(region) }
      for (const k of keys) if (!region.tiles.includes(k)) region.tiles.push(k)
    }
    markDirty()
  }
  function commitZone() {
    if (!map || !zoneDraftRef.current) return
    const zd = zoneDraftRef.current
    const x0 = Math.min(zd.x0, zd.x1), y0 = Math.min(zd.y0, zd.y1), x1 = Math.max(zd.x0, zd.x1), y1 = Math.max(zd.y0, zd.y1)
    if (x1 - x0 < 1 || y1 - y0 < 1) return
    const z: Zone = { id: 'zone_' + addN.current++, x: x0, y: y0, w: x1 - x0 + 1, h: y1 - y0 + 1, c: ZONE_COLORS[map.zones.length % ZONE_COLORS.length], l: 'New Zone', role: 'label' }
    map.zones.push(z); selRef.current = { kind: 'zone', zone: z }; markDirty()
  }
  function deleteSelected() {
    if (!map || !selRef.current) return
    if (selRef.current.kind === 'object') map.objects = map.objects.filter((o) => o !== (selRef.current as any).obj)
    else if (selRef.current.kind === 'zone') map.zones = map.zones.filter((z) => z !== (selRef.current as any).zone)
    else if (selRef.current.kind === 'boundary') collision.current[activeId] = (collision.current[activeId] || []).filter((r) => r !== (selRef.current as any).region)
    selRef.current = null; markDirty()
  }

  // ---------- export DSL (Prompt Starter + layout + pixel assets) ----------
  function annotSuffix(o: Annot, idFallback: string) {
    let s = ''
    if (o.name && o.name !== idFallback) s += ` name="${o.name}"`
    if (o.desc) s += ` desc="${o.desc}"`
    if (o.intent) s += ` intent="${o.intent}"`
    return s
  }
  function pixelAssetLines(m: MapData): string[] {
    const needsObjs = m.objects.filter((o) => o.asset && o.asset.status === 'needs-art')
    const needsZones = m.zones.filter((z) => z.asset && z.asset.status === 'needs-art')
    const total = needsObjs.length + needsZones.length
    if (!total) return []
    const bg = m.image.split('/').pop()
    const lines = [`PIXEL ASSETS · map=${activeId} · ${total} need art  (px = tiles×48, style-match to ${bg})`]
    let i = 1
    for (const o of needsObjs) {
      const a = o.asset!
      const wT = o.w || 1, hT = o.h || 1
      const pxW = Math.min(400, wT * 48), pxH = Math.min(400, hT * 48)
      const tool = a.gen === 'character' ? 'create_character → animate_character'
        : a.anim === 'state-toggle' ? 'create_map_object → create_object_state'
        : a.anim === 'idle-loop' ? 'create_map_object → animate_object'
        : 'create_map_object'
      lines.push(`${i++}. ${o.name || o.id}  @ tile[${o.x},${o.y}]  size ${wT}x${hT} (${pxW}x${pxH}px)  view=${a.view}`)
      lines.push(`   tool: ${tool}`)
      if (a.states?.length) lines.push(`   states: ${a.states.join(' | ')}`)
      if (a.actions?.length) lines.push(`   actions: ${a.actions.join(', ')}`)
      if (a.loop) lines.push(`   loop: ${a.loop}`)
      if (a.prompt) lines.push(`   prompt: "${a.prompt}"`)
      if (o.intent) lines.push(`   intent: "${o.intent}"`)
    }
    for (const z of needsZones) {
      lines.push(`${i++}. ${z.l}  rect=[${z.x},${z.y}..${z.x + z.w - 1},${z.y + z.h - 1}]  role=terrain`)
      lines.push('   tool: create_topdown_tileset')
      if (z.intent) lines.push(`   intent: "${z.intent}"`)
    }
    return lines
  }
  const dsl = useMemo(() => {
    if (!map) return ''
    const lines: string[] = []
    lines.push('LASHIRA OPENWORLD MAP BRIEF')
    lines.push(PROJECT_LINE)
    lines.push(`Style: ${STYLE_ANCHOR}`)
    lines.push(GRID_NOTE)
    lines.push(`Map: ${activeId} · ${map.name} · ${map.sub}`)
    lines.push(`Scene: ${map.scene}`)
    lines.push(READ_NOTE)
    lines.push('')
    lines.push(`LASHIRA OPENWORLD EDIT · map=${activeId} · rev=${rev[activeId] || 1} · grid=${map.W}x${map.H}`)

    const portals = map.objects.filter((o) => o.kind === 'portal')
    const restObjs = map.objects.filter((o) => o.kind !== 'portal' && o.kind !== 'sprite')
    const sprites = map.objects.filter((o) => o.kind === 'sprite')
    if (portals.length) {
      lines.push('PORTALS')
      for (const o of portals) lines.push(`  ${o.id.padEnd(18)} tile=[${o.x},${o.y}] icon=${o.icon} color=${o.color} hitR=${o.hitR || 1}${annotSuffix(o, o.id)}${o.note ? `  note="${o.note}"` : ''}`)
    }
    if (map.zones.length) {
      lines.push('ZONES')
      for (const z of map.zones) lines.push(`  ${z.l.replace(/\s+/g, '_').toLowerCase().padEnd(16)} rect=[${z.x},${z.y}..${z.x + z.w - 1},${z.y + z.h - 1}] color=${z.c} label="${z.l}" role=${z.role || 'label'}${annotSuffix(z, z.l)}`)
    }
    const regions = collision.current[activeId] || []
    if (regions.length) {
      lines.push('COLLISION')
      for (const r of regions) lines.push(`  ${(r.name || r.id).padEnd(18)} tiles=${r.tiles.length} mode=${r.mode}${annotSuffix(r, r.id)}`)
    }
    if (restObjs.length) {
      lines.push('OBJECTS')
      for (const o of restObjs) lines.push(`  ${o.id.padEnd(18)} tile=[${o.x},${o.y}] kind=${o.kind} icon=${o.icon} color=${o.color}${annotSuffix(o, o.id)}`)
    }
    if (sprites.length) {
      lines.push('SPRITES')
      for (const o of sprites) lines.push(`  ${o.id.padEnd(18)} tile=[${o.x},${o.y}]${annotSuffix(o, o.id)}${o.note ? `  note="${o.note}"` : ''}`)
    }
    const pixelLines = pixelAssetLines(map)
    if (pixelLines.length) { lines.push(''); lines.push(...pixelLines) }
    return lines.join('\n')
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [map, activeId, rev])

  const [copied, setCopied] = useState(false)
  function copyDsl() { navigator.clipboard?.writeText(dsl); setCopied(true); setTimeout(() => setCopied(false), 1300) }

  // ---------- export: map snapshot + prompt bundled into one self-contained HTML file ----------
  function escapeHtml(s: string) { return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;') }
  function snapshotDataUrl(): string {
    if (!map) return ''
    const off = document.createElement('canvas')
    off.width = map.W * TP; off.height = map.H * TP
    const octx = off.getContext('2d')!
    const savedCam = camRef.current
    camRef.current = { x: 0, y: 0, zoom: 1 } // world-space, scale 1, for a clean full-map render
    draw({ ctx: octx, vw: off.width, vh: off.height, clean: true })
    camRef.current = savedCam
    return off.toDataURL('image/png')
  }
  function buildExportHtml(): string {
    if (!map) return ''
    const snap = snapshotDataUrl()
    return `<!doctype html>
<html><head><meta charset="utf-8"><title>LashiraBloom — ${escapeHtml(map.name)} export</title>
<style>
  body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#0c0c12;color:#f4f4f5;padding:24px}
  h1{font-size:18px;margin:0 0 4px}
  .sub{color:#a1a1aa;font-size:11px;margin:0 0 20px;font-family:ui-monospace,monospace;text-transform:uppercase;letter-spacing:.08em}
  .wrap{display:grid;grid-template-columns:1fr 1fr;gap:20px;max-width:1400px;margin:0 auto;align-items:start}
  @media (max-width:900px){.wrap{grid-template-columns:1fr}}
  .panel{background:#121219;border:1px solid #23232c;border-radius:13px;padding:14px}
  img{max-width:100%;height:auto;image-rendering:pixelated;border-radius:9px;border:1px solid #23232c;display:block}
  pre{white-space:pre-wrap;font-family:ui-monospace,monospace;font-size:12px;line-height:1.6;margin:0;max-height:80vh;overflow:auto}
  .copybtn{margin-bottom:10px;background:#6366f1;color:#fff;border:none;border-radius:7px;padding:7px 14px;font-weight:700;font-size:12px;cursor:pointer}
  .copybtn.done{background:#16a34a}
</style></head>
<body>
  <h1>LashiraBloom Openworld Export</h1>
  <p class="sub">${escapeHtml(map.name)} (${activeId}) · rev ${rev[activeId] || 1} · generated ${new Date().toISOString()}</p>
  <div class="wrap">
    <div class="panel"><img src="${snap}" alt="${escapeHtml(map.name)} map snapshot" /></div>
    <div class="panel">
      <button class="copybtn" onclick="navigator.clipboard.writeText(document.getElementById('prompt').textContent); this.textContent='Copied ✓'; this.classList.add('done'); setTimeout(()=>{this.textContent='Copy prompt';this.classList.remove('done')},1300)">Copy prompt</button>
      <pre id="prompt">${escapeHtml(dsl)}</pre>
    </div>
  </div>
</body></html>`
  }
  const [exported, setExported] = useState(false)
  function downloadExport() {
    if (!map) return
    const html = buildExportHtml()
    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = `lashira-openworld-${activeId}-rev${rev[activeId] || 1}.html`
    document.body.appendChild(a); a.click(); a.remove()
    URL.revokeObjectURL(url)
    setExported(true); setTimeout(() => setExported(false), 1300)
  }

  if (!maps || !map) return <div className="owb-loading">Loading the real map + component data…</div>

  const sel = selRef.current
  const gapNote = map.objects.find((o) => o.note)?.note
  const collisionTileCount = (collision.current[activeId] || []).reduce((s, r) => s + r.tiles.length, 0)

  return (
    <div className="openworld-builder">
      <div className="owb-top">
        <div className="owb-mark">🗺️</div>
        <div className="owb-title"><b>Openworld Builder</b><span>Circle HQ · LashiraBloom</span></div>
        <div className="owb-inv"><span>Active map</span><b>{map.name}</b><span>·</span><span>rev</span><b>{rev[activeId] || 1}</b></div>
      </div>

      <div className="owb-tabs">
        {MAP_ORDER.map((id) => (
          <button key={id} className={'owb-tab' + (id === activeId ? ' on' : '')} onClick={() => { setActiveId(id); selRef.current = null; measureRef.current = { a: null, b: null } }}>
            <span className="tn" style={{ background: MAP_META[id].swatch }}>{MAP_ICON[id]}</span>
            <span className="txt"><b>{MAP_META[id].name}</b><small>{MAP_META[id].sub}</small></span>
            <span className="tnum">{map && id === activeId ? `${map.W}×${map.H}` : ''}</span>
          </button>
        ))}
      </div>

      <div className="owb-body">
        <div className="owb-col left">
          <div className="owb-sec">
            <h4>Tools</h4>
            <div className="owb-tools">
              {TOOLS.map((t) => (
                <button key={t.id} className={'owb-tool' + (tool === t.id ? ' on' : '')} onClick={() => setTool(t.id)}>
                  <span className="ic">{t.icon}</span>{t.label}
                </button>
              ))}
            </div>
          </div>
          <div className="owb-sec">
            <h4>Layers</h4>
            {LAYER_DEFS.map(({ id: k, label, color }) => {
              const cnt = k === 'objects' ? map.objects.filter((o) => o.kind !== 'sprite').length
                : k === 'sprites' ? map.objects.filter((o) => o.kind === 'sprite').length
                : k === 'zones' ? map.zones.length
                : k === 'collision' ? collisionTileCount : ''
              const on = layerVis.current[k], locked = layerLock.current[k]
              return (
                <div key={k} className={'owb-layer' + (on ? ' on' : '') + (locked ? ' locked' : '')}>
                  <span className="dot" style={{ background: color }} aria-hidden="true" />
                  <button type="button" className="eyebtn" onClick={() => { layerVis.current[k] = !layerVis.current[k]; forceRender() }} title={on ? 'Hide layer' : 'Show layer'}>
                    {on ? <Eye size={13} /> : <EyeOff size={13} />}
                  </button>
                  <span className="nm">{label}</span><span className="ct">{cnt}</span>
                  <button type="button" className="lockbtn" onClick={() => { layerLock.current[k] = !layerLock.current[k]; forceRender() }} title={locked ? 'Unlock layer' : 'Lock layer'}>
                    {locked ? <Lock size={12} /> : <LockOpen size={12} />}
                  </button>
                </div>
              )
            })}
          </div>
          <div className="owb-sec grow">
            <h4>Objects <span className="cnt">{map.objects.length + map.zones.length + (collision.current[activeId]?.length || 0)}</span></h4>
            <div className="owb-objlist">
              {map.objects.map((o) => (
                <div key={o.id} className={'owb-obj' + (sel?.kind === 'object' && sel.obj === o ? ' sel' : '')} onClick={() => { selRef.current = { kind: 'object', obj: o }; setTool('select'); forceRender() }}>
                  <span className="dot" style={{ background: objColor(o) }}>{o.icon}</span><span className="nm">{o.name || o.id}</span><span className="co">{o.x},{o.y}</span>
                </div>
              ))}
              {map.zones.map((z) => (
                <div key={z.id} className={'owb-obj' + (sel?.kind === 'zone' && sel.zone === z ? ' sel' : '')} onClick={() => { selRef.current = { kind: 'zone', zone: z }; setTool('select'); forceRender() }}>
                  <span className="dot" style={{ background: z.c }}>▭</span><span className="nm">{z.l}</span><span className="co">{z.w}×{z.h}</span>
                </div>
              ))}
              {(collision.current[activeId] || []).map((r) => (
                <div key={r.id} className={'owb-obj' + (sel?.kind === 'boundary' && sel.region === r ? ' sel' : '')} onClick={() => { selRef.current = { kind: 'boundary', region: r }; setTool('select'); forceRender() }}>
                  <span className="dot" style={{ background: '#dc2626' }}>🧱</span><span className="nm">{r.name || r.id}</span><span className="co">{r.tiles.length}px</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="owb-col center">
          <div className="owb-stagebar">
            <span className="owb-chip">tile {hoverRef.current ? `[${hoverRef.current.tx}, ${hoverRef.current.ty}]` : '—'}</span>
            <span className="owb-chip">{Math.round(camRef.current.zoom * 100)}%</span>
            <div className="owb-spacer" />
            <button className="owb-zbtn" onClick={() => { camRef.current = { ...camRef.current, zoom: Math.max(0.25, camRef.current.zoom * 0.83) }; forceRender() }}>－</button>
            <button className="owb-zbtn" onClick={() => { fit(); forceRender() }}>⊡</button>
            <button className="owb-zbtn" onClick={() => { camRef.current = { ...camRef.current, zoom: Math.min(4, camRef.current.zoom * 1.2) }; forceRender() }}>＋</button>
          </div>
          <div className="owb-stage" ref={stageRef}>
            <canvas ref={canvasRef}
              onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={onPointerUp}
              onWheel={onWheel} style={{ cursor: tool === 'select' ? 'grab' : 'crosshair' }} />
            <div className="owb-hint">{HINTS[tool]}</div>
          </div>
        </div>

        <div className="owb-col right">
          <div className="owb-sec">
            <h4>Inspector</h4>
            {sel?.kind === 'zone' ? (
              <div className="owb-insp">
                <div className="selhead"><span className="badge" style={{ background: sel.zone.c }}>▭</span><div><b>{sel.zone.l}</b><small>Zone region</small></div></div>
                <label className="fl">Label</label>
                <input className="owb-input" value={sel.zone.l} onChange={(e) => { sel.zone.l = e.target.value; markDirty() }} />
                <label className="fl">Intent</label>
                <textarea className="owb-textarea" rows={2} placeholder="What do you want here?" value={sel.zone.intent ?? ''} onChange={(e) => { sel.zone.intent = e.target.value; markDirty() }} />
                <div className="field"><label>Rect</label><span className="val">{sel.zone.w}×{sel.zone.h} @ [{sel.zone.x},{sel.zone.y}]</span></div>
                <label className="fl">Role</label>
                <div className="toggle3">
                  {(['label', 'terrain', 'trigger'] as const).map((r) => (
                    <button key={r} className={sel.zone.role === r || (!sel.zone.role && r === 'label') ? 'on' : ''} onClick={() => { sel.zone.role = r; if (r === 'terrain') ensureAsset(sel.zone, 'zone'); markDirty() }}>{r}</button>
                  ))}
                </div>
                {sel.zone.role === 'terrain' && (
                  <div className="owb-note">Terrain zone → export uses <code>create_topdown_tileset</code>. Describe the terrain in Intent (e.g. "cobblestone plaza transitioning to grass").</div>
                )}
                <div className="fl">Color</div>
                <div className="swatchrow">{ZONE_COLORS.map((c) => <div key={c} className={'swatch' + (sel.zone.c === c ? ' on' : '')} style={{ background: c }} onClick={() => { sel.zone.c = c; markDirty() }} />)}</div>
                <button className="owb-del" onClick={deleteSelected}>Delete zone</button>
              </div>
            ) : sel?.kind === 'boundary' ? (
              <div className="owb-insp">
                <div className="selhead"><span className="badge" style={{ background: '#dc2626' }}>🧱</span><div><b>{sel.region.name || sel.region.id}</b><small>Boundary region</small></div></div>
                <label className="fl">Name</label>
                <input className="owb-input" value={sel.region.name ?? ''} placeholder={sel.region.id} onChange={(e) => { sel.region.name = e.target.value; markDirty() }} />
                <label className="fl">Intent</label>
                <textarea className="owb-textarea" rows={2} placeholder="Why is this blocked? e.g. &quot;wall&quot;, &quot;counter edge&quot;, &quot;water&quot;" value={sel.region.intent ?? ''} onChange={(e) => { sel.region.intent = e.target.value; markDirty() }} />
                <div className="field"><label>Tiles</label><span className="val">{sel.region.tiles.length}</span></div>
                <div className="field"><label>Mode</label><span className="val">{sel.region.mode}</span></div>
                <button className="owb-del" onClick={deleteSelected}>Delete boundary</button>
              </div>
            ) : sel?.kind === 'object' ? (
              <div className="owb-insp">
                <div className="selhead"><span className="badge" style={{ background: objColor(sel.obj) }}>{sel.obj.icon}</span><div><b>{sel.obj.name || sel.obj.id}</b><small>{KIND_LABEL[sel.obj.kind] || sel.obj.kind}</small></div></div>
                <label className="fl">Name</label>
                <input className="owb-input" value={sel.obj.name ?? ''} placeholder={sel.obj.id} onChange={(e) => { sel.obj.name = e.target.value; markDirty() }} />
                <label className="fl">Intent</label>
                <textarea className="owb-textarea" rows={2} placeholder="What do you want here?" value={sel.obj.intent ?? ''} onChange={(e) => { sel.obj.intent = e.target.value; markDirty() }} />
                <div className="field"><label>Tile</label><div className="coordbox">
                  <input value={sel.obj.x} onChange={(e) => { sel.obj.x = Math.max(0, Math.min(map.W - 1, +e.target.value || 0)); markDirty() }} />
                  <input value={sel.obj.y} onChange={(e) => { sel.obj.y = Math.max(0, Math.min(map.H - 1, +e.target.value || 0)); markDirty() }} />
                </div></div>
                <div className="field"><label>Hit radius</label><span className="val">{sel.obj.hitR || 1} tiles</span></div>
                <div className="field"><label>Color</label><span className="val" style={{ color: objColor(sel.obj) }}>{objColor(sel.obj)}</span></div>

                {sel.obj.kind === 'station' && (
                  <>
                    <label className="fl">Station type</label>
                    <div className="chiprow">
                      {Object.keys(STATION_SUBTYPES).map((st) => (
                        <button key={st} type="button" className={'chip pick' + (sel.obj.subtype === st ? ' on' : '')}
                          onClick={() => { sel.obj.subtype = st; ensureAsset(sel.obj, 'station'); sel.obj.asset!.states = [...STATION_SUBTYPES[st]]; markDirty() }}>{st}</button>
                      ))}
                    </div>
                  </>
                )}

                <label className="fl">Animation</label>
                <select className="owb-select" value={sel.obj.asset?.anim ?? 'none'} onChange={(e) => { ensureAsset(sel.obj, sel.obj.kind); sel.obj.asset!.anim = e.target.value as AnimType; markDirty() }}>
                  {animOptionsFor(sel.obj.kind).map((o) => <option key={o} value={o}>{o}</option>)}
                </select>
                {sel.obj.asset?.anim === 'state-toggle' && (
                  <ChipEditor label="States" items={sel.obj.asset.states || []} onChange={(arr) => { ensureAsset(sel.obj, sel.obj.kind); sel.obj.asset!.states = arr; markDirty() }} />
                )}
                {sel.obj.asset?.anim === 'idle-loop' && (
                  <>
                    <label className="fl">Loop style</label>
                    <select className="owb-select" value={sel.obj.asset.loop ?? ''} onChange={(e) => { sel.obj.asset!.loop = e.target.value || undefined; markDirty() }}>
                      <option value="">—</option><option value="pulse">pulse</option><option value="sway">sway</option><option value="flicker">flicker</option><option value="wave">wave</option><option value="flow">flow</option>
                    </select>
                  </>
                )}
                {sel.obj.kind === 'npc' && (
                  <ChipEditor label="Actions" items={sel.obj.asset?.actions || []} onChange={(arr) => { ensureAsset(sel.obj, 'npc'); sel.obj.asset!.actions = arr; markDirty() }} />
                )}

                <label className="fl">Art status</label>
                <div className="toggle2">
                  <button className={sel.obj.asset?.status !== 'has-art' ? 'on' : ''} onClick={() => { ensureAsset(sel.obj, sel.obj.kind); sel.obj.asset!.status = 'needs-art'; markDirty() }}>Needs art</button>
                  <button className={sel.obj.asset?.status === 'has-art' ? 'on' : ''} onClick={() => { ensureAsset(sel.obj, sel.obj.kind); sel.obj.asset!.status = 'has-art'; markDirty() }}>Has art</button>
                </div>

                {sel.obj.note && <div className="owb-note">⚠ {sel.obj.note}</div>}
                {sel.obj.kind !== 'portal' && <button className="owb-del" onClick={deleteSelected}>Delete object</button>}
              </div>
            ) : tool === 'collision' ? (
              <div className="owb-insp">
                <p className="owb-cap">Drag to paint one named blocked region per stroke.</p>
                <label className="fl">Mode</label>
                <div className="toggle2">
                  <button className={brushRef.current.mode === 'block' ? 'on' : ''} onClick={() => { brushRef.current.mode = 'block'; forceRender() }}>Block</button>
                  <button className={brushRef.current.mode === 'clear' ? 'on' : ''} onClick={() => { brushRef.current.mode = 'clear'; forceRender() }}>Clear</button>
                </div>
                <label className="fl">Brush size</label>
                <div className="sizebtns">{([1, 3, 5] as const).map((s) => <button key={s} className={brushRef.current.size === s ? 'on' : ''} onClick={() => { brushRef.current.size = s; forceRender() }}>{s}</button>)}</div>
              </div>
            ) : tool === 'sprite' ? (
              <div className="owb-insp">
                <p className="owb-cap">Pick a sprite type, then click the map to stamp it. Its default animation is set automatically.</p>
                <div className="spritepal">
                  {SPRITE_CATALOG.map((s) => (
                    <div key={s.id} className={'sprchip' + (activeSpriteRef.current === s.id ? ' on' : '') + (s.id === 'needsart' ? ' needsart' : '')}
                      title={s.id === 'needsart' ? 'Custom — flags a generation prompt' : `${s.label} · ${s.anim}${s.loop ? ' · ' + s.loop : ''}`}
                      onClick={() => { activeSpriteRef.current = s.id; forceRender() }}>
                      <span>{s.icon}</span><small>{s.label}</small>
                    </div>
                  ))}
                </div>
              </div>
            ) : tool === 'zone' ? (
              <p className="owb-cap">Drag a rectangle on the map to draw a named zone. Rename + recolor it right after.</p>
            ) : tool === 'marker' ? (
              <div className="owb-insp">
                <p className="owb-cap">Pick what to place, then click the map.</p>
                <div className="chiprow">
                  {MARKER_KINDS.map((k) => (
                    <button key={k.id} type="button" className={'chip pick' + (markerKindRef.current === k.id ? ' on' : '')} onClick={() => { markerKindRef.current = k.id; forceRender() }}>{k.icon} {k.label}</button>
                  ))}
                </div>
              </div>
            ) : tool === 'measure' ? (
              <p className="owb-cap">Click two points to read the tile distance — not saved to the export.</p>
            ) : (
              <p className="owb-cap">Click a marker, zone, or boundary region to edit it, or drag a marker to reposition. Everything here flows into the export prompt below.</p>
            )}
          </div>

          <div className="owb-sec">
            <h4>Prompt Starter <button type="button" className="owb-linkbtn" onClick={() => setBriefOpen((o) => !o)}>{briefOpen ? 'Hide' : 'Edit'}</button></h4>
            {briefOpen && (
              <>
                <p className="owb-cap">{PROJECT_LINE}</p>
                <p className="owb-cap">{STYLE_ANCHOR}</p>
                <p className="owb-cap">{GRID_NOTE}</p>
                <label className="fl">Scene (editable)</label>
                <textarea className="owb-textarea" rows={4} value={map.scene} onChange={(e) => { map.scene = e.target.value; markDirty() }} />
              </>
            )}
          </div>

          <div className="owb-export">
            <div className="head">
              <h4>Export prompt</h4>
              <div className="owb-exportbtns">
                <button className={'owb-copy' + (copied ? ' done' : '')} onClick={copyDsl}>{copied ? 'Copied ✓' : 'Copy'}</button>
                <button className={'owb-copy secondary' + (exported ? ' done' : '')} onClick={downloadExport}>{exported ? 'Saved ✓' : 'Export HTML'}</button>
              </div>
            </div>
            <pre className="owb-dsl">{dsl}</pre>
            {gapNote && <div className="owb-note owb-note-bottom">⚠ {gapNote}</div>}
          </div>
        </div>
      </div>
    </div>
  )
}
