// B2 · Stage-0 deterministic APPLICATION shell — the app twin of
// studios/engines.ts's makeWebsite(). Same discipline: same brief → same
// output, $0, instant, never depends on AI succeeding. A real single-file CRUD
// shell (add/edit/delete, localStorage persistence, empty state) — not a
// placeholder — because it's also the honest fallback when Stage-1 AI
// generation fails validation (Single-File-Builder.md's tiered generation).
import { makeBrand, type BrandKit } from '../surfaces/studios/engines'

function esc(s: string) { return String(s).replace(/[&<>"]/g, (m) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[m]!)) }

function titleFrom(brief: string): string {
  const first = (brief.split(/[—\-,.\n]/)[0] || 'App').trim()
  return first.slice(0, 40) || 'App'
}

/** A generic single-file CRUD shell: add/edit/delete records, localStorage
 * persistence keyed by a hash of the brief (so re-generating the same brief
 * reuses the same storage key deterministically), empty state, no TODOs. */
export function makeAppShell(brief: string, brand: BrandKit = makeBrand(brief)): string {
  const title = titleFrom(brief)
  const c = brand.colors
  const storeKey = 'arganta_app_' + Math.abs(hashCode(brief)).toString(36)
  return `<!doctype html><html><head><meta charset="utf8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>
*{margin:0;box-sizing:border-box}body{font-family:${brand.fonts.body};color:${c.ink};background:${c.bg};min-height:100vh}
header{padding:20px 5vw;display:flex;align-items:center;gap:12px;border-bottom:1px solid #ffffff22}
header h1{font-family:${brand.fonts.head};font-size:20px;font-weight:700}
main{padding:20px 5vw;max-width:720px;margin:0 auto}
.row{display:flex;gap:8px;margin-bottom:20px}
input{flex:1;padding:12px 14px;border-radius:10px;border:1px solid #ffffff33;background:#ffffff10;color:${c.ink};font-size:15px}
button{padding:12px 20px;border-radius:10px;border:0;background:${c.accent};color:#1a1030;font-weight:700;cursor:pointer;min-height:44px}
button:active{opacity:.85}
.list{display:flex;flex-direction:column;gap:10px}
.item{display:flex;align-items:center;gap:10px;padding:14px 16px;border-radius:12px;background:#ffffff10;border:1px solid #ffffff1a}
.item span{flex:1}
.item button{padding:8px 12px;font-size:13px;background:transparent;border:1px solid #ffffff33;color:${c.ink};font-weight:600}
.empty{opacity:.6;text-align:center;padding:12vh 0;font-size:15px}
footer{padding:5vh 6vw;text-align:center;opacity:.5;font-size:12px}
</style></head><body>
<header><h1>${esc(title)}</h1></header>
<main>
  <div class="row"><input id="in" placeholder="Add an item…" aria-label="New item"><button id="add">Add</button></div>
  <div class="list" id="list" role="list"></div>
  <div class="empty" id="empty" hidden>No items yet. Add your first one above.</div>
</main>
<footer>${esc(brand.name)} · generated by Arganta Core (deterministic Stage-0)</footer>
<script>
(function(){
  var KEY='${storeKey}';
  function load(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){return []}}
  function save(items){try{localStorage.setItem(KEY,JSON.stringify(items))}catch(e){}}
  var items=load();
  var list=document.getElementById('list'), empty=document.getElementById('empty'), input=document.getElementById('in');
  function render(){
    list.innerHTML='';
    empty.hidden=items.length>0;
    items.forEach(function(it,i){
      var row=document.createElement('div'); row.className='item'; row.setAttribute('role','listitem');
      var span=document.createElement('span'); span.textContent=it;
      var del=document.createElement('button'); del.textContent='Remove'; del.setAttribute('aria-label','Remove '+it);
      del.onclick=function(){ items.splice(i,1); save(items); render(); };
      row.appendChild(span); row.appendChild(del); list.appendChild(row);
    });
  }
  function add(){ var v=input.value.trim(); if(!v) return; items.push(v); save(items); input.value=''; render(); }
  document.getElementById('add').onclick=add;
  input.addEventListener('keydown',function(e){ if(e.key==='Enter') add(); if(e.key==='Escape') input.value=''; });
  render();
})();
</script>
</body></html>`
}

function hashCode(s: string): number {
  let h = 0
  for (let i = 0; i < s.length; i++) { h = (h << 5) - h + s.charCodeAt(i); h |= 0 }
  return h
}
