import { CheckCheck, Gauge, LineChart, ListChecks, Radar, Stethoscope, Target, TrendingUp, Waves } from 'lucide-react';
import { widget, type WorkflowGroup } from '../workspace-blueprint/types';

export const RESERVOIR_WORKFLOWS: WorkflowGroup[] = [
  { id: 'monitor', name: 'Monitor', short: 'Monitor', question: 'What changed and where?', tabs: [
    { id: 'performance-overview', name: 'Field Performance Overview', short: 'Performance', blurb: 'Field performance overview', icon: Gauge, purpose: 'Provide an exception-first view of field health against the current plan.', software: 'SLB OFM-lite', output: 'PerformanceSnapshot', legacyStrength: 'Legacy Overview has field KPIs, health scoring, exceptions and real Volve aggregation.', legacyGap: 'Bound to bundled data; no client ingestion, approved baseline, alert ownership or snapshot version.', widgets: [
      widget('Performance cockpit', 'Summarize rate, uptime, pressure, VRR and forecast variance.', 'Client production/injection/pressure · approved forecast', 'KPI cockpit + sparklines', 'React · SVG', 'FieldPerformanceCockpit', 'client-gated', 'Legacy Overview'),
      widget('Exception queue', 'Rank material deviations by value, persistence and confidence.', 'Truth-locked surveillance engine · client time series', 'Ranked exception table', 'd3-array · React', 'ReservoirExceptionQueue', 'client-gated', 'Legacy wellHealth/detectExceptions'),
      widget('Plan variance', 'Show actual versus plan and accountable loss categories.', 'Client actuals · Field Development/RM baseline', 'Variance waterfall + fan chart', 'd3-shape · SVG', 'FieldPlanVariance', 'new', 'Legacy lacks a governed plan baseline'),
    ]},
    { id: 'surveillance-coverage', name: 'Surveillance & Data Coverage', short: 'Surveillance', blurb: 'Data coverage and gaps', icon: Radar, purpose: 'Track acquisition coverage, quality, recency and decision-critical gaps.', software: 'SLB OFM surveillance-lite', output: 'SurveillancePlan', legacyStrength: 'Legacy Surveillance has coverage matrices and honest no-data states.', legacyGap: 'Coverage is Volve-specific, 4D/PLT absent, and there is no client programme, owner or value-of-information link.', widgets: [
      widget('Coverage matrix', 'Show latest measurement and status by reservoir/pattern/well.', 'Client surveillance inventory', 'Coverage heatmap', 'React · CSS Grid', 'SurveillanceCoverageMatrix', 'client-gated', 'Legacy Surveillance'),
      widget('Acquisition timeline', 'Visualize measurement history and upcoming programme.', 'Client acquisition events · planned activities', 'Calendar/Gantt hybrid', 'd3-scale · SVG', 'AcquisitionTimeline', 'client-gated', 'Legacy coverage has limited time planning'),
      widget('Data-gap priorities', 'Rank missing measurements by decision impact.', 'Coverage gaps · opportunity/uncertainty register', 'Priority matrix + action list', 'd3-array · React', 'SurveillanceGapPrioritizer', 'new', 'Legacy identifies gaps but does not value them'),
    ]},
    { id: 'production-validation', name: 'Production & Injection Validation', short: 'Validation', blurb: 'Production and injection allocation', icon: CheckCheck, purpose: 'Validate allocated client volumes, uptime and injection before diagnosis.', software: 'SLB OFM data validation-lite', output: 'ValidatedProductionSeries', legacyStrength: 'Legacy has monthly series builders, WCT/GOR, uptime, VRR and robust exception functions.', legacyGap: 'No client import mapping, allocation reconciliation, revision handling or approval state.', widgets: [
      widget('Data reconciliation', 'Reconcile field totals, well allocations and revisions.', 'Client production accounting/export', 'Balance table + reconciliation waterfall', 'd3-array · React', 'ProductionReconciliation', 'client-gated', 'Legacy assumes prepared wb monthly files'),
      widget('Quality timeline', 'Flag missing, stale, substituted and revised values.', 'Client time-series quality flags', 'Quality ribbon + time series', 'd3-shape · SVG', 'ProductionQualityTimeline', 'client-gated', 'Legacy has no source-quality metadata'),
      widget('Allocation checks', 'Detect rate, uptime and role inconsistencies.', 'Validated client streams · well master', 'Exception scatter + rule table', 'd3-scale · SVG', 'AllocationValidationPanel', 'client-gated', 'Legacy data.ts builders'),
    ]},
  ]},
  { id: 'diagnose', name: 'Diagnose', short: 'Diagnose', question: 'Why is performance changing?', tabs: [
    { id: 'production-diagnostics', name: 'Production Diagnostics', short: 'Diagnostics', blurb: 'Water, gas, well behaviour', icon: Stethoscope, purpose: 'Diagnose rate, water and gas behavior using the established OFM-style diagnostic set.', software: 'SLB OFM-lite', output: 'ProductionDiagnosis', legacyStrength: 'Legacy Production has the nine-panel diagnostic grid and truth-locked WOR/GOR exception logic.', legacyGap: 'Client data not yet gated, selection/cohort state is local, and diagnoses do not become governed records.', widgets: [
      widget('Diagnostic grid', 'Link rate, cumulative, WCT, WOR, GOR and uptime diagnostics.', 'Validated client production series', 'Nine synchronized diagnostic plots', 'Custom RMChart · SVG', 'ProductionDiagnosticGrid', 'reuse', 'Legacy Production + RMChart'),
      widget('Cohort comparator', 'Compare focus wells/patterns against selected peers.', 'Client well groups · validated series', 'Grey-cohort/focus overlays', 'Custom RMChart · d3-array', 'ProductionCohortComparator', 'adapt', 'Legacy RM_SELECTION focus/cohort pattern'),
      widget('Diagnosis record', 'Capture mechanism, confidence, evidence and next test.', 'Selected diagnostics · user interpretation', 'Structured diagnosis panel', 'React · Zustand', 'ProductionDiagnosisRecord', 'new', 'Legacy charts do not persist interpretation'),
    ]},
    { id: 'pressure-pattern', name: 'Pressure, VRR & Pattern Behaviour', short: 'Pressure', blurb: 'VRR and pattern behaviour', icon: Waves, purpose: 'Assess pressure support, injectivity, connectivity and sweep at field/pattern scale.', software: 'OFM · tNavigator surveillance-lite', output: 'PatternDiagnosis', legacyStrength: 'Legacy has VRR=1.023 validation, BHP/THP trends, Hall plots, patterns and streamline allocation.', legacyGap: 'Patterns are seeded, pressure datum/quality workflow is limited, and no calibrated connectivity/action record exists.', widgets: [
      widget('Pressure & Hall diagnostics', 'Track depletion, injectivity loss and fracture/thief signatures.', 'Client BHP/THP/injection series', 'Multi-well trend + Hall derivative', 'Custom RMChart · SVG', 'PressureHallDiagnostics', 'client-gated', 'Legacy Pressure; surveillance truth-lock'),
      widget('VRR balance', 'Compare produced voidage and injected replacement by pattern.', 'Client production/injection · PVT', 'Mirrored stacked bars + VRR line', 'Canvas 2D', 'PatternVrrViewer', 'reuse', 'Legacy VrrPanel'),
      widget('Pattern connectivity', 'Review producer/injector roles, allocation and water movement.', 'Client pattern definitions · streamline or allocation data', 'Pattern map + connectivity matrix', 'Canvas · d3-scale', 'PatternConnectivityViewer', 'adapt', 'Legacy Patterns + streamline engine'),
    ]},
    { id: 'welltest-decline', name: 'Well-Test & Decline Analysis', short: 'Well tests', blurb: 'Well-test and decline analysis', icon: LineChart, purpose: 'Evaluate client well tests and production decline with honest method boundaries.', software: 'KAPPA Ecrin · OFM-lite', output: 'WellPerformanceAssessment', legacyStrength: 'Legacy has well-test trend proxy, DCA fitting/blind tests, Chan/Tong/X-plot diagnostics.', legacyGap: 'No transient-pressure engine; existing well tests are allocated-rate proxies and must not be presented as PTA.', widgets: [
      widget('Well-test trend', 'Compare client test rates, WCT/GOR and operating events.', 'Client well-test allocation/events', 'Dual-axis trend + event pins', 'Canvas 2D', 'WellTestTrendViewer', 'client-gated', 'Legacy WelltestPanel; explicitly not PTA'),
      widget('Decline analysis', 'Fit exponential/hyperbolic decline and blind-test the forecast.', 'Validated client production series', 'Decline plot + residual diagnostics', 'd3-shape · SVG', 'DeclineAnalysisViewer', 'reuse', 'Legacy Forecast + review.ts'),
      widget('Water diagnosis', 'Screen coning, channeling and movable-oil trends.', 'Client oil/water history', 'Chan WOR + Tong/X-plot panels', 'Custom RMChart · SVG', 'WaterDiagnosisSuite', 'reuse', 'surveillance.ts 55/55 tests'),
    ]},
  ]},
  { id: 'optimize', name: 'Optimize', short: 'Optimize', question: 'What action creates value?', tabs: [
    { id: 'forecast-cases', name: 'Forecast & Reservoir Cases', short: 'Forecast', blurb: 'Reservoir cases and profiles', icon: TrendingUp, purpose: 'Maintain an approved base forecast and compare intervention scenarios.', software: 'INTERSECT · tNavigator-lite', output: 'ReservoirForecastCase', legacyStrength: 'Legacy Forecast has DCA, uncertainty fan charts and analog context.', legacyGap: 'No approved forecast version, intervention delta, simulation connection or rolling forecast workflow.', widgets: [
      widget('Base forecast', 'Create and validate the current reference forecast.', 'Validated client history · DCA/simulation basis', 'Fan chart + assumptions ledger', 'd3-shape · SVG', 'ReservoirBaseForecast', 'reuse', 'Legacy Forecast'),
      widget('Scenario forecast', 'Compare intervention uplift and uncertainty against base.', 'Opportunity scenarios · response assumptions', 'Incremental fan chart + delta table', 'd3-shape · SVG', 'ReservoirScenarioForecast', 'adapt', 'Legacy opportunities and forecast are separate'),
      widget('Forecast governance', 'Version, approve and monitor forecast staleness.', 'Forecast artifacts · evidence DAG', 'Version timeline + approval panel', 'React · Zustand', 'ForecastGovernancePanel', 'new', 'Legacy forecast state is not governed'),
    ]},
    { id: 'opportunity-screening', name: 'Opportunity Screening', short: 'Opportunities', blurb: 'Screening and ranking', icon: Target, purpose: 'Screen and rank rigless and rig-based opportunities with transparent value logic.', software: 'OFM · INTERSECT opportunity workflow-lite', output: 'ReservoirOpportunitySet', legacyStrength: 'Legacy Opportunities reuses break-even, reserves and analog engines.', legacyGap: 'Hard-coded opportunity types, no client opportunity authoring, technical maturation or shared Well Delivery handoff.', widgets: [
      widget('Opportunity funnel', 'Move observations through identify, screen, mature and approve.', 'Diagnosis records · user opportunities', 'Funnel + maturity board', 'React · CSS Grid', 'ReservoirOpportunityFunnel', 'adapt', 'Legacy Opportunities ranked register'),
      widget('Technical/economic screen', 'Compare recovery, cost, timing, risk and break-even.', 'Forecast deltas · user cost assumptions', 'Bubble chart + ranked table', 'd3-scale · SVG', 'OpportunityScreeningMatrix', 'reuse', 'review.ts findOpportunity/breakEven'),
      widget('Delivery handoff', 'Publish approved interventions to Well Delivery or action execution.', 'Approved opportunity artifact', 'Handoff contract + readiness check', 'React · Zustand', 'OpportunityDeliveryHandoff', 'new', 'Legacy cross-app link is only a stub'),
    ]},
    { id: 'actions-learning', name: 'Action Tracking & Model Update', short: 'Actions', blurb: 'Tracking and model update', icon: ListChecks, purpose: 'Track interventions through outcome verification and feed actual learning back into models.', software: 'OFM · Avocet workflow-lite', output: 'ReservoirActionLearning', legacyStrength: 'Legacy exposes observations and opportunities with an action-register concept.', legacyGap: 'No end-to-end owner/date/value tracking, outcome attribution, model update or analogue-library calibration.', widgets: [
      widget('Action register', 'Track owner, due date, trigger, status and expected value.', 'Approved diagnoses/opportunities · client work records', 'Action table + aging timeline', 'React · CSS Grid', 'ReservoirActionRegister', 'client-gated', 'Legacy local action concept'),
      widget('Outcome verification', 'Compare delivered response with forecast and baseline.', 'Client post-action actuals · scenario forecast', 'Before/after chart + value waterfall', 'd3-shape · SVG', 'InterventionOutcomeVerifier', 'client-gated', 'No Legacy closed-loop measurement'),
      widget('Model learning', 'Record parameter/analogue updates justified by actual outcomes.', 'Verified outcomes · model assumptions · Knowledge Bank', 'Prior/posterior comparison + lineage', 'd3-array · SVG', 'ReservoirModelLearning', 'new', 'Legacy does not close the calibration loop'),
    ]},
  ]},
];
