// mediaAssets — the persistence-first milestone (docs/media-center/
// Persistence-and-Provider-Strategy.md). Copies REAL generated bytes into the
// media-artifacts bucket and links the resulting row back to the agent_runs
// row that produced it (same run_id — prompt/provider/model/cost lineage).
// Never persists only a provider's temporary URL. Best-effort: a failed save
// never blocks the UI (the generation already succeeded) — it just means this
// one asset stays local-only, same honest-degrade contract as everywhere else.

import { supabase, cloudEnabled } from './supabase'

export interface SaveAssetInput {
  runId: string
  kind: 'image' | 'tts' | 'audio' | 'music' | 'video'
  bytes: Uint8Array
  mime: string
  width?: number
  height?: number
  duration?: number
  prompt: string
  provider: string
  model?: string | null
  costUsd?: number
}

const EXT: Record<string, string> = { 'image/png': 'png', 'image/jpeg': 'jpg', 'audio/mpeg': 'mp3', 'audio/wav': 'wav', 'audio/mp3': 'mp3' }

/** Upload bytes + record the media_asset row. Returns true only if BOTH steps succeeded. */
export async function saveMediaAsset(a: SaveAssetInput): Promise<boolean> {
  if (!cloudEnabled) return false
  try {
    const ext = EXT[a.mime] || a.mime.split('/')[1] || 'bin'
    const path = `${a.runId}.${ext}`
    const blob = new Blob([a.bytes as BlobPart], { type: a.mime })
    const { error: upErr } = await supabase.storage.from('media-artifacts').upload(path, blob, { contentType: a.mime, upsert: true })
    if (upErr) { console.warn('[media-artifacts upload]', upErr.message); return false }
    const { error: rpcErr } = await supabase.rpc('media_asset_save', {
      asset: {
        runId: a.runId, kind: a.kind, bucket: 'media-artifacts', path,
        mime: a.mime, bytes: a.bytes.length, width: a.width ?? null, height: a.height ?? null, duration: a.duration ?? null,
        prompt: a.prompt, provider: a.provider, model: a.model ?? null, costUsd: a.costUsd ?? 0,
      },
    })
    if (rpcErr) { console.warn('[media_asset_save]', rpcErr.message); return false }
    return true
  } catch (e) {
    console.warn('[media-artifacts] threw', (e as Error)?.message)
    return false
  }
}

export function mediaAssetPublicUrl(path: string): string {
  return supabase.storage.from('media-artifacts').getPublicUrl(path).data.publicUrl
}
