// AUTO-PORTED from apps/hq/public/audio/narrative-studio.html — the story-lock rehearsal deck.
// 46 scenes, 7 acts. This is the SINGLE source of scenes for the Cinema Program (WS1/WS2/WS3).
// Do not hand-edit ids/order/files — keep byte-identical to the Scene Manifest. See docs/jarvis-os/.
import type { Act, Voice, ProductId } from './contract'

export type ScenarioBeat = 'intro'|'overview'|'demo'|'summary'|'close'

export type Scene = {
  id: string; act: Act; file: string; voice: Voice
  title: string; idea: string
  guided: 'hold'|'product-tour'|'vault-tour'|'auto'
  product?: ProductId; beat?: ScenarioBeat | null
}

export const SCENES: Scene[] = [
  {id:"1.1",act:1,file:"01-01-JM-system-awakening.mp3",voice:"JM",title:"System awakening",idea:"Reactor ignites. The founder cockpit comes online.",guided:"hold"},
  {id:"1.2",act:1,file:"01-02-JM-founder-recognition.mp3",voice:"JM",title:"Founder recognition",idea:"Jarvis greets the founder — and returns control.",guided:"hold"},
  {id:"1.3",act:1,file:"01-03-JM-reactor-anatomy.mp3",voice:"JM",title:"Reactor anatomy",idea:"One cockpit. Left signals. Central reactor. Right outcomes.",guided:"hold"},
  {id:"2.1",act:2,file:"02-01-JM-left-instruments.mp3",voice:"JM",title:"Left instruments",idea:"World Reach. Weekly Engaged. Valuation Audit.",guided:"hold"},
  {id:"2.2",act:2,file:"02-02-JM-right-instruments.mp3",voice:"JM",title:"Right instruments",idea:"Five Products. Access & Attention. Visit Rhythm.",guided:"hold"},
  {id:"2.3",act:2,file:"02-03-JM-instrument-truth-policy.mp3",voice:"JM",title:"Truth policy",idea:"Every signal declares what is live, partial, simulated, or unwired.",guided:"hold"},
  {id:"3.1",act:3,file:"03-01-JM-argantalab-intro.mp3",voice:"JM",title:"ArgantaLab",idea:"The child learning engine of the Arganta ecosystem.",guided:"hold",product:"arganta",beat:"intro"},
  {id:"3.2",act:3,file:"03-02-JM-argantalab-overview.mp3",voice:"JM",title:"Learning by entering",idea:"Explore ideas. Solve challenges. Build understanding.",guided:"product-tour",product:"arganta",beat:"overview"},
  {id:"3.3",act:3,file:"03-03-JM-argantalab-demo-cue.mp3",voice:"JM",title:"Product demonstration",idea:"Desktop first. Mobile second. The product speaks for itself.",guided:"product-tour",product:"arganta",beat:"demo"},
  {id:"3.4",act:3,file:"03-04-JM-argantalab-summary.mp3",voice:"JM",title:"The purpose",idea:"Not more screen time — better curiosity and deeper participation.",guided:"hold",product:"arganta",beat:"summary"},
  {id:"3.5",act:3,file:"03-05-JM-argantalab-strategic-close.mp3",voice:"JM",title:"Strategic role",idea:"Education becomes active, creative, and personal.",guided:"auto",product:"arganta",beat:"close"},
  {id:"3.6",act:3,file:"03-06-JM-kinetikcircle-intro.mp3",voice:"JM",title:"KinetikCircle",idea:"The coordination layer for family and community life.",guided:"hold",product:"kinetik",beat:"intro"},
  {id:"3.7",act:3,file:"03-07-JM-kinetikcircle-overview.mp3",voice:"JM",title:"A shared rhythm",idea:"Plans, people, moments, and useful apps — connected.",guided:"product-tour",product:"kinetik",beat:"overview"},
  {id:"3.8",act:3,file:"03-08-JM-kinetikcircle-demo-cue.mp3",voice:"JM",title:"Product demonstration",idea:"Desktop first. Mobile second. Coordination without friction.",guided:"product-tour",product:"kinetik",beat:"demo"},
  {id:"3.9",act:3,file:"03-09-JM-kinetikcircle-summary.mp3",voice:"JM",title:"The value",idea:"Less friction. Clearer coordination. More room for what matters.",guided:"hold",product:"kinetik",beat:"summary"},
  {id:"3.10",act:3,file:"03-10-JM-kinetikcircle-strategic-close.mp3",voice:"JM",title:"Strategic role",idea:"Arganta’s social, participation, and distribution layer.",guided:"auto",product:"kinetik",beat:"close"},
  {id:"3.11",act:3,file:"03-11-KF-lashirabloom-intro.mp3",voice:"KF",title:"LashiraBloom",idea:"A shared world of farming, friendship, and play.",guided:"hold",product:"lashira",beat:"intro"},
  {id:"3.12",act:3,file:"03-12-KF-lashirabloom-overview.mp3",voice:"KF",title:"A world that grows",idea:"Farm by hand. Explore together. Care for a living place.",guided:"product-tour",product:"lashira",beat:"overview"},
  {id:"3.13",act:3,file:"03-13-KF-lashirabloom-demo-cue.mp3",voice:"KF",title:"Product demonstration",idea:"Desktop first. Mobile second. Enter the shared world.",guided:"product-tour",product:"lashira",beat:"demo"},
  {id:"3.14",act:3,file:"03-14-KF-lashirabloom-summary.mp3",voice:"KF",title:"A family story",idea:"A field becomes a home, a festival, an adventure, a memory.",guided:"hold",product:"lashira",beat:"summary"},
  {id:"3.15",act:3,file:"03-15-KF-lashirabloom-strategic-close.mp3",voice:"KF",title:"Strategic role",idea:"The living world where learning, coordination, creativity, and play meet.",guided:"auto",product:"lashira",beat:"close"},
  {id:"3.16",act:3,file:"03-16-KF-landing-intro.mp3",voice:"KF",title:"Landing",idea:"Arganta’s public front door.",guided:"hold",product:"landing",beat:"intro"},
  {id:"3.17",act:3,file:"03-17-KF-landing-public-story.mp3",voice:"KF",title:"The public story",idea:"Explain what is real today — and label what is planned.",guided:"product-tour",product:"landing",beat:"overview"},
  {id:"3.18",act:3,file:"03-18-KF-landing-demo-cue.mp3",voice:"KF",title:"Product demonstration",idea:"Desktop first. Mobile second. Discovery becomes a clear next step.",guided:"product-tour",product:"landing",beat:"demo"},
  {id:"3.19",act:3,file:"03-19-KF-landing-partnership-pathway.mp3",voice:"KF",title:"Partnership pathway",idea:"Discover. Build. Publish. Test. Launch. Learn. Iterate.",guided:"hold",product:"landing",beat:"summary"},
  {id:"3.20",act:3,file:"03-20-KF-landing-strategic-close.mp3",voice:"KF",title:"Strategic role",idea:"Public story, product discovery, and the future partnership gateway.",guided:"auto",product:"landing",beat:"close"},
  {id:"3.21",act:3,file:"03-21-JM-arganta-head-quarters-intro.mp3",voice:"JM",title:"Arganta Head Quarters",idea:"The founder operating system behind the ecosystem.",guided:"hold",product:"hq",beat:"intro"},
  {id:"3.22",act:3,file:"03-22-JM-arganta-head-quarters-anatomy.mp3",voice:"JM",title:"The living company",idea:"Memory. Sensors. Command. Architecture. Agents. Jarvis.",guided:"product-tour",product:"hq",beat:"overview"},
  {id:"3.23",act:3,file:"03-23-JM-arganta-head-quarters-demo-cue.mp3",voice:"JM",title:"Product demonstration",idea:"Desktop first. Mobile second. Inspect the operating core.",guided:"product-tour",product:"hq",beat:"demo"},
  {id:"3.24",act:3,file:"03-24-JM-arganta-head-quarters-governance.mp3",voice:"JM",title:"Founder governance",idea:"Not an autonomous black box. Approval-gated by design.",guided:"hold",product:"hq",beat:"summary"},
  {id:"3.25",act:3,file:"03-25-JM-arganta-head-quarters-strategic-close.mp3",voice:"JM",title:"Strategic role",idea:"Evidence, architecture, agents, products, and founder intent — connected.",guided:"auto",product:"hq",beat:"close"},
  {id:"4.1",act:4,file:"04-01-JM-think-know-do-unfold.mp3",voice:"JM",title:"The unfold",idea:"THINK. KNOW. DO.",guided:"hold"},
  {id:"4.2",act:4,file:"04-02-JM-think-explanation.mp3",voice:"JM",title:"THINK",idea:"Founder intent becomes a reasoned, routed request.",guided:"hold"},
  {id:"4.3",act:4,file:"04-03-JM-know-explanation.mp3",voice:"JM",title:"KNOW",idea:"Vault, telemetry, metrics, decisions, and provenance.",guided:"hold"},
  {id:"4.4",act:4,file:"04-04-JM-do-explanation.mp3",voice:"JM",title:"DO",idea:"Approved decisions become controlled execution.",guided:"hold"},
  {id:"5.1",act:5,file:"05-01-JM-founder-command-path.mp3",voice:"JM",title:"Founder → Command",idea:"Intent enters the system.",guided:"hold"},
  {id:"5.2",act:5,file:"05-02-JM-vault-data-path.mp3",voice:"JM",title:"Vault → Data",idea:"Memory meets current evidence and telemetry.",guided:"hold"},
  {id:"5.3",act:5,file:"05-03-JM-architecture-agents-products.mp3",voice:"JM",title:"Architecture → Agents → Products",idea:"Execution reaches the product worlds — and signals return.",guided:"hold"},
  {id:"5.4",act:5,file:"05-04-JM-graph-provenance.mp3",voice:"JM",title:"Provenance",idea:"Live. Partial. Simulated. Placeholder. Every state is visible.",guided:"hold"},
  {id:"6.1",act:6,file:"06-01-JM-activation-question.mp3",voice:"JM",title:"The question",idea:"Why is activation weak?",guided:"hold"},
  {id:"6.2",act:6,file:"06-02-JM-activation-think.mp3",voice:"JM",title:"THINK locates",idea:"Activation is isolated inside the product journey.",guided:"hold"},
  {id:"6.3",act:6,file:"06-03-JM-activation-know.mp3",voice:"JM",title:"KNOW reveals",idea:"Unwired exits surface from the evidence.",guided:"hold"},
  {id:"6.4",act:6,file:"06-04-JM-measure-before-redesign.mp3",voice:"JM",title:"Measure first",idea:"Instrument the journey before redesigning it.",guided:"hold"},
  {id:"6.5",act:6,file:"06-05-JM-instrumentation-package.mp3",voice:"JM",title:"DO builds",idea:"The package is drafted. Deployment stops at founder approval.",guided:"hold"},
  {id:"7.1",act:7,file:"07-01-JM-architecture-recombination.mp3",voice:"JM",title:"Recombination",idea:"THINK, KNOW, and DO fold back into one reactor.",guided:"hold"},
  {id:"7.2",act:7,file:"07-02-JM-closing.mp3",voice:"JM",title:"Return",idea:"The company is visible. The evidence is traceable. The next action is yours.",guided:"hold"},
]

export const NARRATION: Record<string,string> = {
  "1.1": "Arganta Head Quarters is coming online. The Vault is connected. The architecture is ready. Five product worlds are within reach.",
  "1.2": "Welcome back, Aldyth. This is not a presentation. It is a live founder cockpit: a place to understand the company, inspect evidence, direct agents, and approve action.",
  "1.3": "At the center is the reactor. Around it, Arganta's products, signals, memory, architecture, and operating instruments move as one system.",
  "2.1": "World Reach shows where Arganta is being discovered. Weekly Engaged shows whether people return and participate. Valuation Audit separates ambition from evidence, so every claim can be defended.",
  "2.2": "Five Products shows the ecosystem as a portfolio. Access and Attention shows how people enter, and where focus is earned or lost. When Arganta Is Alive reveals the rhythms that make the company active.",
  "2.3": "These instruments do not manufacture certainty. They show what is live, partial, simulated, or still unwired.",
  "3.1": "Begin with ArgantaLab, the child learning engine of the ecosystem.",
  "3.2": "In ArgantaLab, learning is something you enter. You explore ideas, solve challenges, build things, and gradually turn curiosity into understanding.",
  "3.3": "The overview is complete. The desktop experience will play first, followed by the mobile experience.",
  "3.4": "The goal is not simply more screen time. It is better curiosity, deeper participation, and the confidence to keep learning.",
  "3.5": "ArgantaLab gives Arganta its learning engine: a product world where education becomes active, creative, and personal.",
  "3.6": "Next is KinetikCircle, the coordination layer for family and community life.",
  "3.7": "KinetikCircle brings plans, people, and everyday life into one shared rhythm. Calendars, moments, useful apps, and trusted circles stay connected without making life feel complicated.",
  "3.8": "The overview is complete. The desktop experience will play first, followed by the mobile experience.",
  "3.9": "The value is not another busy dashboard. It is less friction, clearer coordination, and more room for the people and moments that matter.",
  "3.10": "KinetikCircle gives Arganta its social and distribution layer: where families gather, products are discovered, and communities participate.",
  "3.11": "Now enter LashiraBloom, the shared world of farming, friendship, and play.",
  "3.12": "LashiraBloom is a world that grows with the people inside it. You farm by hand, explore together, care for a living place, and create memories across one connected family world.",
  "3.13": "The overview is complete. The desktop experience will play first, followed by the mobile experience.",
  "3.14": "What begins as a small field can become a shared home, a festival, an adventure, and a story that belongs to the family building it together.",
  "3.15": "LashiraBloom gives Arganta its living world: the place where learning, coordination, creativity, and play can eventually meet.",
  "3.16": "Landing is Arganta's public front door. It explains the ecosystem, helps visitors discover the five products, and turns interest into a clear next step.",
  "3.17": "Visitors should quickly understand what Arganta is, who each product serves, what is available today, and what is still planned. The story must remain ambitious without becoming misleading.",
  "3.18": "The overview is complete. The desktop experience will play first, followed by the mobile experience.",
  "3.19": "Landing also carries the partnership pathway. Selected solo founders can discover the program, submit an idea, build or polish a product, publish through KinetikCircle Apps, test with the community, run live launch activities, and iterate from real signals. Capabilities that are not yet live must be labelled planned.",
  "3.20": "Landing gives Arganta its public story, product-discovery surface, and future partnership gateway.",
  "3.21": "Finally, Arganta Head Quarters: the founder operating system and agentic command center behind the ecosystem.",
  "3.22": "Here, the Vault holds memory. Data and portfolio surfaces act as sensors. Command provides reasoning and routing. Architecture gives structure. Builder agents provide controlled execution. Jarvis is the face that connects them.",
  "3.23": "The overview is complete. The desktop experience will play first, followed by the mobile experience.",
  "3.24": "Arganta Head Quarters is not an autonomous black box. It is an approval-gated system that helps the founder understand, decide, build, and remain accountable.",
  "3.25": "This is the operating core of Arganta: one place where evidence, architecture, agents, products, and founder intent stay connected.",
  "4.1": "Now the reactor unfolds into three operating forces: THINK. KNOW. And DO.",
  "4.2": "THINK interprets founder intent. It frames the question, selects the right reasoning path, and routes work to the appropriate system or agent.",
  "4.3": "KNOW grounds the system in the Vault, telemetry, metrics, decisions, and provenance. It separates evidence from assumption, and live signals from simulation.",
  "4.4": "DO turns an approved decision into controlled execution: a task, workflow, artifact, code change, or deployment. It acts through tools, and stops where founder approval is required.",
  "5.1": "The architecture begins with the Founder. Jarvis receives intent, and Command translates that intent into a structured request.",
  "5.2": "Command consults the Vault and connected data. The Vault provides memory, while data sources provide current evidence, metrics, and operational signals.",
  "5.3": "Architecture defines how the system should work. Agents use skills and tools to produce artifacts. Those artifacts improve the five products, and the products return new signals to the system.",
  "5.4": "Every grounded node should open a real note, source, metric, repository object, or system record. Live evidence appears solid. Partial evidence remains translucent. Simulation is visibly marked. The two-dimensional Vault remains the place for real reading and editing.",
  "6.1": "Now, a deterministic proof. The question is simple: Why is activation weak?",
  "6.2": "THINK locates activation inside the product journey. It identifies the steps between first entry, meaningful action, and successful return.",
  "6.3": "KNOW checks the evidence. It reveals that key exit points are not yet instrumented, so the system cannot honestly claim to know why users leave.",
  "6.4": "THINK chooses measurement before redesign. The correct next move is to wire the missing signals, define the activation event, and establish a trustworthy baseline.",
  "6.5": "DO prepares the instrumentation package: Event definitions. Data contracts. Implementation tasks. Validation checks. And an approval request. It does not deploy. It stops for the founder.",
  "7.1": "The architecture now recombines. THINK returns to the core. KNOW settles into the Vault. DO returns to readiness. The five product worlds resume their orbit.",
  "7.2": "Arganta Head Quarters is ready. The company is visible. The evidence is traceable. The next action remains yours.",
}

export const ACTS: Record<Act,{roman:string;title:string;accent:string}> = {
  1: { roman: "I", title: "IGNITION & COCKPIT", accent: "#45e8ff" },
  2: { roman: "II", title: "SIX INSTRUMENTS", accent: "#55d6ff" },
  3: { roman: "III", title: "FIVE PRODUCTS", accent: "#4be5bd" },
  4: { roman: "IV", title: "THINK · KNOW · DO", accent: "#9d77ff" },
  5: { roman: "V", title: "ARCHITECTURE GRAPH", accent: "#8f7bff" },
  6: { roman: "VI", title: "DETERMINISTIC PROOF", accent: "#f6b94f" },
  7: { roman: "VII", title: "RECOMBINATION & RETURN", accent: "#45e8ff" },
}
