import type { Question, QuestionScope } from './types';

/**
 * The Volve Mission assessment bank.
 *
 * Blueprint (published in the Assessments tab):
 *   Daily checks  — 10 questions per day for days 1-4, 80% to pass.
 *   Final exam    — 50 scenario-led questions: evidence 7, exploration 9,
 *                   field development 12, well delivery 9, reservoir
 *                   management 9, integrated decisions 4.
 */

/* Integrated decisions — cross-lifecycle consequence, framing and triage. */
const INTEGRATED: Question[] = [
  {
    id: 'q-f-int-01', scope: 'final', competency: 'integrated',
    stem: 'A revised top-reservoir surface moves the structural crest 12 m deeper. Which consequence chain is most likely to change the development decision?',
    options: [
      'Only the in-place volume changes; the well plan and schedule are unaffected until the next model release',
      'Gross rock volume changes, propagating into in-place volume, target depth and potentially the executable rig slot',
      'Nothing should propagate yet, because a surface revision is an interpretation rather than a measurement',
      'The production forecast changes but the volumetrics do not, because history is already measured',
    ],
    answer: 1,
    explanation: 'Gross rock volume is geometry-driven, so a crest change flows through in-place volume into targets and schedule. Treating it as a volumetrics-only edit hides the consequence that actually reaches the decision.',
  },
  {
    id: 'q-f-int-02', scope: 'final', competency: 'integrated',
    stem: 'A team opens its field review with forty slides of workflow detail and one closing recommendation. What is the most material weakness?',
    options: [
      'The review runs longer than the time allocated',
      'The recommendation appears at the end rather than the start',
      'The team presented insufficient uncertainty analysis',
      'The decision, its options and the criteria that separate them were never framed',
    ],
    answer: 3,
    explanation: 'Without a stated decision, options and criteria, the audience cannot judge whether the analysis is relevant. Ordering and length are presentation faults; an unframed decision is a decision-quality failure.',
  },
  {
    id: 'q-f-int-03', scope: 'final', competency: 'integrated',
    stem: 'Which uncertainty most deserves a place in a ten-minute integrated field review?',
    options: [
      'The one whose plausible outcomes would lead to different decisions',
      'The one with the widest numerical range',
      'The one that is cheapest to reduce with further study',
      'The one the technical team understands least well',
    ],
    answer: 0,
    explanation: 'Decision-relevance is the filter: an uncertainty matters when its range spans a change of course. A wide range that leaves the same choice in place consumes review time without informing it.',
  },
  {
    id: 'q-f-int-04', scope: 'final', competency: 'integrated',
    stem: 'A well gate paper cites a reservoir target depth taken from a development case that has since been superseded. What is the appropriate gate response?',
    options: [
      'Approve, since the difference between case revisions is likely to be small',
      'Reject the well, because its basis of design is invalid',
      'Condition approval on re-stating the target against the current case, with a named owner and a verification date',
      'Hold the well until the static model has been rebuilt from scratch',
    ],
    answer: 2,
    explanation: 'A stale but correctable basis is exactly what a condition is for, provided it carries a verifiable criterion and an owner. Rejecting or holding discards a sound well for a traceable bookkeeping fault.',
  },
];

/* Exploration — lifecycle maturity, petroleum system, chance vs range, the gate. */
const EXPLORATION: Question[] = [
  { id: 'q-d1-01', scope: 'day1', competency: 'exploration', stem: 'A team relabels three leads as prospects after a workshop in which no new data were reviewed, arguing the portfolio needs more drillable inventory. What is the most defensible response?', options: ['Accept the relabel, since prospect status is an internal naming convention with no evidence threshold.', 'Accept it if the leads sit in a play that already contains a discovery, because play success transfers down.', 'Reject the relabel, because moving from lead to prospect requires new evidence supporting a drillable target.', 'Reject the relabel and demote all three to play level until a new seismic survey has been acquired.'], answer: 2, explanation: 'Each lifecycle transition must be earned with stronger evidence and a clearer decision, not with reclassification. A discovery elsewhere in the play does not define trap, closure or target at these specific leads.' },
  { id: 'q-d1-02', scope: 'day1', competency: 'exploration', stem: 'A prospect summary states "source present, reservoir present, seal present, trap defined" and concludes that the petroleum system is proven. Where is the reasoning weakest?', options: ['Presence of each element says nothing about whether it worked, so effectiveness and timing remain untested.', 'The summary omits a reservoir quality cut-off, which is the only element genuinely missing here.', 'Presence is sufficient to prove the system, so the real gap is that no volume range is quoted.', 'The elements are listed out of sequence, so the charge story cannot be audited by a reviewer.'], answer: 0, explanation: 'The petroleum system is one dependent system, and presence is not effectiveness; timing and dependency still have to be argued. Adding a volume range would size a case that has not yet been shown to work.' },
  { id: 'q-d1-03', scope: 'day1', competency: 'exploration', stem: 'A prospect carries a 25 percent geological chance of success and a P50 volume of 40 MMbbl. A manager summarises this as "so we are 50 percent likely to find 40 MMbbl". What is wrong?', options: ['Nothing, since a P50 already carries the chance of success inside its definition.', 'Only the phrasing, because on a risked basis half of all outcomes still fall below 40 MMbbl.', 'The two numbers should be multiplied and reported as a 12.5 percent probability of 40 MMbbl.', 'The P50 is conditional on the accumulation working, while the 25 percent governs whether there is any volume to size.'], answer: 3, explanation: 'Chance of success and the volume distribution are different axes: the range describes size if the case exists. Multiplying the two percentages is meaningless because 50 percent is a position on the volume curve, not a probability of existence.' },
  { id: 'q-d1-04', scope: 'day1', competency: 'exploration', stem: 'A resource table for an undrilled prospect reads P90 12 MMbbl, P50 35 MMbbl, P10 140 MMbbl. A reviewer asks what the P90 actually means.', options: ['There is a 90 percent chance the prospect contains no more than 12 MMbbl.', 'If the accumulation exists, there is a 90 percent chance the volume exceeds 12 MMbbl.', 'There is a 90 percent chance the prospect is commercial at 12 MMbbl or above.', 'The figure of 12 MMbbl is the smallest volume this prospect could physically hold.'], answer: 1, explanation: 'P90 is the low estimate with a 90 percent chance of being exceeded, conditional on the case existing. Reading it as an upper bound inverts the convention, and it is not an absolute physical minimum.' },
  { id: 'q-d1-05', scope: 'day1', competency: 'exploration', stem: 'Charge, reservoir and trap are each assessed at 0.8 chance and seal at 0.2, giving a combined chance near 10 percent. The team proposes more seismic to sharpen the trap outline. What is the best critique?', options: ['Work should target seal, the element that dominates the failure, rather than a trap already assessed as likely.', 'The four factors should be averaged rather than multiplied, which puts the real chance nearer 65 percent.', 'Trap work is right because trap definition is the first-order control in any mature basin setting.', 'No further work is justified below 15 percent chance, so the prospect should simply be dropped.'], answer: 0, explanation: 'In a dependent system the weakest element dominates the outcome, so effort belongs where it can move the chance. Averaging the factors is not how a dependent chain behaves, and a low chance alone is not grounds to stop before the dominant risk is examined.' },
  { id: 'q-d1-06', scope: 'day1', competency: 'exploration', stem: 'At the Progress, Study or Stop gate a team recommends Progress with a one-line rationale that the prospect "looks strong and is analogous to nearby producers". What is the primary deficiency?', options: ['Analogues are inadmissible at a gate, since only data from the prospect itself may be cited.', 'The default call should be Study whenever an analogue is the leading argument on the page.', 'The rationale needs a commercial threshold and a partner view before anyone can assess it.', 'It carries no traceable evidence references, no stated material gap and no next best action.'], answer: 3, explanation: 'The gate requires three evidence references, one material gap and a next best action, and none of those are present. Analogues are legitimate evidence, so banning them misidentifies the problem.' },
  { id: 'q-d1-07', scope: 'day1', competency: 'exploration', stem: 'While preparing the gate pack an analyst finds no reliable seal capacity data for the target interval and leaves that section blank so the case does not look weaker.', options: ['Correct, because a blank section signals absent data more clearly than any commentary would.', 'Incorrect, because the missing seal capacity is itself a finding and belongs in the material gap.', 'Incorrect, because a regional default value should be inserted and then flagged in the appendix.', 'Acceptable, provided the seal chance factor is lowered to compensate for the missing data.'], answer: 1, explanation: 'A gap is a finding and must be surfaced, since it drives the next best action. Quietly lowering a chance factor buries the gap inside a number instead of reporting it.' },
  { id: 'q-d1-08', scope: 'day1', competency: 'exploration', stem: 'A discovery well flowed oil, and the asset team now refers to the structure as a field in every document it issues. What does this skip?', options: ['Nothing, because a successful flow test is what defines a field.', 'Only a naming convention, which the regulator assigns after first production anyway.', 'A discovery becomes a field once development is justified, and the appraisal and commercial case are not yet made.', 'A second penetration, which is required before any label may change regardless of commercial work.'], answer: 2, explanation: 'Maturity is not certainty, and the discovery to field step requires a justified development, not just a flow. A second well may help but is not what the label turns on.' },
  { id: 'q-d1-09', scope: 'day1', competency: 'exploration', stem: 'A team assigns a 60 percent charge chance to a new lead on the grounds that the basin has produced oil for decades. Which objection is strongest?', options: ['Basin production is irrelevant to charge, which can only be argued from local source rock geochemistry.', 'Charge chance should default to 50 percent for any lead until a well has actually been drilled.', 'Charge chance cannot exceed the play chance, which makes 60 percent arithmetically impossible.', 'Basin charge does not prove migration reached this trap, so lead-specific access must be argued.'], answer: 3, explanation: 'Proven charge in the basin supports the play, but the lead still needs a migration pathway into its own trap. Basin evidence is relevant, so dismissing it outright is too strong.' },
  { id: 'q-d1-10', scope: 'day1', competency: 'exploration', stem: 'A trap is mapped as a robust four-way closure, but the source kitchen reached peak generation before the structure formed. How should this be handled at the gate?', options: ['Timing is a distinct element of the system, so the mismatch should carry the failure case explicitly.', 'Trap quality overrides timing, since a good closure will capture any later remigration.', 'The mismatch should be folded into the trap chance so a single number reports it.', 'Timing only constrains gas prospects, so the oil case can proceed unchanged.'], answer: 0, explanation: 'Timing is one of the five dependent elements and a structure that post-dates charge can fail on that basis alone. Folding it into trap chance hides the dominant risk behind a factor that means something else.' },
  { id: 'q-f-exp-01', scope: 'final', competency: 'exploration', stem: 'A portfolio review sums the P10 volumes of eight independent prospects and presents the total as the exploration upside for the licence round. Which criticism is correct?', options: ['P10 values may be summed only where the prospects share a common trap style.', 'Adding P10 values overstates the aggregate high case, because all eight are unlikely to reach their high case together.', 'Summing P10 values is valid, but the total should then be divided by the number of prospects.', 'The error is the use of P10 rather than P90, which is the correct quantile to aggregate.'], answer: 1, explanation: 'Quantiles do not add across independent cases, so the summed high case is far less likely than 10 percent. Substituting P90 repeats the same error at the other end of the range.' },
  { id: 'q-f-exp-02', scope: 'final', competency: 'exploration', stem: 'A prospect has a 30 percent chance of success and a mean success-case volume of 50 MMbbl. A screening spreadsheet shows 50 MMbbl in the column headed "risked volume".', options: ['Correct, because a mean is already a risked measure by construction.', 'Correct, provided the chance of success is above 25 percent, which it is here.', 'Incorrect, because the risked volume should be 50 divided by 0.30, or about 167 MMbbl.', 'Incorrect, because the risked mean is 15 MMbbl, the success-case mean multiplied by the chance.'], answer: 3, explanation: 'Chance of success multiplies the success-case volume to give a risked mean, so 0.30 times 50 is 15 MMbbl. A mean is a property of the volume distribution and carries no chance information on its own.' },
  { id: 'q-f-exp-03', scope: 'final', competency: 'exploration', stem: 'Between two reviews a prospect range tightens from P90 8 / P50 30 / P10 120 to P90 27 / P50 31 / P10 36, with no new well and no new seismic acquired.', options: ['The narrowing reflects changed assumptions rather than new information, so the input ranges must be shown.', 'The narrowing is a legitimate result of running the Monte Carlo model to better convergence.', 'The tightening is expected as a prospect matures and requires no further explanation.', 'The P50 barely moved, so the revision is immaterial and can be accepted as presented.'], answer: 0, explanation: 'Uncertainty narrows through information, and with no new data the change can only come from inputs that need to be exposed. More simulation iterations refine the estimate of the distribution, they do not shrink it.' },
  { id: 'q-f-exp-04', scope: 'final', competency: 'exploration', stem: 'A volumetric model samples net-to-gross and porosity from independent distributions, although core data show the two are strongly positively correlated in this reservoir. What is the likely effect on the result?', options: ['The mean is badly biased, while the P90 and P10 remain essentially unaffected.', 'There is no effect, since correlation only matters when recovery factor is involved.', 'The spread is too narrow, so both the low case and the high case are understated.', 'The spread is too wide, so the reported P10 should be reduced by hand.'], answer: 2, explanation: 'Ignoring positive correlation lets good and poor values offset each other, which artificially compresses the range and manufactures precision. The distortion is in the spread, not principally in the central value.' },
  { id: 'q-f-exp-05', scope: 'final', competency: 'exploration', stem: 'An appraisal well is proposed for a discovery whose dominant uncertainty is a wide volume range, but where every outcome from P90 to P10 leads to the same development concept. What is the strongest argument?', options: ['Drill, because narrowing the volume range always adds value to the project.', 'Reconsider, because information that cannot change the decision does not justify its cost.', 'Drill, because a discovery can never be sanctioned on a single penetration.', 'Reconsider, and raise the chance of success instead through further seismic reprocessing.'], answer: 1, explanation: 'Appraisal earns its cost only where the result can change a decision, and here the concept is invariant across the range. Chance of success is no longer the live question once the accumulation has been found.' },
  { id: 'q-f-exp-06', scope: 'final', competency: 'exploration', stem: 'Three prospects sit in the same untested play and each is quoted at a 35 percent chance of success. A partner treats the drilling programme as three independent chances at a discovery. Which correction matters most?', options: ['They share play-level risk, so a single play failure could take all three at once.', 'Each chance should be cut to about 12 percent to reflect that three wells are planned.', 'Independence is fine, because chance factors are always assessed prospect by prospect.', 'The shared play means the chances add, giving roughly a 100 percent chance of one success.'], answer: 0, explanation: 'Common play risk is shared, so the outcomes are correlated and the programme is far more likely to be all or nothing than independence implies. Probabilities of alternative outcomes are never simply added.' },
  { id: 'q-f-exp-07', scope: 'final', competency: 'exploration', stem: 'A well on a North Sea trend encounters good reservoir and a valid trap but no movable hydrocarbons, with only residual shows. What is the most useful conclusion for the remaining prospects on the trend?', options: ['Reservoir presence is confirmed, so the chance of success across the trend should be raised.', 'The result is specific to this well and should not alter any other prospect chance factor.', 'Trap chance should be lowered across the trend, because the trap has clearly failed.', 'Charge or retention is now the leading risk on the trend and should carry the downgrade.'], answer: 3, explanation: 'Reservoir and trap were both demonstrated, so the failure sits with charge or retention, and that is where the trend chance must fall. Raising the overall chance on the reservoir result ignores the element that actually failed.' },
  { id: 'q-f-exp-08', scope: 'final', competency: 'exploration', stem: 'A prospect summary reports "recoverable volume P50 45 MMbbl" using a recovery factor carried across from a nearby producing field with a different drive mechanism. How should this number be treated?', options: ['As measured data, since the analogue field recovery factor is a published figure.', 'As standard practice, because analogue recovery factors are the industry default at prospect stage.', 'As a derived number whose analogue assumption is stated and whose sensitivity is shown.', 'As unusable, because recoverable volumes cannot be quoted before a well is drilled.'], answer: 2, explanation: 'The volume is derived through a transformation whose key assumption is a borrowed drive mechanism, so the assumption and its sensitivity must travel with it. Common use of analogues does not exempt the assumption from being stated.' },
  { id: 'q-f-exp-09', scope: 'final', competency: 'exploration', stem: 'At a final gate a prospect is economic at P50, but the entire case depends on a seal type that no well on the trend has ever tested. The team recommends Progress to drill.', options: ['Progress is right, because only drilling can ever test a seal.', 'The untested seal is the material gap and should drive both the recommendation and the stated next action.', 'Stop is the only defensible call whenever an element is untested anywhere on the trend.', 'Progress is right provided the seal chance factor is set at 0.5 to reflect the absence of data.'], answer: 1, explanation: 'The gate turns on naming the material gap and choosing the next best action against it, which may be cheaper de-risking before a well. Drilling does eventually test the seal, but that does not excuse a recommendation that leaves the dominant gap unstated.' },
];

/* Evidence and provenance — truth class, lineage, conflict and gap reporting. */
const EVIDENCE: Question[] = [
  { id: 'q-f-evi-01', scope: 'final', competency: 'evidence', stem: 'A summary slide lists "water saturation 28 percent" next to "gamma ray 45 API" under a single heading reading "Well measurements". What is the problem?', options: ['Neither value is a measurement, since both are outputs of the petrophysical model.', 'There is no problem, because both values come from the same logging run in the same well.', 'The gamma ray is the derived value, because API units are a computed normalisation.', 'Saturation is derived from a resistivity log through a saturation model, and its assumptions travel with it.'], answer: 3, explanation: 'A log reading is measured, while saturation is a derived quantity produced by a model with parameters that must be declared. Treating the gamma ray as derived misplaces the transformation, which happens downstream of the tool reading.' },
  { id: 'q-f-evi-02', scope: 'final', competency: 'evidence', stem: 'A field review states that the oil water contact is at 3100 m. Traced back, the number rests on a seismic flat spot supported by one pressure gradient intersection.', options: ['The contact should be reported as measured, because pressure data are physical measurements.', 'The contact is an interpretation from two evidence lines and should be labelled, with alternatives preserved.', 'The flat spot makes the contact directly observed, so no qualifier is needed on the slide.', 'The contact is a forecast, because it will only be confirmed by future production behaviour.'], answer: 1, explanation: 'A contact inferred from a seismic response and a gradient intersection is interpreted, and the alternative depths must survive into the report. The underlying pressure points are measured, but the contact drawn from them is not.' },
  { id: 'q-f-evi-03', scope: 'final', competency: 'evidence', stem: 'A rate of 4,000 barrels per day appears as a modelled forecast in a reservoir study, then three months later as "current rate 4,000 bopd" in a board pack, with no production data acquired in between.', options: ['The number is unchanged, so the restatement is accurate as written.', 'The restatement is acceptable, because a forecast becomes an actual once its period has passed.', 'The number silently changed truth class from forecast to reported actual, and that is the reportable error.', 'The only error is that the board pack omitted the confidence interval around the forecast.'], answer: 2, explanation: 'The digits are identical but the claim is not, and a forecast presented as an actual is a provenance failure. Adding a confidence interval would still leave the number mislabelled as something that was observed.' },
  { id: 'q-f-evi-04', scope: 'final', competency: 'evidence', stem: 'Two vendor reports give net pay for the same interval as 24 m and 31 m. With a deadline approaching, an analyst reports the average of 27.5 m as the agreed value.', options: ['Averaging conceals an unresolved conflict, and the disagreement and its cause are themselves the finding.', 'Averaging is sound, provided both vendors worked from the same log suite in the same well.', 'The higher value should be taken, since thinner pay reflects stricter cut-offs and is over-conservative.', 'The values differ by less than 30 percent, so the discrepancy sits within tolerance and needs no comment.'], answer: 0, explanation: 'An unresolved conflict is reportable in its own right, and the cut-off or method difference behind it is the useful information. Averaging produces a number that neither vendor supports and erases the reason they disagreed.' },
  { id: 'q-f-evi-05', scope: 'final', competency: 'evidence', stem: 'A porosity value in the corporate database has an empty source field. A junior team member asks whether it can be used in the volumetric model due this week.', options: ['Yes, because values held in the corporate database have already passed data governance.', 'Yes, if a second database returns a similar value, which corroborates the first.', 'No, and the value should be deleted so that nobody can reuse it later.', 'Not until its lineage is traced, because without provenance its truth class and uncertainty are unknown.'], answer: 3, explanation: 'Without lineage there is no way to know whether the figure is measured, derived or assumed, or what uncertainty it should carry. Agreement between two databases often just reflects a shared upstream copy rather than independent support.' },
  { id: 'q-f-evi-06', scope: 'final', competency: 'evidence', stem: 'A planning pack contains a high case production profile built by assuming an untested fault compartment is connected, and presents it beside the base forecast with no distinguishing label.', options: ['This is correct, because a high case is simply the P10 of the same forecast distribution.', 'The high case should be removed, because unproven connectivity cannot legitimately be modelled.', 'It is a scenario resting on a specific assumption and must be labelled as one, not read as a forecast.', 'The two are equivalent as long as both were produced in the same reservoir simulator.'], answer: 2, explanation: 'A conditional profile built on a named assumption is a scenario, and mixing it with a forecast silently changes what the reader is being told. Exploring unproven connectivity is legitimate, so the fix is labelling rather than deletion.' },
  { id: 'q-f-evi-07', scope: 'final', competency: 'evidence', stem: 'A cumulative production figure taken from a public regulatory database is cited in a study as "measured field production". What is the most accurate truth class for it?', options: ['Reported, because it is a third-party submission whose allocation method is not visible to the study.', 'Measured, because physical meters produced the volumes before they were ever submitted.', 'Derived, because a cumulative total is calculated by summing the monthly volumes.', 'Interpreted, because the study author chose which of several databases to cite.'], answer: 0, explanation: 'A regulatory submission is reported information, since the study cannot see the allocation and correction steps behind it. Metering sits at the start of that chain but the figure reaching the study is no longer a direct measurement.' },
];

/* Well delivery — basis of design, depth references, trajectory, offsets, sequence. */
const WELL_DELIVERY: Question[] = [
  { id: 'q-d3-01', scope: 'day3', competency: 'well-delivery', stem: 'A subsurface team submits a well proposal that jumps straight to a casing scheme and bit programme, citing "the reservoir target agreed last month". The drilling engineer refuses to start detailed design. What is the strongest technical justification for that refusal?', options: ['Casing design cannot begin until the rig contract is signed and the slot is confirmed', 'No statement of requirements or basis of design exists to connect reservoir intent to the engineering choices', 'Bit selection should always follow, not precede, the mud programme in the design sequence', 'The proposal has not yet been reviewed by the partner group, so any design work would be premature'], answer: 1, explanation: 'Design has to be traceable to a documented objective, target, data acquisition need and acceptance criteria; without that basis the engineering choices cannot be defended or audited. Contract and partner timing are commercial gates, not the reason the technical work is unanchored.' },
  { id: 'q-d3-02', scope: 'day3', competency: 'well-delivery', stem: 'A geologist quotes the reservoir top at 2,750 m TVDSS. The rig floor programme lists the same top at 2,780 m. Before raising an error report, what should the engineer establish first?', options: ['Whether the driller measured from the rotary table using a miscalibrated pipe tally', 'Whether the seismic depth conversion has been updated since the last velocity model', 'Whether the two numbers are stated on the same depth reference, since MD, TVD and TVDSS are not interchangeable', 'Whether the 30 m difference is inside the target uncertainty envelope and therefore acceptable'], answer: 2, explanation: 'TVDSS is referenced to mean sea level while a rig figure is commonly MD or TVD from a rig datum, so the two numbers may describe the same point with no error at all. Treating it as a tally or depth-conversion problem assumes a discrepancy that has not yet been shown to exist.' },
  { id: 'q-d3-03', scope: 'day3', competency: 'well-delivery', stem: 'A revised trajectory removes a shallow sidestep and instead builds angle rapidly through the intermediate section, raising planned dogleg severity from 1.8 to 4.5 degrees per 30 m. Which consequence should carry the most weight in the review?', options: ['Increased torque and drag, casing wear and difficulty running the completion through the build section', 'A shorter measured depth to target that reduces total drilling days and rotating hours', 'Reduced formation exposure in the reservoir section, lowering differential sticking risk', 'A lower separation factor against neighbouring wells because the well leaves the congested zone sooner'], answer: 0, explanation: 'High DLS is a deliverability issue: it drives torque and drag, casing wear and completion-running risk over the life of the well. The shorter measured depth is real but is a schedule benefit, not the risk the review must resolve.' },
  { id: 'q-d3-04', scope: 'day3', competency: 'well-delivery', stem: 'A new well is planned from a congested platform template where several existing wells run near-vertical for the first few hundred metres. Which screening measure should drive the anti-collision discussion at this stage?', options: ['Closest approach expressed as absolute centre-to-centre distance in metres', 'Maximum planned dogleg severity in the shallow build section', 'Separation factor, which normalises closest approach against the combined positional uncertainty of both wells', 'Slot spacing on the template deck, since it fixes the minimum achievable separation'], answer: 2, explanation: 'Separation factor is the standard screening measure because it compares the gap to the uncertainty in both wellbore positions, which is what determines whether the gap is real. Raw metres ignore survey uncertainty, and shallow wells are exactly where uncertainty ellipses are least forgiving relative to spacing.' },
  { id: 'q-d3-05', scope: 'day3', competency: 'well-delivery', stem: 'A team cites an offset well 900 m away that drilled without incident, and proposes reducing the contingency in the 12 1/4 in section. What most undermines that argument?', options: ['A single offset is never sufficient evidence; at least three analogues are required before contingency can be changed', 'The offset penetrated a different formation with a different mud system and hole geometry, so proximity does not establish similarity', 'The offset was drilled by a different contractor, so its performance data cannot be transferred', 'The offset is older than five years, which places it outside the current well engineering standard'], answer: 1, explanation: 'Offset relevance rests on comparable formation, hole section, mud system and geometry; spatial proximity alone explains nothing about the mechanism being carried across. A fixed count of analogues, contractor identity or record age are procedural filters, not the reason the comparison fails.' },
  { id: 'q-d3-06', scope: 'day3', competency: 'well-delivery', stem: 'A technically sound well plan is presented for a slot on a rig already under contract. Which finding would most directly make the well undeliverable on that rig, rather than merely more expensive?', options: ['The required mud weight window is narrow and demands close pore-pressure monitoring while drilling', 'The planned logging suite has a longer rig-up time than the offset wells used as reference', 'The trajectory places the reservoir section in a formation with a known history of hole instability', 'Hookload at the planned casing depth exceeds the rig derrick rating with no achievable string redesign'], answer: 3, explanation: 'Rig capability limits such as hookload, pump capacity, BOP rating and tubular handling are hard constraints that decide executability. A narrow mud window or unstable formation raises difficulty and cost but does not by itself put the well outside what the rig can physically do.' },
  { id: 'q-d3-07', scope: 'day3', competency: 'well-delivery', stem: 'A programme review shows the well design is complete and approved, yet the sequencing lead argues the slot should not be committed to next quarter. Which observation would best support that position?', options: ['Long-lead completion equipment and the required subsea tie-in survey are not scheduled to be available before the slot opens', 'The design was approved by a different technical authority than the one who reviewed the previous well', 'The planned well duration is longer than the average of the offset wells in the same field', 'The trajectory has been revised twice since the original concept was agreed'], answer: 0, explanation: 'A plan is not readiness: dependencies and long-lead items determine whether a slot can actually be executed on the date claimed. Approval routing, above-average duration and revision count describe the paperwork and the design, not the availability of what the well needs to start.' },
  { id: 'q-d3-08', scope: 'day3', competency: 'well-delivery', stem: 'At the delivery gate, a reviewer proposes: "Approve, conditional on the shallow gas risk being managed appropriately during the top-hole section." How should the gate chair respond?', options: ['Accept it, since a named hazard with a defined section is enough to record a condition', 'Convert it to a Hold, because any unresolved shallow gas concern must stop the well until the risk is closed out', 'Reject it as drafted, because a condition needs a verifiable criterion with a named owner and a date', 'Downgrade it to an observation, since operational execution risks are handled in the drilling programme, not at the gate'], answer: 2, explanation: '"Managed appropriately" cannot be verified, so it does not constrain anything; a real condition states what evidence must exist, who owns it and by when. Escalating to Hold is premature because a Hold is for missing evidence that blocks approval, not for a condition that is simply badly written.' },
  { id: 'q-d3-09', scope: 'day3', competency: 'well-delivery', stem: 'A well objective states that the well must "confirm reservoir quality in the eastern segment". Which addition would most improve it as a basis for approval?', options: ['A statement that a full triple-combo log suite and rotary sidewall cores will be run', 'A commitment that the well will be drilled with the highest available survey accuracy', 'A note that the eastern segment has been mapped from the reprocessed 3D seismic volume', 'The specific data to be acquired and the acceptance criteria that will determine whether the objective was met'], answer: 3, explanation: 'An objective becomes decision-grade only when the required data acquisition and the acceptance criteria are explicit, so success or failure is judged against a stated threshold. Listing a log suite specifies activity without saying what result would constitute confirmation.' },
  { id: 'q-d3-10', scope: 'day3', competency: 'well-delivery', stem: 'Following a trajectory change, an engineer overwrites the plan file with the new geometry and updates the well summary sheet. What is the main weakness in this way of handling the revision?', options: ['The rationale for the superseded design is lost, so later reviewers cannot see which constraint drove the change', 'The updated file will not automatically propagate to the anti-collision scan, which must be re-run', 'The well summary sheet is not the controlled document and should not have been updated first', 'The new geometry has not been re-checked against the rig capability envelope'], answer: 0, explanation: 'Revisions must preserve rationale, otherwise a future team can unknowingly reintroduce the very constraint that forced the change. Re-running the anti-collision scan and rechecking rig capability are necessary steps but they address the new design, not the loss of decision history.' },
  { id: 'q-f-wd-01', scope: 'final', competency: 'well-delivery', stem: 'A well plan places the target within a mapped uncertainty envelope of plus or minus 40 m vertically, while the planned landing point is specified to the metre. What does this combination most likely indicate?', options: ['The trajectory is over-engineered and the build rate should be relaxed to reduce dogleg severity', 'The plan presents precision the subsurface evidence does not support, so target uncertainty has not been carried into the design', 'The survey programme is inadequate and a higher-accuracy MWD tool is needed for the landing', 'The depth reference has been misapplied, since a landing point should only ever be quoted in MD'], answer: 1, explanation: 'Quoting a landing point far more precisely than the uncertainty envelope hides the real question, which is whether the well still meets its objective anywhere within that envelope. Upgrading the survey tool improves wellbore position knowledge but does nothing about uncertainty in where the target actually is.' },
  { id: 'q-f-wd-02', scope: 'final', competency: 'well-delivery', stem: 'A gate record shows: "Condition: reservoir team to review the pressure data." Six weeks later the well is on the rig schedule and nobody can say whether the condition was met. What was the root defect in the record?', options: ['The condition had no verification criterion, owner or date, so there was nothing to check closure against', 'The condition should have been a Hold, because pressure data is safety-critical', 'The condition was assigned to a team rather than to the drilling superintendent who runs the programme', 'The condition was recorded at the gate instead of in the risk register, where actions are tracked'], answer: 0, explanation: 'A condition that cannot be verified is not a real condition, which is exactly why its status became unknowable. Assigning it to an individual or moving it to another register would not have helped if there is still no criterion defining what "reviewed" means.' },
  { id: 'q-f-wd-03', scope: 'final', competency: 'well-delivery', stem: 'A completion engineer objects to a trajectory with a sustained 5 degrees per 30 m build immediately above the reservoir. Which concern is most specific to the completion?', options: ['Cuttings transport will deteriorate through the build, increasing the risk of pack-off while drilling', 'Formation exposure time in the build section will increase, raising the chance of differential sticking', 'Running rigid completion components and control lines through the high-curvature interval may exceed their bend limits or cause hang-up', 'Cement placement quality behind the production casing will be compromised by eccentric standoff'], answer: 2, explanation: 'The completion-specific issue with high DLS is passing stiff assemblies and control lines through a tight curvature without exceeding bend limits or getting stuck. Hole cleaning, sticking and cement standoff are genuine consequences of the same geometry but belong to the drilling and cementing phases.' },
  { id: 'q-f-wd-04', scope: 'final', competency: 'well-delivery', stem: 'A lessons-learned entry reads: "Do not use oil-based mud in this interval." The interval is being planned again on a new well. How should the entry be treated?', options: ['Applied as written, since lessons learned are recorded precisely so they are not re-litigated', 'Discarded, because a single-well lesson is anecdotal until it recurs on a second well', 'Escalated to a design standard so that the restriction applies field-wide', 'Held pending the context, because without the failure mechanism and conditions it cannot be judged transferable'], answer: 3, explanation: 'A lesson without its mechanism and operating context cannot be tested against the new well, so applying or discarding it are both guesses. Treating an uncontextualised entry as a field-wide standard multiplies the original error rather than correcting it.' },
  { id: 'q-f-wd-05', scope: 'final', competency: 'well-delivery', stem: 'At the delivery gate, the shallow hazard assessment for the top-hole section has not been completed and no site survey interpretation is available. The rig arrives in nine days. What is the correct gate outcome?', options: ['Approve with a condition that the shallow hazard assessment be closed before spud, owned by the subsurface lead', 'Hold, because the evidence needed to judge the top-hole risk does not yet exist', 'Approve, and manage the shallow hazard through the drilling programme and real-time monitoring', 'Condition the approval on the rig arriving with a shallow gas diverter configured and tested'], answer: 1, explanation: 'A Hold is the correct instrument when the evidence required to make the decision is absent, since there is nothing to attach a condition to. Conditioning on a pre-spud action assumes the risk is characterised and only needs closing out, which is precisely what is not yet true.' },
  { id: 'q-f-wd-06', scope: 'final', competency: 'well-delivery', stem: 'A casing shoe depth is specified as 2,400 m in the well programme, while the pore pressure prognosis that justified it is plotted against TVDSS. In a high-angle well, why is this combination hazardous?', options: ['Pore pressure prognoses are only valid in vertical wells and must be re-derived for deviated sections', 'The shoe depth should be quoted in TVD, since casing tension is governed by vertical depth', 'If the programme figure is MD, the shoe may sit at a materially different vertical depth than the pressure regime assumed', 'MD and TVDSS diverge only below the kick-off point, so the risk is confined to the reservoir section'], answer: 2, explanation: 'In a high-angle well MD and vertical depth diverge substantially, so an MD shoe depth can place the casing in a different pressure regime than the prognosis intended. Pore pressure prognoses are not invalidated by deviation; they are simply referenced to vertical depth and must be read that way.' },
  { id: 'q-f-wd-07', scope: 'final', competency: 'well-delivery', stem: 'Two platform wells are planned from adjacent slots. Where in the well profile does the anti-collision risk typically peak?', options: ['In the shallow section, where the wells are close together and positional uncertainty is already accumulating', 'At total depth, where accumulated survey uncertainty is greatest', 'Through the build section, where dogleg severity is highest', 'In the reservoir section, where multiple wells converge on the same drainage area'], answer: 0, explanation: 'The shallow section combines minimal physical separation from slot spacing with uncertainty that is already non-trivial, so the separation factor is at its worst there. At total depth the uncertainty ellipses are larger but the wells have usually diverged far enough that clearance is comfortable.' },
  { id: 'q-f-wd-08', scope: 'final', competency: 'well-delivery', stem: 'A well is moved forward two months in the sequence to fill a rig gap. The design is unchanged and the rig is capable. What should the sequencing review examine most closely?', options: ['Whether the shorter lead time compresses the design review cycle below the standard duration', 'Whether the well remains the highest value option in the portfolio at the earlier date', 'Whether moving the well changes its planned duration through seasonal weather exposure', 'Whether the dependencies and long-lead items the well relies on can be delivered against the earlier date, and what other milestones are displaced'], answer: 3, explanation: 'Moving a slot changes readiness and milestone exposure, so the question is what the well still needs and what else in the sequence is pushed out. Design review timing and value ranking matter, but neither determines whether the earlier slot is physically executable.' },
  { id: 'q-f-wd-09', scope: 'final', competency: 'well-delivery', stem: 'A risk register lists "wellbore instability in the shale section" with mitigation "increase mud weight and monitor cavings". No name appears against the entry. What is the primary problem?', options: ['The mitigation is too generic and should specify a numerical mud weight window', 'With no owner, nobody is accountable for implementing or verifying the mitigation before the section is drilled', 'Instability should be classified as a design assumption rather than a risk', 'Cavings monitoring is a real-time observation and cannot serve as a mitigation'], answer: 1, explanation: 'A mitigation needs an owner, otherwise it is a statement of intent that no one is answerable for at execution. Adding a numerical mud weight would sharpen the action but still leaves nobody responsible for applying or verifying it.' },
];

/* Field development — model spine, petrophysics, volumetric lineage, uncertainty and value. */
const FIELD_DEVELOPMENT: Question[] = [
  { id: 'q-d2-01', scope: 'day2', competency: 'field-development', stem: 'A petrophysicist raises the porosity cutoff from 0.08 to 0.12 across all wells. Net pay and STOIIP both fall, and the team asks what this tells them.', options: ['The volume drop confirms the original case was optimistic and should be replaced without further review.', 'Average porosity of the reservoir has been revised downward, which is what reduces the calculated volume.', 'Less rock now qualifies as net, so volume falls; accuracy is unchanged unless the cutoff is justified by flow or test evidence.', 'A higher cutoff removes poor rock, so the remaining pay is more certain and the new STOIIP carries a narrower range.'], answer: 2, explanation: 'A cutoff is a bookkeeping rule about which rock is counted, so raising it always reduces net volume without adding information. The tempting distractor treats a lower number as a more accurate one; conservatism and accuracy are not the same thing.' },
  { id: 'q-d2-02', scope: 'day2', competency: 'field-development', stem: 'A junior geologist builds a three-well correlation panel with measured depth on the vertical axis. Two of the three wells are strongly deviated through the reservoir.', options: ['The panel must be rebuilt in TVDSS before any structural conclusion, because MD carries hole deviation.', 'MD is acceptable for correlation provided all three wells share the same rig datum and logging contractor.', 'The panel is valid because correlation reads log character, and depth reference only matters once volumes are calculated.', 'MD is the safer choice for deviated wells because it preserves the true thickness the bit actually penetrated.'], answer: 0, explanation: 'Along-hole depth inflates apparent thickness and shifts apparent structure in deviated wells, so structural correlation requires a common vertical datum. A shared rig datum does not help, because the distortion comes from inclination rather than from the reference point.' },
  { id: 'q-d2-03', scope: 'day2', competency: 'field-development', stem: 'Two reports quote the oil-water contact for the same accumulation as 3100 m and 3096 m. One value comes from a wireline pressure interpretation, the other from the static model.', options: ['The 4 m difference sits within normal pick uncertainty, so the two values can simply be averaged before gross rock volume is computed.', 'The deeper value should be adopted, since a deeper contact is the conservative choice for a reserves case.', 'The pressure-derived contact supersedes the model value because pressure data are measurement rather than interpretation.', 'The depth reference behind each value must be established first, since a TVD versus TVDSS mismatch can create an apparent contact difference.'], answer: 3, explanation: 'A few metres of difference is exactly the size of a datum offset, so the reference must be resolved before the discrepancy is treated as geological. Averaging is wrong because it buries a possible bookkeeping error inside a number that then propagates into GRV.' },
  { id: 'q-d2-04', scope: 'day2', competency: 'field-development', stem: 'A structural case is rerun with the oil-water contact placed 10 m deeper. STOIIP rises by more than 20 percent while every petrophysical input is unchanged.', options: ['The result must be an error, because a contact shift cannot change volume by more than the fractional change in column height.', 'Gross rock volume depends on the area captured at each depth, so a small contact shift can add a large volume on a flat-flanked structure.', 'The rise shows that net-to-gross was silently recalculated when the contact was moved.', 'Contact depth affects recoverable volume only, so STOIIP should be insensitive to where the contact is placed.'], answer: 1, explanation: 'GRV is an area-depth integral, so on a low-relief structure the last few metres of column can enclose a disproportionate map area. The distractor that scales volume with column height assumes a constant cross-section, which almost no real trap has.' },
  { id: 'q-d2-05', scope: 'day2', competency: 'field-development', stem: 'A volumetric case is rebuilt with the formation volume factor revised from 1.25 to 1.35 reservoir m3 per stock tank m3, with all other inputs held fixed.', options: ['STOIIP falls, because Bo divides the reservoir hydrocarbon volume to give a stock tank volume.', 'STOIIP rises, because a larger formation volume factor means more oil is present in the reservoir pore space.', 'STOIIP is unchanged, because Bo is applied only when converting production rates measured at surface.', 'STOIIP falls by exactly 10 percent, matching the fractional change carried through to the recovery factor.'], answer: 0, explanation: 'Bo sits in the denominator, so a larger value means each stock tank barrel occupies more reservoir volume and the surface-referenced number drops. The distractor that reads a larger Bo as more oil confuses shrinkage on production with hydrocarbon in place.' },
  { id: 'q-d2-06', scope: 'day2', competency: 'field-development', stem: 'A subsurface lead reports net-to-gross of 0.62 while the petrophysicist reports net pay as 0.48 of the same gross interval, and the project manager asks which figure is the error.', options: ['One of the two must be wrong, since both describe the fraction of the gross interval that qualifies as reservoir rock.', 'Net-to-gross should always be the smaller figure, because it applies the saturation cutoff last.', 'Neither is necessarily wrong; net reservoir and net pay use different cutoff sets, so the cutoffs must be stated alongside each figure.', 'The lower figure should be adopted for volumetrics, because the conservative case is the defensible one.'], answer: 2, explanation: 'Net reservoir typically applies rock-quality cutoffs while net pay adds a saturation criterion, so the two legitimately differ and only become comparable once the cutoffs are declared. Picking the lower number for safety avoids the real question of which definition the volumetric equation actually needs.' },
  { id: 'q-d2-07', scope: 'day2', competency: 'field-development', stem: 'Log-derived porosity averages 0.21 over an interval where overburden-corrected core plugs average 0.18. The property model is due for handover in two days.', options: ['The log values should stand, because core plugs sample a tiny fraction of the interval and are not representative.', 'The core values should replace the log curve entirely wherever core coverage exists.', 'The difference is within tool noise and can be set aside until an appraisal well is drilled.', 'The log transform should be re-examined against the core, with any residual difference carried explicitly as porosity uncertainty.'], answer: 3, explanation: 'Core is the calibration anchor, so a systematic three porosity unit offset is a signal to revisit the transform and then carry what remains as a stated uncertainty. Wholesale replacement by core is wrong because plugs cannot populate the uncored intervals that dominate the volume.' },
  { id: 'q-d2-08', scope: 'day2', competency: 'field-development', stem: 'A top-reservoir surface gridded from eight well picks shows a sharp local high at one well. The interpreter increases grid smoothing until the high flattens out.', options: ['This is correct practice, because a single control point cannot be resolved by the grid and smoothing removes the artefact.', 'The pick should be checked first, because smoothing hides a possible data error rather than resolving whether the high is real.', 'The well should be dropped from the grid, since one anomalous control point cannot be reconciled with the other seven.', 'Smoothing is acceptable provided a seismic horizon is later used to constrain the same surface.'], answer: 1, explanation: 'QC belongs before interpolation, and a single-well high is exactly the signature of a mis-picked marker or a depth reference error that should be diagnosed rather than filtered. Smoothing changes the map without ever establishing whether the input was wrong, and the same is true of quietly deleting the well.' },
  { id: 'q-d2-09', scope: 'day2', competency: 'field-development', stem: 'A tornado plot shows contact depth dominating the STOIIP range, with porosity and net-to-gross contributing far less. The team proposes a three-month rock-typing study.', options: ['The study is justified, because rock typing improves the property model across the whole field.', 'The study should run in parallel, since every input contributes to the range and none can be deprioritised.', 'Effort should target contact definition first, because work on a minor driver is unlikely to move the decision.', 'The tornado should be rebuilt with equal input ranges before any ranking of drivers is trusted.'], answer: 2, explanation: 'Ranking drivers exists precisely so that study effort is spent where it can change the outcome, and here that is the contact. Equalising the input ranges would destroy the ranking, since the whole point is that each input carries its own credible range.' },
  { id: 'q-d2-10', scope: 'day2', competency: 'field-development', stem: 'A pilot hole is proposed to tighten the porosity range. Reviewing the concepts, the team finds the same development plan is selected at every porosity value inside the current range.', options: ['The pilot hole carries low value of information here, because no plausible outcome changes the decision.', 'The pilot hole is worthwhile, because reducing any technical uncertainty raises confidence in the forecast.', 'The pilot hole should be acquired if its cost is small relative to total project capex.', 'Value of information cannot be assessed until the data have been acquired and interpreted.'], answer: 0, explanation: 'Information has value only when an outcome could flip the choice, and a decision that is invariant across the range fails that test. Cheapness relative to capex is not a justification, since a low-cost measurement that changes nothing still returns nothing.' },
  { id: 'q-f-fd-01', scope: 'final', competency: 'field-development', stem: 'At the decision gate the STOIIP range spans a factor of three and the low case does not support the proposed facility size. The team wants to record a Select.', options: ['Select is defensible, because the mid case supports the facility and the low case is deliberately pessimistic.', 'Reject is required, because a low case that fails the facility test disqualifies the development.', 'Select is acceptable with a note that the range will narrow once production data arrive.', 'Rework is the honest call, naming the dominant uncertainty and the one study most likely to move it.'], answer: 3, explanation: 'A case whose low outcome breaks the concept is not ready to select, but a wide range is a reason to narrow it rather than to abandon the field. Selecting on the mid case treats the range as decoration and commits facility capital against an untested downside.' },
  { id: 'q-f-fd-02', scope: 'final', competency: 'field-development', stem: 'A partner memo states recoverable volume as gross rock volume times net-to-gross times porosity times one minus water saturation, times a recovery factor.', options: ['The expression is correct, because Bo cancels once a recovery factor is applied.', 'Bo is missing; the in-place volume must be divided by Bo before the recovery factor is applied.', 'The recovery factor should be applied before the saturation term, because recovery acts on movable oil.', 'The expression yields recoverable reservoir volume, which is the standard basis for partner reporting.'], answer: 1, explanation: 'Without dividing by Bo the result stays in reservoir volume and overstates the stock tank number, and recovery factor is applied only after the in-place volume is properly referenced to surface. Bo does not cancel against RF, since the two describe entirely different physical effects.' },
  { id: 'q-f-fd-03', scope: 'final', competency: 'field-development', stem: 'In a partner meeting a screening economics run is presented as evidence that the field holds 40 million barrels of proved reserves.', options: ['The claim conflates two things, because screening economics tests whether a case is worth progressing, not whether volumes meet a reserves definition.', 'The claim stands, provided the screening case used the low-side volume together with a positive NPV.', 'The claim stands, because demonstrated commerciality is the defining test for proved reserves.', 'The claim needs only an updated oil price deck before it becomes a valid reserves statement.'], answer: 0, explanation: 'Screening economics is a ranking tool built on provisional inputs, whereas a reserves classification requires defined project maturity, evidence and audit under a recognised framework. Commerciality is one condition among several, so a positive NPV alone never converts a screening volume into proved reserves.' },
  { id: 'q-f-fd-04', scope: 'final', competency: 'field-development', stem: 'Two volumetric cases are said to differ only in water saturation, 0.25 against 0.35, yet the reported STOIIP differs by a factor of two.', options: ['The result is expected, because hydrocarbon saturation is the strongest single term in the volumetric equation.', 'The result is expected, because Sw also drives net pay through the saturation cutoff, which doubles its effect.', 'The delta is too large for that change alone, so a second input has moved and the lineage must be reconciled.', 'The two cases should be averaged, since neither saturation value can be shown to be correct.'], answer: 2, explanation: 'That saturation change alters the hydrocarbon term by roughly 15 percent, so a factor of two proves something else moved and the input lineage has to be traced. The cutoff-coupling answer names a real mechanism but cannot plausibly stretch a 15 percent effect to 100 percent.' },
  { id: 'q-f-fd-05', scope: 'final', competency: 'field-development', stem: 'A completion engineer asks for perforations 20 m above the contact and quotes a single depth number. The well is deviated at about 55 degrees through the reservoir.', options: ['The number can be passed straight to the completion program, since contact and perforation lie in the same wellbore.', 'The number is safe as long as both the driller and the geologist work from the rig floor as datum.', 'The request should be held until 3D seismic confirms the contact position.', 'The reference must be stated, because 20 m above the contact in TVDSS is roughly 35 m along hole at that inclination.'], answer: 3, explanation: 'At 55 degrees the along-hole equivalent of a vertical standoff is about 20 divided by the cosine of the angle, so the two numbers differ by around 15 m and a silent swap perforates near the contact. A shared rig-floor datum removes the elevation offset but does nothing about the MD to TVD conversion.' },
  { id: 'q-f-fd-06', scope: 'final', competency: 'field-development', stem: 'A static model is handed over with formation tops loaded as fixed values and no alternative correlation stored anywhere in the project.', options: ['This removes the ability to test alternatives, since picks are interpretations and the model should carry at least one competing correlation.', 'This is good practice, because a single agreed correlation stops downstream teams producing inconsistent volumes.', 'This is acceptable, because tops are read directly from logs and are therefore measurements rather than interpretations.', 'This matters only for the property model, because gross rock volume depends on surfaces rather than on well tops.'], answer: 0, explanation: 'Markers are interpretations, and a model that cannot express a second correlation cannot produce an honest structural range. Consistency is a real benefit but it is bought here by hiding uncertainty, and the tops are exactly what the surfaces are built from.' },
  { id: 'q-f-fd-07', scope: 'final', competency: 'field-development', stem: 'A permeability cube is built from a porosity to permeability transform fitted on 30 core plugs from a single well, then used to rank candidate drainage points across the whole field.', options: ['The approach is sound, because porosity to permeability transforms are physically based and therefore transferable.', 'The ranking inherits the assumptions of the transform, so its applicability away from the cored well must be stated and tested.', 'The cube should be rescaled so that its mean permeability matches the field-average porosity trend.', 'Core permeability should not be used at all, because plug-scale measurements are irrelevant to flow.'], answer: 1, explanation: 'A single-well transform encodes that facies and diagenetic history, so extrapolating it across a field is a stated assumption that needs testing against any other well or test data. Calling such transforms physically based overstates them, since the porosity to permeability relationship is empirical and rock-type specific.' },
  { id: 'q-f-fd-08', scope: 'final', competency: 'field-development', stem: 'A well test would consume three weeks of rig time. The two development concepts still on the table are separated mainly by expected well productivity, which the test would resolve.', options: ['The test should be deferred, because concept selection can be revisited after first production.', 'The test is not justified, because rig time always outweighs the value of a single data point.', 'The test is justified, because well tests are standard practice ahead of concept selection.', 'The test carries high value of information, because its outcome plausibly switches the selected concept.'], answer: 3, explanation: 'The test is worth acquiring precisely because a plausible result changes which concept is chosen, which is the definition of decision-relevant information. Invoking standard practice is not an argument, since the same test would be worthless if both concepts survived every possible productivity outcome.' },
  { id: 'q-f-fd-09', scope: 'final', competency: 'field-development', stem: 'A STOIIP case comes in above the volume the planned facility can handle, and a manager suggests raising the shale volume cutoff until the number fits the facility.', options: ['This is acceptable, because a stricter cutoff yields a more conservative and therefore more defensible case.', 'This is acceptable provided the new cutoff is applied consistently across every well in the field.', 'This fits the answer to the desired result, because a cutoff must be set from log and core evidence rather than from facility capacity.', 'This is the wrong lever, because the recovery factor should be reduced instead to bring the case into range.'], answer: 2, explanation: 'Cutoffs are technical parameters justified by rock and flow evidence, so tuning one to hit a capacity target corrupts the in-place estimate that every later decision rests on. Applying the manipulated cutoff consistently makes the bias uniform rather than making it legitimate.' },
  { id: 'q-f-fd-10', scope: 'final', competency: 'field-development', stem: 'A decision deck opens with a single STOIIP figure and a recommended concept, with the full uncertainty analysis placed in an appendix.', options: ['This is appropriate, because decision makers need a clear recommendation rather than a range.', 'The range should frame the recommendation, because a single figure hides whether the concept survives the low case.', 'The single figure is acceptable if it is the P50, which by definition represents the expected outcome.', 'The appendix is sufficient, provided the deterministic case was built from mid-case inputs throughout.'], answer: 1, explanation: 'Range comes before recommendation because the decision depends on how the concept behaves across the range, not on one point inside it. The P50 defence also misreads the statistic, since P50 is the median and a mid-input deterministic case is not generally the mean outcome.' },
  { id: 'q-f-fd-11', scope: 'final', competency: 'field-development', stem: 'Two wells logged with different tool suites are used to populate a porosity model, and no environmental corrections were ever applied to the older well.', options: ['The curves must be normalised and QC checked first, because the property model will propagate bias from the older well across its drainage area.', 'The model averages the two wells, so tool differences cancel and no correction is required.', 'The older well should simply be given a lower weight during interpolation.', 'Environmental corrections affect saturation only, so porosity population is unaffected.'], answer: 0, explanation: 'Interpolation spreads a systematic log bias over the whole region a well controls, so correction and normalisation must precede property modelling. Down-weighting only dilutes the error, and it never removes a bias that is systematic rather than random.' },
  { id: 'q-f-fd-12', scope: 'final', competency: 'field-development', stem: 'At the gate the team names reservoir quality as the dominant uncertainty and proposes a broad multi-disciplinary study to address it.', options: ['This is adequate, because reservoir quality usefully bundles porosity, permeability and net-to-gross together.', 'The team should instead name whichever input carries the widest absolute range, regardless of its effect on volume.', 'The uncertainty must be stated specifically enough that a single study can plausibly change the decision.', 'The gate should be passed now and the study scoped after the concept has been selected.'], answer: 2, explanation: 'A named uncertainty is only useful when it is sharp enough to point at one piece of work whose outcome could move the decision. Bundling several parameters under reservoir quality feels comprehensive but guarantees a study that returns after months without having resolved anything decision-relevant.' },
];

/* Reservoir management — validated signal, competing mechanisms, forecast boundaries, closed loop. */
const RESERVOIR_MANAGEMENT: Question[] = [
  { id: 'q-d4-01', scope: 'day4', competency: 'reservoir-management', stem: 'Overnight a producer reports water cut stepping from 22 to 46 percent, while wellhead pressure, choke setting and the last well test are unchanged. The step coincides with a revision of the field allocation model after a neighbouring well came online. What is the most defensible first move?', options: ['Choke the well back by a third to suppress what is most likely rate-sensitive coning before more oil is lost.', 'Validate the allocation and metering chain against the well test before treating the step as reservoir behaviour.', 'Add the well to the water shutoff candidate list and begin scoping a rig intervention for the next slot.', 'Rebuild the decline forecast on the new higher water cut so the production outlook stays current.'], answer: 1, explanation: 'A step change with no movement in any physical driver, timed to an allocation revision, is far more likely an accounting artefact than a reservoir event. Cutting rate spends real oil to treat a signal that may not exist.' },
  { id: 'q-d4-02', scope: 'day4', competency: 'reservoir-management', stem: 'A producer is tested at 250 sm3/d of oil and 750 sm3/d of water, with negligible free gas at the separator. How should the water production be reported on the surveillance sheet?', options: ['A water cut of 3.0, since water cut is defined as the ratio of water rate to oil rate.', 'A water cut of 33 percent, taking the oil rate divided by the water rate.', 'A water cut of 75 percent, equivalent to a water-oil ratio of 3.0.', 'A water cut of 25 percent, since the oil fraction of the stream sets the cut.'], answer: 2, explanation: 'Water cut is water rate over total liquid rate, so 750/1000 = 75 percent; the value 3.0 is the water-oil ratio, a different and unbounded measure that is easily confused with cut.' },
  { id: 'q-d4-03', scope: 'day4', competency: 'reservoir-management', stem: 'Two neighbouring producers both show water cut climbing over three months. Each is choked back by roughly 30 percent; after two weeks one well drops back several points while the other is unchanged. What does this best support?', options: ['Both wells are coning, and the second simply needs a longer stabilisation period before the same response appears.', 'Both wells are on injector breakthrough along the same layer, and the first responded only because total liquid rate fell.', 'Neither result is diagnostic, because water cut mechanically falls whenever total liquid rate is reduced.', 'The responsive well fits rate-sensitive coning, while the unresponsive one points to channelling.'], answer: 3, explanation: 'Coning is a near-wellbore drawdown effect that can partly reverse when rate is reduced, whereas channelling through a high-permeability layer or fracture is generally not rate-reversible. Water cut does not automatically fall with rate, so the contrast between the two wells is genuinely informative.' },
  { id: 'q-d4-04', scope: 'day4', competency: 'reservoir-management', stem: 'A multi-zone producer shows steadily rising water cut. The team is split between water entering from the lower perforated interval and a completion integrity failure above the reservoir. Which single measurement most directly discriminates?', options: ['A production log across the completion to identify the depth at which water enters the wellbore.', 'A pressure build-up survey to re-estimate permeability and near-wellbore skin.', 'A pressure response at a nearby observation well to test inter-well connectivity.', 'A month of higher-frequency well tests to confirm that the water cut trend is real.'], answer: 0, explanation: 'A PLT resolves which interval or depth is producing water, which is exactly what separates the two hypotheses. Observation-well pressure tests connectivity between wells, something neither hypothesis actually disputes.' },
  { id: 'q-d4-05', scope: 'day4', competency: 'reservoir-management', stem: 'A well was converted from natural flow to gas lift six weeks ago and the rate stepped up. An engineer fits an Arps hyperbolic decline through the full four-year history, including the last six weeks, to update reserves. What is the main problem?', options: ['Hyperbolic decline is invalid for any well on artificial lift, so the whole history should be refitted with a harmonic form.', 'Six weeks is too short a sample, but the same whole-history fit becomes sound once three months of post-conversion data exist.', 'Decline analysis assumes stable operating conditions, so a fit spanning the lift change is invalid and the post-change period is a new segment.', 'The fit is acceptable because Arps is an empirical method and therefore insensitive to changes in operating conditions.'], answer: 2, explanation: 'DCA presumes stable operating conditions and boundary-dominated flow, both broken by a lift change, so the trend must be re-established after the change. The issue is not sample length; more data on the wrong side of a discontinuity does not repair the fit.' },
  { id: 'q-d4-06', scope: 'day4', competency: 'reservoir-management', stem: 'A hyperbolic fit to a mature oil producer returns b = 1.6 with a very long tail, lifting estimated remaining reserves by about 40 percent. How should this result be treated?', options: ['Accept it, since a high b-factor reflects strong aquifer support and is physically expected in a waterflood.', 'Treat it as a red flag, because b above 1 extrapolates to an unbounded cumulative and the tail must be constrained.', 'Accept it once the regression R-squared exceeds 0.95, which validates the extrapolation to abandonment.', 'Reject decline analysis for this well outright and require a full-physics simulation before quoting any reserves number.'], answer: 1, explanation: 'With b greater than 1 the integrated cumulative does not converge, so the extrapolation overstates reserves regardless of fit quality. A high R-squared measures how well history was matched, not whether the forecast is physical.' },
  { id: 'q-d4-07', scope: 'day4', competency: 'reservoir-management', stem: 'A producer has gone from 30 to 55 percent water cut in four months. Coning, injector breakthrough along a high-permeability streak and a completion leak all remain live and the team cannot rank them. The next intervention slot is three months away. What is the strongest recommendation at the decision gate?', options: ['Act now with a water shutoff on the lower interval, since every month of delay costs oil regardless of mechanism.', 'Adopt the mechanism most commonly seen elsewhere in the field and proceed on that basis rather than stalling the decision.', 'Continue monitoring the existing monthly rate and water cut data unchanged and revisit at the next quarterly review.', 'Request a specific surveillance job, naming the hypotheses it separates and the date it feeds the intervention decision.'], answer: 3, explanation: 'Acquiring data is a legitimate gate outcome when evidence genuinely cannot discriminate, provided the request is tied to hypotheses and a decision date. Passive monitoring differs from this: it repeats data already shown to be non-discriminating and lets the intervention slot pass.' },
  { id: 'q-d4-08', scope: 'day4', competency: 'reservoir-management', stem: 'An approved opportunity is written up as: reduce rate on A-12 to manage water; owner, production technology; revisit in Q3. What is the most important element still missing before this can close the loop?', options: ['The expected response and how success will be measured inside a stated verification window.', 'A cost estimate and an economic ranking of the item against the rest of the opportunity portfolio.', 'A named fallback option to be executed if the rate reduction does not deliver the intended effect.', 'Countersigned approval from the subsurface manager in addition to production technology.'], answer: 0, explanation: 'Without a predicted response and a window in which to measure it, the outcome cannot be judged and no model update follows, so the loop stays open. Economic ranking affects prioritisation but generates no learning.' },
  { id: 'q-d4-09', scope: 'day4', competency: 'reservoir-management', stem: 'Over two quarters, producing GOR rises across nearly all producers while average reservoir pressure continues to fall. One engineer proposes gas coning on the highest-rate wells. What is the better first interpretation?', options: ['Gas coning on the high-rate wells remains the leading explanation and is being spread over the other wells by the allocation model.', 'The trend most likely reflects a change in the gas metering factor applied at the processing facility.', 'A field-wide response tracking pressure decline points to a field-scale mechanism such as pressure dropping below saturation pressure.', 'Rising GOR at falling pressure indicates injector breakthrough displacing gas ahead of the advancing water front.'], answer: 2, explanation: 'A mechanism must explain the scale of the observation, and a coherent field-wide trend moving with pressure fits liberation of solution gas below the bubble point. Coning is a near-wellbore, rate-driven effect that would show up on specific wells, not uniformly across the field.' },
  { id: 'q-d4-10', scope: 'day4', competency: 'reservoir-management', stem: 'A producer has held a flat on-stream oil rate all quarter, yet the monthly delivered volume fell about 12 percent. Uptime moved from 96 to 84 percent over the same period. What does this indicate?', options: ['The reservoir is depleting and the apparently flat on-stream rate is a metering artefact that should be discarded.', 'The loss is deferment rather than reservoir performance, and calendar-day rate should be compared with on-stream rate.', 'Uptime is a facilities metric and should be excluded from reservoir surveillance so that the subsurface signal stays clean.', 'The well is being automatically choked back, so the on-stream rate needs re-normalising to the prevailing choke setting.'], answer: 1, explanation: 'On-stream rate held constant while uptime fell, which accounts for the volume loss without any change in reservoir behaviour. Uptime belongs in surveillance precisely because ignoring it makes deferment look like decline.' },
  { id: 'q-f-rm-01', scope: 'final', competency: 'reservoir-management', stem: 'Six months after a successful water shutoff, the team reports the measured uplift and closes the action item. The static and dynamic models still carry the pre-job description of that interval. What is the main consequence?', options: ['Minimal, since the uplift was measured and the value has already been captured in the production numbers.', 'Future decline fits on this well will be biased low, because decline analysis reads the interval description from the model.', 'The main risk is auditing, since the reserves committee cannot sign off the addition without a matching model update.', 'The loop has not closed: the next forecast and candidate screen still run on a description the field disproved.'], answer: 3, explanation: 'Learning is only banked when the model that generates future forecasts and candidates is updated, otherwise the same wrong description keeps producing wrong recommendations. Decline analysis is empirical and does not read the model, so the bias claim is wrong.' },
  { id: 'q-f-rm-02', scope: 'final', competency: 'reservoir-management', stem: 'A partner asks for the number for next year field production. The engineer holds a base decline case, an infill case and a workover case, each with different assumptions. What is the most professional response?', options: ['Provide the base case with its assumptions, its range and the conditions under which each upside case applies.', 'Provide the arithmetic mean of the three cases, since averaging is the least biased way to give one number.', 'Provide the base case alone, because cases that depend on unapproved projects should not be shown to partners.', 'Provide the highest technically defensible case so that facilities and offtake are not under-committed.'], answer: 0, explanation: 'A forecast is a conditional statement, so it is only usable with its assumptions, range and triggers visible. Averaging cases blends mutually exclusive futures into a number that describes none of them.' },
  { id: 'q-f-rm-03', scope: 'final', competency: 'reservoir-management', stem: 'In a water-injected North Sea oil field, reported voidage replacement for one pattern sits above 1.0, yet pressure in the surrounding producers keeps falling and no water breakthrough has appeared. Which explanation deserves testing first?', options: ['The producers are coning water from the underlying aquifer, which locally masks the injection support on the gauges.', 'Injected water may not be reaching the target zone or pattern, so injection allocation, fall-off or tracer data should be checked.', 'Voidage replacement above 1.0 always over-pressures a pattern, so the downhole pressure gauges are most likely drifting.', 'The injectors have fractured and water is arriving at the producers faster than the surveillance frequency can resolve.'], answer: 1, explanation: 'VRR is computed from allocated volumes, so it can look healthy while water exits to a thief zone or out of pattern, which matches falling pressure with no breakthrough. A fractured injector would normally produce early water arrival, which is precisely what is absent.' },
  { id: 'q-f-rm-04', scope: 'final', competency: 'reservoir-management', stem: 'One producer shows a sharp rise in water cut. Before proposing an intervention, the engineer plots the same trend for the other eight wells in the segment and finds all eight rising at a similar pace. How should this change the diagnosis?', options: ['It confirms the well-specific hypothesis, since the well in question is still the worst performer in the group.', 'It eliminates the injectors from consideration, because a shared trend across wells cannot originate from injection.', 'It shifts weight towards a segment-scale cause such as an advancing flood front rather than a well-specific defect.', 'It renders the observation uninformative, since a trend common to a whole segment normally signals an allocation error.'], answer: 2, explanation: 'Cohort comparison separates well-specific mechanisms from shared ones, and a common trend across peers is evidence for a segment-scale process. A shared trend does not exonerate the injectors; a sweeping flood front is itself an injection-driven, field-scale effect.' },
  { id: 'q-f-rm-05', scope: 'final', competency: 'reservoir-management', stem: 'The team disagrees on whether an injector is in pressure communication with a producer across a mapped fault. Which observation would most directly settle the question?', options: ['A production log on the producer to establish which interval is contributing the flow.', 'A water sample from the producer analysed for salinity and ion composition against injection water.', 'A longer history match of the segment in the existing dynamic model.', 'A deliberate rate change at the injector with pressure monitored at the producer or observation well.'], answer: 3, explanation: 'An interference test measures pressure connectivity directly, which is the disputed property. Water chemistry can indicate that injected water arrived but says nothing about connectivity if breakthrough has not yet occurred.' },
  { id: 'q-f-rm-06', scope: 'final', competency: 'reservoir-management', stem: 'After an intervention, an engineer re-fits the decline curve through the entire history including the post-job period, and reports that the well is now performing in line with the new forecast. What is wrong with this as an evaluation?', options: ['The pre-job baseline was overwritten, so there is nothing independent left to measure the uplift against.', 'Re-fitting is acceptable, but the b-factor must be held constant across the job date for the comparison to be valid.', 'Post-job data should never be included in a decline fit until at least twelve months of production have elapsed.', 'The error is using decline analysis at all, since only a calibrated dynamic simulation can evaluate an intervention.'], answer: 0, explanation: 'Uplift is defined against the preserved pre-job forecast, so a refit that absorbs the post-job data guarantees agreement and measures nothing. Holding the b-factor fixed does not restore the lost counterfactual.' },
  { id: 'q-f-rm-07', scope: 'final', competency: 'reservoir-management', stem: 'A proposed infill producer targeting an undrained part of a flooded segment needs a production profile for the investment case. What is the correct method boundary?', options: ['Fit a decline curve to the nearest offset producer and apply it directly, since the two wells share the same reservoir.', 'Decline analysis needs history from the well itself, so the profile must come from analogues or simulation with uncertainty stated.', 'Apply a harmonic decline anchored on a deliberately low initial rate, the standard conservative default for undrilled locations.', 'Treat any profile as speculative and build the investment case on volumetrics alone without a rate forecast.'], answer: 1, explanation: 'DCA extrapolates an established trend and therefore cannot be applied to a well with no history; a physics-based or analogue-based profile with an explicit range is required. Borrowing an offset decline imports that well drainage, depletion state and completion, none of which apply to undrained rock.' },
  { id: 'q-f-rm-08', scope: 'final', competency: 'reservoir-management', stem: 'Coning and channelling are both live explanations for a producer with rising water cut, and the two candidate remedies differ sharply in cost. No rig time is available for six months. What is the most useful next step?', options: ['Book the rig slot now for the higher-value remedy so that the option is not lost to another candidate well.', 'Wait for the water cut to develop further, since the shape of the trend will eventually reveal the mechanism at no cost.', 'Run a controlled, reversible rate reduction with a defined observation period to test whether the response is rate-sensitive.', 'Escalate to a full-field simulation study to resolve the mechanism before committing to any action in the field.'], answer: 2, explanation: 'Rate sensitivity is the practical discriminator between coning and channelling, and a reversible rate test buys that information cheaply within the waiting period. Committing rig time first spends the expensive resource before the diagnosis that determines which remedy is right.' },
  { id: 'q-f-rm-09', scope: 'final', competency: 'reservoir-management', stem: 'A water shutoff was justified on an expected water cut reduction of 15 points sustained for at least three months. Two weeks after the job, water cut is down 18 points and the team wants to declare success and roll the treatment out to five more wells. What is the sound position?', options: ['Declare success now, since exceeding the target ahead of schedule is a stronger result than merely meeting it.', 'Declare success but discount the expected uplift on the remaining five wells as a prudence measure.', 'Discard the original criterion, since early over-performance shows the success measure was set at the wrong level.', 'Hold the agreed verification window, because early post-job behaviour is often transient and that is why the window exists.'], answer: 3, explanation: 'The success measure specified a sustained response precisely because clean-up and near-wellbore effects can flatter the first weeks after a job. Declaring success early converts an unverified result into a five-well commitment.' },
];

export const QUESTIONS: Question[] = [
  ...EXPLORATION,
  ...EVIDENCE,
  ...FIELD_DEVELOPMENT,
  ...WELL_DELIVERY,
  ...RESERVOIR_MANAGEMENT,
  ...INTEGRATED,
];

export function questionsFor(scope: QuestionScope): Question[] {
  return QUESTIONS.filter((q) => q.scope === scope);
}

/** Published blueprint counts, used to show authoring progress against target. */
export const BLUEPRINT: Record<QuestionScope, number> = {
  day1: 10, day2: 10, day3: 10, day4: 10, final: 50,
};
