import { widget, type WorkflowGroup } from '../workspace-blueprint/types';

export const FIELDDEV_WORKFLOWS: WorkflowGroup[] = [
  { id: 'static-model', name: 'Static Reservoir Model', question: 'What reservoir are we developing?', tabs: [
    { id: 'client-data-qc', name: 'Client Data QC & Subsurface Case', purpose: 'Inventory the client delivery and establish an explicit, versioned subsurface basis.', software: 'Petrel project/data workflow-lite', output: 'SubsurfaceCase', legacyStrength: 'Legacy loaders, map tree and provenance badges handle the Volve bundle well.', legacyGap: 'Path-bound Volve package, no client ingestion contract, QC dashboard or immutable case.', widgets: [
      widget('Client delivery inventory', 'Inventory surfaces, grids, logs, trajectories, contacts and metadata.', 'Client-provided OSDU/files only', 'Coverage matrix + validation summary', 'React · Web Workers', 'ClientDeliveryInventory', 'client-gated', 'Legacy CosmoExplorer object tree'),
      widget('Spatial/depth QC', 'Detect CRS, unit, datum, extent and depth-reference conflicts.', 'Client metadata and headers', 'QC exception table + extent map', 'MapLibre GL · d3-array', 'SubsurfaceQcPanel', 'client-gated', 'Legacy loaders assume prepared Volve coordinates'),
      widget('Subsurface case ledger', 'Freeze the accepted inputs and uncertainty inventory.', 'Approved client inputs · analogue assumptions', 'Versioned case card + lineage DAG', 'React · Zustand · SVG', 'SubsurfaceCaseManager', 'new', 'Legacy viewers share mutable state without a case object'),
    ]},
    { id: 'petrophysics-lite', name: 'Petrophysics', purpose: 'Run a simplified Techlog-style deterministic interpretation when client logs and picks are supplied.', software: 'Techlog-lite', output: 'PetrophysicalModel', legacyStrength: 'Legacy log viewer, cutoffs, Vsh/PHIE/Sw recompute, crossplot and upscaling are live and tested.', legacyGap: 'Single-field assumptions, limited multi-well QC, no interpretation version comparison or client import gate.', widgets: [
      widget('Log interpretation', 'Inspect raw curves, computed curves, picks and cutoffs.', 'Client-provided LAS/DLIS-derived curves and formation picks', 'Synchronized multi-track log plot', '@equinor/videx-wellog', 'PetrophysicsLogStudio', 'client-gated', 'Legacy LogsView + Petrophysics'),
      widget('Crossplot & cutoffs', 'Select facies/net cutoffs and inspect sensitivity.', 'Client logs · deterministic petrophysics engine', 'Linked crossplot + histogram', 'Canvas · d3-array', 'PetrophysicsCrossplot', 'reuse', 'Legacy Crossplot/Petrophysics recompute'),
      widget('Upscaling review', 'Compare raw and grid-block property statistics.', 'Interpreted client logs · target grid', 'Raw-vs-upscaled tracks + statistics', 'd3-scale · SVG', 'LogUpscalingReview', 'reuse', 'Legacy fdData upscale functions'),
    ]},
    { id: 'static-model-lite', name: 'Structure, Grid & Properties', purpose: 'Create or review a screening-grade static model from client surfaces/grids or approved simplified geometry.', software: 'Petrel · Roxar RMS-lite', output: 'StaticModelCase', legacyStrength: 'Legacy has strong 2D/3D maps, structural surfaces, Cartesian grid, SGS/SIS and packed 3D viewers.', legacyGap: 'Unfaulted/simple geometry, Volve constants, no client-grid import, model versioning or cross-case QC.', widgets: [
      widget('Structural framework', 'Review surfaces, contacts, closures and gross-rock volume.', 'Client surfaces/grids · user contacts', '2D map + cross-section + 3D surface', 'Canvas · Three.js/R3F', 'StructuralFrameworkViewer', 'adapt', 'Legacy MapView, Structural, Map3D'),
      widget('Grid builder & QC', 'Define layering, active cells and cell-quality statistics.', 'Approved structure · client grid or lightweight builder', '3D voxel grid + quality histograms', 'Three.js/R3F · Web Workers', 'StaticGridBuilder', 'reuse', 'Legacy GridModelView/GridCube3D'),
      widget('Property modeling', 'Run deterministic kriging/SGS/SIS and compare realizations.', 'Client petrophysics · variogram settings · analog priors', 'Property map/volume + realization browser', 'Canvas · Three.js · d3-array', 'PropertyModelStudio', 'reuse', 'Legacy Property; geostat truth-lock 33/33'),
    ]},
  ]},
  { id: 'dynamic-model', name: 'Dynamic Reservoir Model', question: 'How will it perform?', tabs: [
    { id: 'fluids-rock', name: 'PVT, SCAL & Initialization', purpose: 'Define the simplified rock-fluid and initial-state functions required by the dynamic model.', software: 'Techlog · Petrel RE-lite', output: 'DynamicInitialization', legacyStrength: 'Legacy engine includes Volve PVT, Corey relative permeability, contacts and initialization.', legacyGap: 'No editable function workspace, laboratory-data import, region assignment or case validation report.', widgets: [
      widget('PVT functions', 'Review Bo, Rs, Bg, viscosity and bubble-point behavior.', 'Client PVT tables or approved correlations', 'Function plots + property table', 'd3-shape · SVG', 'PvtFunctionEditor', 'client-gated', 'engine/sim/pvt.ts'),
      widget('SCAL functions', 'Edit and validate relative-permeability endpoints and exponents.', 'Client SCAL or analogue defaults', 'Kr/fractional-flow chart', 'd3-shape · SVG', 'ScalFunctionEditor', 'adapt', 'engine/sim/relperm.ts truth-lock'),
      widget('Initialization QC', 'Check contacts, saturation, pore volume and in-place reconciliation.', 'Static model · PVT/SCAL · client pressure', 'Balance cards + depth profiles', 'd3-scale · SVG', 'InitializationQcPanel', 'adapt', 'Legacy volumetric/grid reconciliation tests'),
    ]},
    { id: 'simulation-cases', name: 'Simulation Cases', purpose: 'Run transparent screening-grade ECLIPSE/INTERSECT-style cases on the lightweight model.', software: 'ECLIPSE · INTERSECT-lite', output: 'SimulationRun', legacyStrength: 'Legacy 2D FV simulation, streamlines, pressure solver, packed frames and 3D playback are extensively truth-locked.', legacyGap: 'No durable case manager, client schedule import, 3-phase/full-physics scope or run comparison workflow.', widgets: [
      widget('Case manager', 'Clone, diff, queue and compare immutable simulation cases.', 'StaticModelCase · initialization · client/user schedule', 'Case table + run queue', 'React · Zustand · Web Workers', 'SimulationCaseManager', 'new', 'Legacy SimulationView has one live state'),
      widget('Simulation viewer', 'Playback saturation/pressure and inspect well response.', 'Truth-locked FV simulation frames', '2D/3D time-lapse + scrubber', 'Canvas · Three.js/R3F', 'SimulationResultViewer', 'reuse', 'Legacy SimulationView + SimDrape'),
      widget('Flow diagnostics', 'Inspect streamline allocation, sweep and time of flight.', 'Simulation pressure/velocity field', 'Streamline map + allocation matrix', 'Canvas · d3-scale', 'FlowDiagnosticsViewer', 'reuse', 'engine/sim/streamline.ts'),
    ]},
    { id: 'history-uncertainty', name: 'History Match & Uncertainty', purpose: 'Compare model response with client history and quantify parameter uncertainty.', software: 'Petrel RE · INTERSECT uncertainty-lite', output: 'CalibratedDynamicCase', legacyStrength: 'Legacy has uncertainty tornadoes, ensembles, DCA blind tests and model-vs-reference concepts.', legacyGap: 'No simulation-history objective function, assisted matching, posterior ensemble or case ranking.', widgets: [
      widget('History-match dashboard', 'Compare simulation and client observations with normalized misfit.', 'Client production/pressure history · simulation results', 'Observed-vs-sim plots + misfit matrix', 'd3-shape · SVG', 'HistoryMatchDashboard', 'client-gated', 'Legacy FieldReview is decline-based, not simulation HM'),
      widget('Sensitivity screening', 'Rank uncertain parameters by response impact.', 'Case ensemble · parameter ranges', 'Tornado + Morris screening matrix', 'd3-array · SVG', 'DynamicSensitivityPanel', 'adapt', 'Legacy Uncertainty tornado engine'),
      widget('Ensemble browser', 'Review prior/posterior cases and confidence envelopes.', 'Simulation ensemble · match scores', 'Fan charts + parallel coordinates', 'd3-scale · Canvas', 'EnsembleBrowser', 'new', 'Legacy lacks posterior ensemble handling'),
    ]},
  ]},
  { id: 'development-plan', name: 'Development Planning', question: 'What should we build?', tabs: [
    { id: 'recovery-wells', name: 'Recovery, Pattern & Planned Wells', purpose: 'Turn the calibrated reservoir case into recovery options and scenario planned wells.', software: 'Petrel RE · INTERSECT development planning-lite', output: 'RecoveryScheme · PlannedWellSet', legacyStrength: 'Legacy has streamlines, well-placement drawing, analog recovery and opportunity economics.', legacyGap: 'No integrated pattern generator, well-count optimizer, drainage/PI decision record or planned-well identity.', widgets: [
      widget('Recovery option screen', 'Compare depletion, waterflood and simplified injection strategies.', 'Calibrated case · fluid/rock functions · analog priors', 'Option cards + sweep/VRR matrix', 'React · d3-scale', 'RecoveryOptionScreen', 'adapt', 'Legacy simulation + analog recovery'),
      widget('Pattern & well planner', 'Generate scenario producer/injector patterns and spacing.', 'Client field boundary/grid · recovery option', 'Interactive map + drainage circles/streamlines', 'Canvas · deck.gl', 'PatternWellPlanner', 'adapt', 'Legacy MapView planned-well drawing'),
      widget('Well-count & PI basis', 'Explain count, type, spacing and deliverability ranges.', 'Area · kh · client/analogue constraints', 'Decision table + sensitivity plot', 'd3-array · SVG', 'WellCountBasis', 'new', 'M7 engines specified; not integrated in Legacy'),
    ]},
    { id: 'forecast-phasing', name: 'Forecast, Constraints & Phasing', purpose: 'Translate development cases into production profiles and staged execution plans.', software: 'INTERSECT · ECLIPSE schedule-lite', output: 'ProductionProfile · DevelopmentSchedule', legacyStrength: 'Legacy has simulation production, DCA, forecast fan charts and economic profiles.', legacyGap: 'No greenfield ramp/plateau engine, facility constraints, integrated phasing or case-to-schedule seam.', widgets: [
      widget('Production forecast', 'Compare simulation, type-curve and analog forecast modes.', 'Simulation runs · client history when available · analogs', 'P10/P50/P90 fan chart', 'd3-shape · SVG', 'DevelopmentForecastViewer', 'reuse', 'Legacy Forecast + review.ts DCA'),
      widget('Constraint model', 'Apply liquids, water, gas, injection and uptime limits.', 'Client facility limits or user scenarios', 'Constraint timeline + bottleneck waterfall', 'd3-scale · SVG', 'FacilityConstraintModel', 'new', 'Legacy forecast is not facility constrained'),
      widget('Development phasing', 'Stage wells, facilities and first production by case.', 'PlannedWellSet · constraints · user dates', 'Milestone Gantt', 'SVG · d3-scale', 'DevelopmentPhasingGantt', 'adapt', 'Legacy Drilling Gantt mechanics, absent from FD'),
    ]},
    { id: 'value-fdp', name: 'Economics, Cases & FDP', purpose: 'Compare development cases, expose uncertainty and record the FID recommendation.', software: 'Merak Peep · PlanningSpace-lite', output: 'EconomicCase · FDPDocument', legacyStrength: 'Legacy economics, NPV, tornado, break-even and Field Review decisions are truth-locked.', legacyGap: 'Simplified fiscal model, hard-coded option set, no full case DAG, immutable sanction gate or FDP assembler.', widgets: [
      widget('Economic case', 'Calculate cash flow, NPV, IRR, payback and break-even.', 'Development schedule · production · user fiscal/cost deck', 'Cash-flow chart + KPI table', 'd3-shape · SVG', 'EconomicCaseViewer', 'reuse', 'Legacy Economics + engine/econ.ts'),
      widget('Case comparison', 'Compare technical, schedule, value and confidence side by side.', 'Versioned development cases', 'Decision matrix + tornado', 'd3-scale · React', 'DevelopmentCaseComparator', 'adapt', 'Legacy FieldReview fixed FDP options'),
      widget('FDP/FID package', 'Assemble selected artifacts and capture approval.', 'Artifact DAG · selected case · evidence ledger', 'Document outline + gate checklist', 'React · CSS Grid', 'FdpDecisionPackage', 'new', 'Legacy has no artifact-driven FDP assembly'),
    ]},
  ]},
];
