import type { DaySyllabus } from './types';

/** Day 4 - OPERATE (Reservoir Management). Output: Reservoir Action Card. */
export const DAY4: DaySyllabus = {
  slides: [
    { layout: 'divider', eyebrow: 'DAY 4 - OPERATE', title: 'The well delivered on Day 3 now produces data, not certainty', body: 'Day 3 handed over a completed Hugin Formation producer under water injection support. From first flow it stops being a construction project and becomes one element in a coupled system of producers, injectors, facilities and an allocation model. Day 4 is about reading that system without being fooled by it.', bullets: ['Inherited - a delivered well, its completion design and its offset injector pattern', 'New reality - rates are allocated by a model at most points in time, not measured', 'Question of the day - which field signal matters and what should happen next', 'Output - a Reservoir Action Card, Act, Acquire Data or Monitor'], note: 'Open the Reservoir Management workspace on the field performance overview and leave it on screen while you frame the day. Ask the room who owns the well now that it is producing, because the answer is usually contested and that is the point. Pre-empt the assumption that operations is a lower-status phase than subsurface design.' },
    { layout: 'objective', eyebrow: 'OBJECTIVE - DAY 4', title: 'By close of play you can defend a diagnosis and the action it justifies', body: 'The standard is not that you produce an explanation. The standard is that you can state which competing explanations remain alive, what evidence would separate them, and what you propose to do given that state of knowledge.', bullets: ['Validate a production signal before treating it as reservoir behaviour', 'Hold at least two competing mechanisms and name the discriminating test', 'State a forecast as a conditional claim with its method boundary attached', 'Choose between Act, Acquire Data and Monitor with named conditions', 'Assign an owner, an expected response and a verification window'], note: 'Read the verbs aloud - validate, discriminate, condition, decide, verify. Tell the room that a diagnosis claiming certainty will score lower than one that ranks two mechanisms honestly. Pre-empt the belief that Monitor is a weak answer, because you will grade it as a full decision later in the day.' },
    { layout: 'framework', eyebrow: 'FRAME - THE LOOP', title: 'The surveillance loop earns its keep only when it changes a decision', body: 'Monitor, Diagnose, Forecast, Act, Learn is a decision cycle rather than a reporting cycle. Every element of it is justified only by the action it can change, and measurement that cannot change an action is cost rather than information.', bullets: ['Monitor - detect the exception against an approved baseline, not against last month', 'Diagnose - convert an observation into ranked candidate mechanisms', 'Forecast - state what happens if nothing changes and if something does', 'Act - intervene, acquire data or accept the trend deliberately', 'Learn - verify the outcome and update the model that produced the call'], note: 'Walk the five stages on the workspace navigation so the room sees that the loop is the software structure and not a slide device. Put the question to the room - name one report your organisation produces monthly that has never changed a decision. Pre-empt the belief that more data is always better, because value of information is the test.' },
    { layout: 'concept', eyebrow: 'EVIDENCE - VALIDATION', title: 'Allocation and metering artefacts arrive disguised as reservoir behaviour', body: 'Well rates on most producing assets are allocated from a field total using a model, not measured continuously at the wellhead. When that model is revised, every derived quantity moves at once, and the movement looks exactly like a reservoir event.', bullets: ['Check test rates, allocation factors and revision dates before any diagnosis', 'Ask whether the step aligns with a well test rather than a reservoir process', 'Confirm uptime and downtime coding before interpreting a rate change', 'Treat voidage replacement ratio as an allocated quantity, not a measurement', 'Record the data vintage that supported the call'], note: 'Demonstrate the production validation module live and show where allocation revisions become visible. Ask the room how many of them can name the date of their last allocation model change. Pre-empt the habit of moving from a chart to a mechanism within ten seconds.' },
    { layout: 'concept', eyebrow: 'EVIDENCE - SIGNAL SET', title: 'Deferment is not decline', body: 'A falling oil rate has at least four ordinary explanations before reservoir depletion becomes one of them - reduced uptime, a choke or lift change, an allocation revision, and a facility constraint. Ratios and pressure carry the reservoir signal more reliably than rate alone.', bullets: ['Rate - contaminated by uptime, choke settings and facility constraints', 'Water cut - water rate divided by total liquid rate, on a bounded scale', 'Water-oil ratio - unbounded and better than water cut for trend diagnostics', 'Gas-oil ratio - sensitive to pressure crossing bubble point and to lift gas', 'Pressure - the closest thing to a state variable the reservoir offers you'], note: 'Plot water cut and water-oil ratio for the same series and show that one saturates while the other keeps resolving. Ask which they would put in a monthly report and which in a diagnostic. Pre-empt the routine confusion of water cut with water-oil ratio, and of either with gas-oil ratio.' },
    { layout: 'example', eyebrow: 'EVIDENCE - WORKED EXAMPLE', title: 'A water cut step that lands on a revision date is an accounting event until proven otherwise', body: 'Illustrative case - a Volve producer shows water cut rising by roughly ten percentage points within a single reporting month, with no choke change, no workover and no injector event. The step coincides with the month in which the allocation model was re-based after a new well test.', bullets: ['The step is instantaneous at a month boundary, which reservoir processes rarely are', 'Field total water is unchanged while the split between wells moves', 'The offset producer moves the opposite way by a similar magnitude', 'The next independent well test is the decisive check, not further trend fitting', 'Working conclusion - reallocation leads, pending confirmation by test'], note: 'Put the chart up before revealing the revision date and make the room commit to a mechanism first, because most will diagnose water breakthrough. Use the mirrored move on the offset well as the tell. Pre-empt the objection that this is contrived by asking how often they reconcile well volumes against the field total.' },
    { layout: 'framework', eyebrow: 'METHOD - DIAGNOSIS', title: 'Observation is not mechanism', body: 'Water arriving at a producer is an observation. Coning, channelling, a completion failure and an allocation error are mechanisms, and all four can produce the same chart. Diagnosis is the disciplined act of keeping competing mechanisms alive until evidence separates them.', bullets: ['List candidate mechanisms explicitly before ranking any of them', 'State the observable each mechanism predicts, including what it forbids', 'Rank by weight of evidence, not by which is easiest to fix', 'Name the cheapest single test that separates the top two', 'Carry the surviving alternatives into the action decision'], note: 'Write four candidate mechanisms on the board and ask which chart alone can eliminate any of them, because the honest answer is none. Demonstrate the diagnostics module with two mechanisms deliberately held open. Pre-empt premature convergence, which is the dominant failure mode in the exercise that follows.' },
    { layout: 'concept', eyebrow: 'METHOD - DISCRIMINATION', title: 'Rate reversibility and interval resolution separate the four candidates', body: 'The common mechanisms differ in what they predict under a controlled rate change and under a production log. That difference is what makes them testable rather than a matter of opinion.', bullets: ['Coning - near-wellbore and drawdown driven, partly reverses when rate is reduced', 'Channelling through a high permeability layer or fracture - not rate reversible', 'Completion failure - often abrupt and correlated with a recent well intervention', 'Allocation error - moves with revision dates and reverses on offset wells', 'A production log resolves which interval produces water; an interference test resolves connectivity between wells'], note: 'Be explicit that a production log and an interference test answer different questions and are not substitutes for each other. Ask which test they would order if the budget allowed only one, then ask what question they are actually trying to answer. Pre-empt the reflex of ordering the most expensive survey available.' },
    { layout: 'example', eyebrow: 'METHOD - WORKED EXAMPLE', title: 'A reversible rate test is the cheapest evidence that separates coning from channelling', body: 'Illustrative case - the producer is choked back by roughly a third for a defined hold period at otherwise stable conditions, then restored. Under coning, water cut falls materially during the reduced-rate period and returns on restoration. Under channelling, water cut is largely insensitive to the rate change.', bullets: ['Design the test with a stated hold period, stable lift and no other change', 'Write both predicted outcomes down first, so neither can be rationalised after', 'The cost is deferred production, which is small against a well intervention', 'A partial response indicates a mixed mechanism, not a failed test', 'The result changes the action either way, which is what makes it worth buying'], note: 'Insist on the pre-registered prediction, because a test whose outcomes were not written down in advance will always be explained away. Ask the room to price a few days of deferment against a rigless water shutoff. Pre-empt the assumption that reducing rate is simply a loss.' },
    { layout: 'exercise', eyebrow: 'EXERCISE 1 - BRIEF', title: 'Diagnose the exception without collapsing to a single story', body: 'You will take a flagged performance exception on a Volve producer through coverage, validation, diagnostics and pressure context, and produce a Diagnosis note. The note must rank at least two mechanisms and name the test that would separate them.', bullets: ['Scope - one producing well, one flagged exception, one pinned data vintage', 'Sequence - performance overview, coverage, validation, diagnostics, pressure and pattern', 'Deliverable - Diagnosis note with ranked mechanisms and a discriminating test', 'Time - 45 minutes working, 15 minutes debrief', 'Grading - the evidence captured at each step, not the elegance of the conclusion'], note: 'Assign pairs and require one person in each pair to argue the alternative mechanism deliberately. Circulate and challenge any table that has converged inside ten minutes. Pre-empt the reflex request for more data by asking what decision the extra data would change.' },
    { layout: 'debrief', eyebrow: 'EXERCISE 1 - DEBRIEF', title: 'Strong notes ranked mechanisms; weak notes named one and defended it', body: 'The separating behaviour was whether the pair validated the series before interpreting it. Tables that started in the diagnostics module almost always produced a confident diagnosis of a signal that had not yet been shown to be real.', bullets: ['Good - validation evidence and data vintage recorded before any mechanism is named', 'Good - two mechanisms carried forward with the discriminating test specified', 'Failure - reading a downtime-driven rate drop as decline', 'Failure - using a healthy voidage replacement ratio as proof of no water exit path', 'Failure - ordering a production log to answer a connectivity question'], note: 'Take two notes from the room and read the mechanism ranking aloud without naming authors. Reinforce that voidage replacement ratio is computed from allocated volumes, so it can look healthy while water leaves to a thief zone. Close by asking each pair what they would do tomorrow morning.' },
    { layout: 'framework', eyebrow: 'METHOD - FORECAST', title: 'A forecast is a conditional statement, not a prediction', body: 'Decline analysis says what will happen if operating conditions remain as they were during the fitted period and if flow is boundary dominated. Both clauses are assumptions about the world, and both are routinely violated on producing assets.', bullets: ['Arps requires stable operating conditions across the fitted interval', 'Arps requires boundary-dominated flow rather than transient behaviour', 'A change in choke, artificial lift or completion terminates the fit window', 'Changes in injection support alter the drive the decline implicitly encodes', 'State the condition set with the number, or the number is not usable'], note: 'Write the two assumptions on the board and leave them there for the rest of the day. Ask the room to name a well in their own asset whose decline was fitted straight through a lift change. Pre-empt the view that decline analysis is simple, because it is simple to compute and easy to invalidate.' },
    { layout: 'concept', eyebrow: 'METHOD - BOUNDARY', title: 'A good history fit is not a valid forecast', body: 'Fit quality measures agreement with the past inside the fitted window. It says nothing about whether the assumptions hold forward. The most common failure is a hyperbolic fit with a b-factor above one, which extrapolates to an unbounded cumulative and quietly inflates reserves.', bullets: ['A b-factor above one does not converge; cumulative production grows without limit', 'Constrain b to a defensible range or impose a terminal exponential decline', 'Fit only across intervals in which operating conditions did not change', 'Blind-test the fit by withholding the most recent period and predicting it', 'Report the fit window and the condition set alongside the forecast rate'], note: 'Demonstrate the decline module and push b above one so the room watches the cumulative run away. Ask what economic decision that number would have supported. Pre-empt the argument that a high b is justified by layered or transient behaviour by asking them to demonstrate boundary-dominated flow first.' },
    { layout: 'concept', eyebrow: 'RANGE - UNCERTAINTY', title: 'Preserve the baseline, show the range, state the boundary', body: 'On a producing asset the value of a forecast lies in the difference between cases, not in the central line. That difference exists only if the approved baseline is frozen and preserved while the intervention case is built beside it.', bullets: ['Version and freeze the approved base case before any scenario work begins', 'Build the intervention case as a delta against that frozen baseline', 'Carry low, mid and high cases with the assumption that drives the spread', 'State the method boundary explicitly on every case you publish', 'Report uplift as a range with a verification window, not as a point'], note: 'Show the forecast case module and version the base case live before adding a scenario. Ask who in the room can retrieve the forecast their asset approved twelve months ago. Pre-empt the common practice of overwriting the base case every month, which destroys the ability to measure anything at all.' },
    { layout: 'example', eyebrow: 'RANGE - WORKED EXAMPLE', title: 'Re-fitting through an intervention destroys the evidence that it worked', body: 'Illustrative case - a water shutoff is executed on a Volve producer and the decline curve is then re-fitted across the whole history including the intervention. The new fit passes smoothly through the event, the residuals look excellent, and the uplift becomes unmeasurable because no counterfactual survives.', bullets: ['The pre-intervention fit is the counterfactual and must be frozen first', 'Uplift is measured against that frozen baseline extrapolated forward', 'A fit spanning the event absorbs the uplift into the curve parameters', 'Excellent residuals here are a symptom, not a validation', 'Without a counterfactual the intervention cannot be justified again elsewhere'], note: 'Draw the two fits side by side and let the room see that the better-looking one has answered no question. Ask how their organisation currently proves that an intervention paid back. Pre-empt the reply that production simply went up, because in many of those cases the baseline went up as well.' },
    { layout: 'exercise', eyebrow: 'EXERCISE 2 - BRIEF', title: 'Screen the action against the diagnosis you can actually defend', body: 'You will carry the Diagnosis note into well-test and decline evaluation, build a base and intervention case, price the information option, screen candidate actions and issue a Reservoir Action Card. Act, Acquire Data and Monitor are all valid outcomes when the conditions are named.', bullets: ['Scope - same well, same pinned vintage, diagnosis carried forward unchanged', 'Sequence - decline evaluation, forecast cases, information value, screening, action record', 'Deliverable - Reservoir Action Card with owner, expected response and verification window', 'Time - 45 minutes working, 15 minutes debrief', 'Grading - the condition set and the verification plan, not the size of the prize'], note: 'State plainly that a card recommending Acquire Data is graded as highly as one recommending Act, provided the evidence genuinely cannot discriminate. Circulate and ask each table what result would make them abandon their chosen action. Pre-empt prize inflation by requiring the range rather than the high case.' },
    { layout: 'debrief', eyebrow: 'EXERCISE 2 - DEBRIEF', title: 'The strongest cards named what would prove them wrong', body: 'Cards that specified an expected response, a verification window and a falsification condition were defensible whichever option they chose. Cards that led with a value figure and carried no condition set were not.', bullets: ['Good - an Acquire Data call justified by two mechanisms that remain genuinely live', 'Good - uplift stated as a range against a frozen and versioned baseline', 'Good - a named owner and a date on which the response will be checked', 'Failure - a decline fit spanning a lift change used to size the prize', 'Failure - an action with no stated outcome that would count as failure'], note: 'Read out one card that chose Monitor and defend it publicly so the room stops treating Monitor as a non-answer. Ask each table for their falsification condition in a single sentence. Pre-empt the belief that a decision is only credible when something is executed.' },
    { layout: 'framework', eyebrow: 'DECIDE - THE GATE', title: 'Act, Acquire Data or Monitor - each is a decision with conditions', body: 'The gate call follows from the state of the evidence, not from organisational appetite. Where the evidence cannot discriminate between mechanisms whose optimal actions differ, acquiring data is the correct decision and should be argued on value of information.', bullets: ['Act - one mechanism dominates and the intervention is robust to the alternatives', 'Acquire Data - mechanisms remain live and they imply different actions', 'Monitor - the trend is understood and does not yet cross an economic threshold', 'Every option carries an owner, an expected response and a verification window', 'Every option carries the observation that would reverse the call'], note: 'Force each table to place their case in exactly one of the three boxes with no hedging. Ask what the cost of being wrong is in each box, because it is asymmetric. Pre-empt the culture in which Monitor reads as indecision, since an unverified action is worse than a well-conditioned wait.' },
    { layout: 'summary', eyebrow: 'SUMMARY - DAY 4', title: 'Operate is the discipline of not being fooled by your own data', body: 'The day moved from a signal that had to be validated, through mechanisms that had to be held in competition, to a forecast that means nothing without its conditions, and ended in a decision that can be checked against reality.', bullets: ['Frame - the loop exists to change a decision, not to produce a report', 'Evidence - validate allocation, uptime and vintage before interpreting anything', 'Method - observation is not mechanism, and rate reversibility discriminates', 'Range - freeze the baseline, carry the spread, state the method boundary', 'Decide - Act, Acquire Data or Monitor, each with an owner and a verification window'], note: 'Put the six beats on screen and ask which beat their own organisation skips most often, because the answer is usually validation. Recap that the Reservoir Action Card is the artifact of the day, not the slide pack. Close by naming exactly what Day 5 will do with it.' },
    { layout: 'bridge', eyebrow: 'HANDOFF - TO DAY 5', title: 'The Action Card closes the lifecycle evidence chain that Day 5 audits', body: 'Day 5 reviews the field as an integrated whole, and it can only do that if each phase handed forward a traceable claim. The Reservoir Action Card is the operating end of that chain, linking the delivered well back to the development concept and to the original prospect case.', bullets: ['Carried forward - the validated signal with its data vintage and allocation state', 'Carried forward - the ranked diagnosis and the surviving alternative mechanisms', 'Carried forward - the frozen base case and the intervention delta with its range', 'Carried forward - the gate call, its owner and its verification window', 'Day 5 tests whether the chain from prospect to producing well holds together'], note: 'Show the action tracking module and the record the card lands in, so the handoff is a real object rather than a promise. Ask each table to write one sentence on what they now believe that they did not believe this morning. Pre-empt the idea that Day 5 is a wrap-up session, because it is an audit of everything produced so far.' },
  ],
  missions: [
    {
      title: 'Diagnose the exception',
      brief: 'A flagged performance exception on a Volve Hugin Formation producer under water injection support has reached the surveillance review. Take it from raw flag to a defensible Diagnosis note that ranks competing mechanisms and names the test that separates them.',
      scope: 'Volve - producing well - performance exception',
      output: 'Diagnosis note',
      steps: [
        { title: 'Pin the exception', detail: 'Filter to the flagged producer and define the exception against the approved baseline rather than against last month.', evidence: 'Well identifier, exception type, the first date the deviation is visible, and the baseline version it is measured against.', module: 'performance-overview' },
        { title: 'Audit the data behind it', detail: 'Review surveillance coverage for the well and record which measurements exist, at what frequency and how recent they are, including well tests and any pressure surveys.', evidence: 'Coverage summary for the well showing the date of the most recent well test and an explicit list of decision-critical gaps.', module: 'surveillance-coverage' },
        { title: 'Validate before you interpret', detail: 'Reconcile allocated rates against uptime and injection records, and check whether the exception coincides with an allocation revision or a downtime episode.', evidence: 'Statement of whether the signal is validated, contaminated or unresolved, supported by the allocation revision dates and the uptime record.', module: 'production-validation' },
        { title: 'Separate rate from ratio', detail: 'Build the diagnostic set for the well - oil rate, water cut, water-oil ratio and gas-oil ratio - and characterise the change in shape rather than in size.', evidence: 'Diagnostic panel capture with the change classified as a step, a trend or a discontinuity, plus a written description of the water-oil ratio behaviour.', module: 'production-diagnostics' },
        { title: 'Test it against pressure and pattern', detail: 'Check the reservoir pressure trend and the behaviour of the supporting injectors and offset producers to see whether the pattern corroborates or contradicts each candidate mechanism.', evidence: 'Diagnosis note listing at least two ranked mechanisms, the pattern evidence for and against each, and the single discriminating test proposed.', module: 'pressure-pattern' },
      ],
    },
    {
      title: 'Screen the action',
      brief: 'Carry the Diagnosis note forward and decide what the asset should do. Evaluate decline within honest method boundaries, build a base and intervention case, price the information option, and issue a Reservoir Action Card that can be verified.',
      scope: 'Volve - producing well - action screening on the diagnosed exception',
      output: 'Reservoir Action Card - Act, Acquire Data or Monitor',
      steps: [
        { title: 'Establish the defensible fit window', detail: 'Review the well tests and fit decline only across intervals with unchanged choke, lift and completion, stopping the window where an operating change occurs.', evidence: 'Fit window start and end dates, the b-factor used with its justification, and the operating changes that bound the window.', module: 'welltest-decline' },
        { title: 'Freeze the baseline and build the delta', detail: 'Version the approved base case, then create the intervention case as a delta against it instead of re-fitting the full history through the event.', evidence: 'Base case version identifier plus low, mid and high intervention uplift expressed as a range against the frozen baseline.', module: 'forecast-cases' },
        { title: 'Price the information option', detail: 'For the discriminating test named in the Diagnosis note, set out its cost, its duration and what each possible outcome would change in the action choice.', evidence: 'Value of information statement giving the test, its cost and duration, and the different action that each outcome would trigger.', module: 'surveillance-coverage' },
        { title: 'Rank the candidate actions', detail: 'Screen the realistic options - rate management, rigless water shutoff, deeper intervention and no action - against the ranked mechanisms and the uplift range.', evidence: 'Ranked option table naming the mechanism each option assumes and the exposure if the alternative mechanism turns out to be the true one.', module: 'opportunity-screening' },
        { title: 'Issue the Action Card', detail: 'Record the gate call in the action register with its full condition set, so that the outcome can later be checked against what was predicted.', evidence: 'Reservoir Action Card stating Act, Acquire Data or Monitor, with owner, expected response, verification window and the observation that would reverse the call.', module: 'actions-learning' },
      ],
    },
  ],
};
