import type { DaySyllabus } from './types';

/** Day 5 - DECIDE (Integrated Field Review). Output: Integrated Field Decision. */
export const DAY5: DaySyllabus = {
  slides: [
    { layout: 'divider', eyebrow: 'DAY 05 - DECIDE', title: 'The field is one connected decision', body: 'Four days produced four separate gate cards on one real North Sea field. Today they stop being four artifacts and become a single evidence chain carrying a single recommendation.', bullets: ['Exploration Gate Card - Progress, Study or Stop', 'Development Case Card - Select, Rework or Reject', 'Well Gate Card - Approve, Condition or Hold', 'Reservoir Action Card - Act, Acquire Data or Monitor', 'Integrated Field Decision - what all four now oblige you to do'], note: 'Keep this opener under five minutes because the teams need the build time. Put the four inherited cards on the wall and ask each team which of them they would defend least well this morning. The honest answer is usually the one they wrote fastest.' },
    { layout: 'objective', eyebrow: 'OBJECTIVES - WHAT YOU WILL DO', title: 'By this evening you will defend a field decision on its process, not on its optimism', body: 'Day 5 is not a revision day. It tests whether you can integrate four lifecycle handoffs into one auditable argument and stand behind it while a panel that has read the same evidence attacks it.', bullets: ['Frame a field decision with an owner, real options, criteria and a reversal trigger', 'Trace any headline number back to the record that produced it', 'Propagate one change across all four lifecycle handoffs and price the consequence', 'Cut an uncertainty list down to the few that can change the recommendation', 'Present and defend a seven-element field review under challenge'], note: 'Read these as verbs the learner will be graded on, not as topics that will be covered. State early that the final exam is individual and the capstone is team, and that neither the leaderboard nor team performance decides certification.' },
    { layout: 'framework', eyebrow: 'FRAME - BEFORE THE ANALYSIS', title: 'Frame the decision before you touch the analysis', body: 'A decision exists only when someone can say who owns it, what the genuine alternatives are, what measure separates them and by when it must be made. Analysis started before that frame is set produces evidence that nobody can act on.', bullets: ['Decision owner - the person who can say yes and fund it', 'Options - at least three, mutually exclusive, all genuinely executable', 'Criteria - the measures that separate the options, with thresholds', 'Timing - the date after which the decision is made by default', 'Trigger - the observation that would reverse the call'], note: 'Ask the room who owned the last decision they built analysis for; most will not be able to name a person. Pre-empt the belief that framing is administrative overhead - an unframed decision is the single most common reason good subsurface work is never used.' },
    { layout: 'concept', eyebrow: 'FRAME - THE FAILURE MODE', title: 'A recommendation with no stated decision cannot be judged', body: 'If the decision is unstated, every option can be defended and none can be refused, because there is no criterion available to fail against. The reviewer is then reduced to assessing the confidence of the presenter instead of the quality of the case.', bullets: ['No stated decision means no test of what is relevant', 'No alternatives means the recommendation survives by default, not by merit', 'No criteria means the most senior voice in the room decides', 'No trigger means the case can never be shown to be wrong'], note: 'Show a real-sounding but unframed recommendation and ask the room to argue against it - they will find they cannot, and that is the point. Name the trap explicitly - an argument that cannot be lost is not strong, it is empty.' },
    { layout: 'example', eyebrow: 'FRAME - WORKED EXAMPLE', title: 'There is upside in the Hugin becomes a dated, owned, reversible choice', body: 'Weak version - the Hugin Formation still has upside and we should drill more wells. It names no owner, no alternative, no measure and no deadline, so it can be neither approved nor rejected.', bullets: ['Decision - commit the next rig slot to a northern-segment infill producer, or to an injector conversion, or to neither', 'Owner - the asset manager, before the rig option window closes', 'Criteria - incremental recovery per unit cost, and observed pattern pressure response', 'Evidence anchors - Day 2 static case, Day 3 slot conflict, Day 4 pattern diagnosis', 'Trigger - a pending pressure survey showing the segment is already supported reverses the infill call'], note: 'Do this reframe live on the board with the room supplying each element, and refuse to move on until someone names a person for owner. Point out that nothing was analysed here - only the question was fixed, and it already changed what evidence matters.' },
    { layout: 'framework', eyebrow: 'EVIDENCE - THE CHAIN', title: 'Every number in the review must be able to name its parent', body: 'An evidence chain is not a bibliography. Each number carries the record it came from, the transformation applied to it and the downstream item that moves when it moves.', bullets: ['Upstream source - the record, its truth class and its date', 'Transformation - the method applied and the assumptions it rests on', 'Downstream consequence - what changes if this number changes', 'Custody - who owns the number now, and who owned it before', 'Break point - the link you would attack first if you were the challenger'], note: 'Open the cockpit and pick one number off a team board at random, then walk it back to source in front of the room. The exercise is uncomfortable by design and it sets the standard for the whole day - an anchor you cannot open in under a minute is not an anchor.' },
    { layout: 'concept', eyebrow: 'EVIDENCE - PROPAGATION', title: 'A moved surface is never only a moved surface', body: 'A structural or contact revision changes volume, which moves the target, which changes the trajectory, which consumes rig days, which shifts the profile, which changes the forecast and the value. The chain runs whether or not anyone chooses to trace it.', bullets: ['Volume moves first and most visibly, so it absorbs all the attention', 'Target and trajectory move next, and they cost rig days', 'Schedule moves the shape of the profile, not merely the date', 'Forecast and value move last, and are the first things blamed', 'An untraced consequence does not disappear, it arrives unannounced'], note: 'Ask which of these five links their own organisation actually reviews when a model is updated - the honest answer is usually the first and the last. Pre-empt the idea that this is a modelling problem; it is a handoff problem, which is why it belongs on Day 5.' },
    { layout: 'example', eyebrow: 'EVIDENCE - WORKED EXAMPLE', title: 'One contact revision travels from the Day 2 static model to the Day 4 production consequence', body: 'Take the Hugin fluid contact from the Day 2 base case and deepen it by a few metres, staying inside the range the existing pressure evidence already permits. Nothing improper has been done, and yet four downstream artifacts are now stale.', bullets: ['Static - gross rock volume rises materially in the flank segment, and volume in place follows', 'Development - the flank becomes an economic target, changing the well count and the sequence', 'Well delivery - the landing point moves down-dip and the trajectory tightens against the dogleg limit', 'Reservoir management - injection support reaches the new perforations later, so the pattern response lags', 'Value - first oil is unchanged, but the plateau lengthens and the water handling peak arrives earlier'], note: 'Run the revision live in the cockpit rather than describing it, and pause after each link to ask which team would have caught it. Use clearly illustrative magnitudes only - the point is the propagation path, not a proprietary number, and say so plainly.' },
    { layout: 'concept', eyebrow: 'METHOD - DECISION QUALITY', title: 'Judge the decision on the process, because the outcome has not happened yet', body: 'Decision quality is assessed on six elements - an appropriate frame, genuinely different alternatives, reliable information, clear values and trade-offs, sound reasoning, and commitment to action. A well made decision can still produce a poor outcome, and a reckless one can get lucky.', bullets: ['Frame - the right decision, at the right scope, at the right time', 'Alternatives - genuinely different, not one option flanked by two strawmen', 'Information - reliable, and worth more than it cost to acquire', 'Values and reasoning - the trade-off made explicit rather than absorbed', 'Commitment - the organisation will actually execute what was chosen'], note: 'Pre-empt outcome bias directly, because it is the strongest reflex in the room - ask who would call a decision good if the well came in dry. Then state the rule the panel will apply this afternoon - you are graded on the six elements, and the panel will never be told how Volve actually performed until after scoring.' },
    { layout: 'exercise', eyebrow: 'EXERCISE 1 - BUILD THE INTEGRATED CASE', title: 'Assemble the chain before you argue the conclusion', body: 'Ninety minutes in the cockpit. Take the four inherited gate cards, absorb the integrated event card you are dealt, and produce a field case that a reviewer can audit from source record to recommendation without asking you a question.', bullets: ['Scope - Volve, full lifecycle, cockpit only, no new analysis', 'Input - your four gate cards plus one integrated event card', 'Output - integrated field case with all seven review elements drafted', 'Rule - any claim that cannot be traced to a record does not go on the board', 'Discipline - integrate what exists rather than generating something new'], note: 'Hand out the event cards face down and start the clock immediately so no team can pre-plan around a variant. Circulate and ask one question only - show me where that number came from - and refuse to accept a chart as an answer.' },
    { layout: 'debrief', eyebrow: 'DEBRIEF 1 - WHAT GOOD LOOKED LIKE', title: 'The strong teams cut evidence; the weak teams collected it', body: 'Every team had access to the same four days of material. The separation came entirely from what teams were willing to leave out and from whether their anchors survived a single traceability question.', bullets: ['Strong - three anchors, each opened in the cockpit inside a minute', 'Strong - the event card consequence traced through all four handoffs', 'Weak - a chronological restatement of four days instead of an integration', 'Weak - an uncertainty carried forward that no option was sensitive to', 'Weak - an option set containing one real choice and two placeholders'], note: 'Debrief on process only and do not reveal which case was closest to the historical outcome. Name the failure modes without naming the teams, and ask each team to delete one item from its board before the afternoon - the deletion is the lesson.' },
    { layout: 'framework', eyebrow: 'RANGE - WHAT SURVIVES', title: 'Carry only the uncertainties capable of changing the recommendation', body: 'Uncertainty management in a field review is a filtering task, not an inventory task. Start from the option set and ask, for each variable, what plausible value would cause a different option to win.', bullets: ['Start from the options, never from the model input list', 'Ask what value of this variable would flip the choice', 'If no plausible value flips it, it is context and it leaves the review', 'If a plausible value flips it, it earns a slot, an owner and a date', 'Data is worth acquiring only when a plausible result would change the decision'], note: 'Demonstrate the value of information test on a survey the teams all want to run, and show that some of them would act identically whichever way it came back. Pre-empt the objection that this discards rigour - the range still exists in the model, it simply does not consume review time it cannot repay.' },
    { layout: 'concept', eyebrow: 'RANGE - THE THREE-PART FILTER', title: 'Material, decision-relevant and actionable - all three, or it leaves the room', body: 'Each surviving uncertainty must be large enough to move the outcome measure, capable of changing which option wins, and open to something being done about it before the decision date. Two out of three makes a footnote, not a review item.', bullets: ['Material - large enough to move the measure the criteria are written against', 'Decision-relevant - a plausible value changes which option is selected', 'Actionable - a study, survey or test can move it before the decision date', 'Material but not decision-relevant - report it, do not review it', 'Decision-relevant but not actionable - it becomes a condition, not a study'], note: 'Work the fourth and fifth bullets slowly because they are where most teams misfile things. The decision-relevant but unactionable case is the most important one to get right - it does not justify delay, it justifies a named condition and a reversal trigger.' },
    { layout: 'example', eyebrow: 'RANGE - WORKED EXAMPLE', title: 'The widest range on the board is not the one that decides', body: 'Two uncertainties from the Volve case. A permeability multiplier with a wide range across the Hugin, and a narrowly bounded cross-fault transmissibility on a single flank segment.', bullets: ['Permeability - by far the widest input range anyone has on the board', 'Permeability - both options win together or lose together across that whole range, so it is decision-invariant', 'Transmissibility - a narrow range, already well constrained by pressure evidence', 'Transmissibility - one end supports the flank injector, the other strands it, so the option flips', 'The narrow uncertainty gets the surveillance budget; the wide one gets a footnote'], note: 'Put both on screen and ask the room to vote on which deserves the study money before you reveal the sensitivity. Most rooms choose the wide one, which is exactly the instinct this slide exists to break.' },
    { layout: 'framework', eyebrow: 'THE FIELD REVIEW - SEVEN ELEMENTS', title: 'Seven elements, ten minutes, nothing else on the screen', body: 'The review format is fixed so that the panel compares arguments rather than production values. Anything not in the seven elements is removed before you present.', bullets: ['The decision, and the single option you recommend', 'Three evidence anchors, each traceable to a source record on demand', 'Two uncertainties that could reverse the call, with the test that would settle them', 'Lifecycle consequences across all four inherited handoffs', 'The next action, with owner and date, and the trigger that defines success'], note: 'Publish the rubric before the build begins so no team can claim surprise, and state that the seven elements map to the four scoring dimensions. Warn the room that a slide containing anything outside the seven elements costs presentation time and earns nothing.' },
    { layout: 'exercise', eyebrow: 'EXERCISE 2 - THE FIELD REVIEW', title: 'Defend the case in front of a panel that has read the same evidence', body: 'Seven minutes to present the seven elements, three minutes of challenge. The panel has full access to the cockpit and will ask you to open any anchor you cite.', bullets: ['Format - seven minutes present, three minutes challenge, no extensions', 'Panel - the facilitator plus two peer reviewers drawn from other teams', 'Rule - every anchor must be openable in the cockpit while the panel watches', 'Rule - naming what would change your mind scores; defending everything does not', 'Output - the Integrated Field Decision with its conditions recorded'], note: 'Brief the peer reviewers privately to ask one traceability question and one reversal question each, and to stay on process rather than on geology preferences. Cut presenters at seven minutes without exception so the constraint stays real for the teams that follow.' },
    { layout: 'debrief', eyebrow: 'DEBRIEF 2 - HOW THE PANEL SCORED IT', title: 'The panel scored traceability and reversibility, not eloquence', body: 'Scores separated on two behaviours - whether an anchor could be opened on demand, and whether the team could state the observation that would reverse its own recommendation. Presentation polish moved nothing.', bullets: ['Workflow - was the cockpit used to find evidence, or only to display it', 'Evidence - did each anchor survive being opened in front of the panel', 'Decision - one option, named conditions, an owner and a date', 'Reversibility - the team volunteered what would change its mind', 'Common loss - a confident recommendation with no condition attached to it'], note: 'Give each team one sentence of what worked and one of what cost them, and keep it public so the calibration is shared. Close the debrief by restating that the outcome at Volve is still not the grading standard, and only reveal historical performance afterwards as a discussion piece.' },
    { layout: 'framework', eyebrow: 'DECIDE - THE INTEGRATED CALL', title: 'Attach the conditions, or you have not actually decided anything', body: 'An integrated field decision is one option plus the conditions under which it holds. Without verifiable conditions and a named reversal trigger, what has been produced is a preference, and it will be relitigated the moment anything moves.', bullets: ['The call - one option, stated in one sentence, with the owner named', 'The conditions - each with a verifiable criterion, an owner and a date', 'The information plan - only data whose plausible result changes the call', 'The reversal trigger - the observation that sends this back to this room', 'The record - the decision, its basis and its date, written where the next team will find it'], note: 'Insist on the difference between a condition and a wish - subject to further study is not a condition, whereas a stated criterion checked by a named person by a stated date is. Point out that the last bullet is the whole course in miniature - Day 5 exists because Day 1 wrote its basis down.' },
    { layout: 'summary', eyebrow: 'THE COURSE ON ONE PAGE', title: 'One spine, four gate cards, one evidence chain', body: 'Volve was the instrument, not the subject. What was actually taught is a repeatable six-beat method for converting evidence of mixed quality into a decision that can be audited by someone who was not in the room.', bullets: ['The spine - frame, evidence, method, range, decide, handoff, every single day', 'The cards - four gate decisions, each with named conditions and a reversal trigger', 'The chain - Hugin evidence through static case, well plan, production response and value', 'The filter - material, decision-relevant, actionable, or it does not survive the review', 'The standard - process quality is what you control; the outcome is not'], note: 'Walk the six beats once, fast, and let the room recite them back rather than reading them off the slide. This is the page people photograph, so leave it up while you take questions.' },
    { layout: 'bridge', eyebrow: 'HANDOFF - MONDAY MORNING', title: 'The method leaves with you; the field stays behind', body: 'Volve is a clean, publicly released, fully closed lifecycle, and your own asset is none of those things. The six beats still apply, and the first place they bite is a decision your organisation is already arguing about without having framed it.', bullets: ['Pick one live decision in your asset and frame it before Wednesday', 'Find the three anchors that carry it, and the one that cannot be traced', 'Cut your uncertainty list with the three-part filter and defend the deletions', 'Write the reversal trigger down where your successor will find it', 'The Fieldcraft Passport records the individual exam, the captured mission evidence and the demonstrated competencies'], note: 'Ask each participant to say the one decision they will frame on Monday out loud before they leave, because a stated commitment survives the flight home. Close by stating plainly that the leaderboard is a teaching device and never determines individual certification - the Passport rests on the individual exam and the evidence each person captured.' },
  ],
  missions: [
    {
      title: 'Build the integrated case',
      brief: 'Take the four inherited gate cards and one integrated event card, and assemble a single auditable field case in the cockpit without generating any new analysis.',
      scope: 'Volve - full lifecycle evidence chain',
      output: 'Integrated field case',
      steps: [
        { title: 'Assemble the chain', detail: 'Pin the cockpit scope to Volve and lay the four inherited gate cards end to end, from the exploration call through to the reservoir action. Identify the numbers that appear in more than one card.', evidence: 'The four gate calls in lifecycle order, plus one number that carries through all four and the record it originates from.', module: 'cockpit' },
        { title: 'Test the consequence', detail: 'Apply the integrated event card you were dealt and trace its effect forward through every downstream handoff until it reaches value. Stop at each link and record what became stale.', evidence: 'The propagation path across all four handoffs, naming the artifact invalidated at each step.', module: 'cockpit' },
        { title: 'Filter the uncertainty', detail: 'List every uncertainty still live after the event card, then apply the material, decision-relevant and actionable filter to each one in turn.', evidence: 'Every uncertainty considered, with a one-line reason each was kept or cut, and no more than two survivors.', module: 'cockpit' },
        { title: 'Frame the options', detail: 'Define at least three mutually exclusive and genuinely executable options for the next field decision, and state the criteria that separate them.', evidence: 'Three options, the separating criteria with thresholds, the named decision owner and the decision date.', module: 'cockpit' },
        { title: 'Draft the recommendation', detail: 'Select one option and build the draft case around it - three traceable evidence anchors, the surviving uncertainties and the condition the call depends on.', evidence: 'The recommended option in one sentence, three anchors each with a source record, and one attached condition.', module: 'cockpit' },
      ],
    },
    {
      title: 'The Field Review',
      brief: 'Present the integrated case as a seven-element field review, survive a panel challenge on traceability and reversibility, and record the decision with the conditions that make it real.',
      scope: 'Volve - full lifecycle evidence chain - review panel',
      output: 'Integrated Field Decision',
      steps: [
        { title: 'Build the seven-element board', detail: 'Reduce the integrated case to exactly seven elements - decision, option, three anchors, two uncertainties, lifecycle consequences, next action, success trigger. Remove everything else.', evidence: 'The seven elements as they will be presented, plus a list of what you removed and why.', module: 'cockpit' },
        { title: 'Rehearse the trace', detail: 'Dry run the review inside the cockpit, opening each of the three anchors from its source record while a teammate times you.', evidence: 'The cockpit path to each anchor and the time taken to open it, with any anchor that failed the test replaced.', module: 'cockpit' },
        { title: 'Present to the panel', detail: 'Deliver the seven elements in seven minutes, with the evidence live on screen rather than described.', evidence: 'The delivered element sequence and the anchors the panel asked you to open during the presentation.', module: 'cockpit' },
        { title: 'Take the challenge', detail: 'Answer three minutes of panel challenge, conceding where the chain is weak instead of defending every point.', evidence: 'The hardest question put to you, your answer, and the one part of your case it genuinely weakened.', module: 'cockpit' },
        { title: 'Record the decision and its conditions', detail: 'Commit the final call in writing with the conditions attached, and state the observation that would send it back to the review.', evidence: 'The decision in one sentence, each condition with criterion, owner and date, the success trigger and the reversal trigger.', module: 'cockpit' },
      ],
    },
  ],
};
