import { widget, type WorkflowGroup } from '../workspace-blueprint/types';

export const DRILLING_WORKFLOWS: WorkflowGroup[] = [
  { id: 'campaign-setup', name: 'Campaign Setup', question: 'What is ready and what capacity exists?', tabs: [
    { id: 'sanctioned-intake', name: 'Sanctioned-Well Intake', purpose: 'Validate client wells and approved Well Delivery handoffs before scheduling.', software: 'Landmark EDM · OpenWells-lite', output: 'SchedulableWellSet', legacyStrength: 'Legacy schedule consumes proposal gates and renders well maturity.', legacyGap: 'It schedules bundled Volve wells automatically; no client-only intake gate, shared identity or completeness validation.', widgets: [
      widget('Well intake queue', 'List sanctioned wells and block incomplete records.', 'Client master data · approved Well Delivery handoffs', 'Readiness queue + validation badges', 'React · CSS Grid', 'SanctionedWellQueue', 'client-gated', 'Legacy maturation dashboard'),
      widget('Duration basis', 'Compare P10/P50/P90 section and total durations.', 'Client offsets/programmes · analogue duration model', 'Distribution bars + basis table', 'd3-scale · SVG', 'DrillingDurationBasis', 'client-gated', 'Legacy schedule-model deterministic duration'),
      widget('Dependency register', 'Capture predecessors, earliest starts and shared constraints.', 'Client programme constraints · user rules', 'Dependency graph + exception table', 'd3-shape · SVG', 'WellDependencyRegister', 'new', 'Legacy dependency fields are effectively empty'),
    ]},
    { id: 'rig-fleet', name: 'Rig Fleet & Capability', purpose: 'Model client rig availability and compatibility with the sanctioned well set.', software: 'Primavera P6 · OpenWells-lite', output: 'RigCapacityPlan', legacyStrength: 'Legacy Rigs view has utilization, activities and a clear two-lane model.', legacyGap: 'Rig names/capacity are seeded; no capability matrix, contracts, availability windows or maintenance constraints.', widgets: [
      widget('Rig register', 'Capture availability, contract windows and operational limits.', 'Client rig/contract data', 'Rig cards + availability timeline', 'SVG · React', 'RigFleetRegister', 'client-gated', 'Legacy RigsView'),
      widget('Rig-well compatibility', 'Screen depth, pressure, load, water depth and equipment fit.', 'Client rig capability · sanctioned well requirements', 'Compatibility matrix', 'React · CSS Grid', 'RigCompatibilityMatrix', 'client-gated', 'Legacy has no compatibility engine'),
      widget('Capacity outlook', 'Compare demand with available rig months.', 'Rig availability · duration basis', 'Demand/capacity stacked timeline', 'd3-scale · SVG', 'RigCapacityOutlook', 'new', 'Legacy utilization is derived after sequencing'),
    ]},
    { id: 'constraints-milestones', name: 'Constraints & Milestones', purpose: 'Define campaign-wide dates, interfaces and readiness constraints.', software: 'Primavera P6-lite', output: 'CampaignConstraintSet', legacyStrength: 'Legacy has RFSU milestones, schedule window and basis/non-FID markers.', legacyGap: 'Milestones are derived defaults; no constraint calendar, ownership, logic ties or downstream impact analysis.', widgets: [
      widget('Constraint calendar', 'Capture weather, permits, facilities, shutdown and logistics windows.', 'Client calendars · user constraints', 'Calendar heatmap + timeline bands', 'd3-scale · SVG', 'CampaignConstraintCalendar', 'client-gated', 'Legacy time-axis bands'),
      widget('Milestone network', 'Link RFD, spud, TD, completion and RFSU milestones.', 'Client milestones · dependency register', 'Milestone network + critical path', 'd3-shape · SVG', 'MilestoneNetwork', 'new', 'Legacy MilestonesView is a flat derived list'),
      widget('Readiness risk', 'Expose milestone probability and owner/action status.', 'Readiness evidence · duration uncertainty', 'Risk matrix + confidence bands', 'React · d3-scale', 'MilestoneRiskPanel', 'new', 'Legacy has basis dots but no action workflow'),
    ]},
  ]},
  { id: 'integrated-schedule', name: 'Integrated Scheduling', question: 'What is the best executable sequence?', tabs: [
    { id: 'rig-sequence', name: 'Rig-by-Time Sequence', purpose: 'Construct the integrated rig schedule from approved wells, constraints and capacity.', software: 'Primavera P6 scheduling-lite', output: 'IntegratedDrillingSchedule', legacyStrength: 'Legacy rig-swimlane Gantt, time slider and bar geometry are polished and reusable.', legacyGap: 'Sequence uses deterministic seeded order; no constraint solver, drag persistence, critical path or client import.', widgets: [
      widget('Rig swimlane Gantt', 'Place and move wells across rigs and time.', 'SchedulableWellSet · rig capacity · constraints', 'Interactive rig Gantt', 'SVG · d3-scale', 'RigSequenceGantt', 'reuse', 'Legacy DrillingGantt + TimeSlider'),
      widget('Sequence inspector', 'Explain predecessors, readiness, duration and basis for a selected bar.', 'Integrated schedule records', 'Context inspector + logic table', 'React · CSS Grid', 'SequenceInspector', 'adapt', 'Legacy LiveRail well inspector'),
      widget('Schedule health', 'Detect conflicts, gaps, over-allocation and late milestones.', 'Current schedule · constraint set', 'Exception ribbon + conflict matrix', 'd3-array · React', 'ScheduleHealthPanel', 'new', 'Legacy cross-filtering does not validate logic'),
    ]},
    { id: 'campaign-utilization', name: 'Campaign Gantt & Utilization', purpose: 'Assess campaign efficiency, rig occupancy and move/idle exposure.', software: 'Primavera P6 resource analysis-lite', output: 'CampaignUtilization', legacyStrength: 'Legacy computes utilization, campaigns, activity counts and time-window KPIs.', legacyGap: 'No move model, cost-of-idle, resource leveling or uncertainty envelope.', widgets: [
      widget('Utilization profile', 'Show busy, move, maintenance and idle time by rig.', 'Integrated schedule · client rig states', 'Stacked utilization timeline', 'd3-scale · SVG', 'RigUtilizationProfile', 'adapt', 'Legacy rigUtilization/KpiRibbon'),
      widget('Move & idle analysis', 'Quantify move durations, gaps and avoidable idle cost.', 'Schedule transitions · client move/cost assumptions', 'Waterfall + transition matrix', 'd3-array · SVG', 'MoveIdleAnalysis', 'new', 'Legacy inserts fixed 6–14 day gaps'),
      widget('Campaign KPIs', 'Summarize wells, rig days, delivery dates and capacity margin.', 'Schedule selectors', 'KPI ribbon + sparklines', 'React · SVG', 'CampaignKpiRibbon', 'reuse', 'Legacy KpiRibbon'),
    ]},
    { id: 'schedule-scenarios', name: 'Scenarios, Conflicts & Revisions', purpose: 'Compare alternatives and preserve every approved schedule revision.', software: 'Primavera P6 what-if planning-lite', output: 'ScheduleScenarioSet', legacyStrength: 'Legacy has named snapshots and well-level add/remove/move diffs.', legacyGap: 'Revisions are localStorage-only; no branching cases, drivers, approval or multi-metric scenario comparison.', widgets: [
      widget('Scenario manager', 'Clone and compare schedule alternatives without overwrite.', 'Integrated schedule versions', 'Scenario cards + comparison table', 'React · Zustand', 'ScheduleScenarioManager', 'new', 'Legacy schedule-store snapshots'),
      widget('Conflict resolver', 'Surface resource/date conflicts and test resolutions.', 'Scenario constraints · schedule health', 'Conflict graph + recommendation panel', 'd3-shape · React', 'ScheduleConflictResolver', 'new', 'No Legacy constraint-resolution engine'),
      widget('Revision diff', 'Explain wells added, removed, moved and duration changes.', 'Approved revisions', 'Git-like diff table + timeline overlay', 'SVG · React', 'ScheduleRevisionDiff', 'reuse', 'Legacy RevisionsView/diff'),
    ]},
  ]},
  { id: 'execution-control', name: 'Execution Control', question: 'How do we protect and improve the plan?', tabs: [
    { id: 'lookahead', name: 'Operational Look-Ahead', purpose: 'Create a rolling near-term view of activities, readiness and handoffs.', software: 'Primavera P6 · WellView-lite', output: 'OperationalLookAhead', legacyStrength: 'Legacy window slider and operations rail provide a strong time-focused cockpit.', legacyGap: 'No live client progress, look-ahead horizon, readiness owners or daily/weekly granularity.', widgets: [
      widget('Look-ahead timeline', 'Show the next 2/6/12 weeks by rig and critical interface.', 'Client schedule updates · readiness actions', 'Rolling Gantt', 'SVG · d3-scale', 'OperationalLookAheadGantt', 'client-gated', 'Legacy TimeSlider + Gantt'),
      widget('Readiness board', 'Track materials, services, permits and handover blockers.', 'Client action/readiness records', 'Kanban/RAG matrix', 'React · CSS Grid', 'LookAheadReadinessBoard', 'client-gated', 'No equivalent Legacy workflow'),
      widget('Upcoming decisions', 'Prioritize schedule decisions by time and consequence.', 'Milestones · conflicts · action owners', 'Decision queue + countdown', 'React · d3-array', 'UpcomingDecisionQueue', 'new', 'Legacy OperationsRail milestones'),
    ]},
    { id: 'progress-resequence', name: 'Progress, Deviations & Re-sequencing', purpose: 'Ingest client progress, measure variance and update the forward sequence.', software: 'OpenWells · Primavera P6-lite', output: 'UpdatedDrillingSchedule', legacyStrength: 'Legacy can visualize schedule bars and compare revisions.', legacyGap: 'No actual-progress ingestion, earned schedule, variance drivers or controlled forecast update.', widgets: [
      widget('Plan versus actual', 'Compare actual start/progress/duration against baseline.', 'Client DDR/OpenWells progress · approved baseline', 'Baseline/current Gantt overlay', 'SVG · d3-scale', 'DrillingProgressViewer', 'client-gated', 'Legacy schedule is scenario only'),
      widget('Variance analysis', 'Explain delay by NPT, logistics, weather and readiness causes.', 'Client progress/NPT codes', 'Variance waterfall + Pareto', 'd3-array · SVG', 'DrillingVarianceAnalysis', 'client-gated', 'No Legacy actual-data path'),
      widget('Controlled re-sequence', 'Preview downstream impacts before approving a change.', 'Current progress · remaining schedule · constraints', 'Impact network + before/after timeline', 'd3-shape · SVG', 'ControlledResequence', 'new', 'Legacy revisions diff after change only'),
    ]},
    { id: 'campaign-learning', name: 'Campaign Closeout & Learning', purpose: 'Convert actual campaign performance into duration, cost and planning priors.', software: 'WellView · OpenWells-lite', output: 'CampaignLearningPack', legacyStrength: 'Legacy has post-well review dates, revision history and Well Delivery debrief linkage.', legacyGap: 'No actual performance dataset, normalized lessons, benchmark update or feedback into future duration models.', widgets: [
      widget('Campaign performance', 'Benchmark days, cost, NPT and delivery reliability by well/rig.', 'Client closeout data · baseline schedule', 'Benchmark matrix + control chart', 'd3-scale · SVG', 'CampaignPerformanceDashboard', 'client-gated', 'Legacy PM tracker is date-based only'),
      widget('Learning register', 'Normalize lessons, causes, actions and applicability.', 'Client post-well reviews · user dispositions', 'Searchable lesson cards + taxonomy', 'React · CSS Grid', 'CampaignLearningRegister', 'client-gated', 'Legacy has no campaign lesson store'),
      widget('Planning-prior update', 'Compare prior versus actual duration/cost distributions.', 'Approved actuals · prior basis', 'Distribution overlay + calibration score', 'd3-array · Canvas', 'PlanningPriorCalibration', 'new', 'Legacy deterministic estimates are not calibrated'),
    ]},
  ]},
];
