import { widget, type WorkflowGroup } from '../workspace-blueprint/types';

export const EXPLORATION_WORKFLOWS: WorkflowGroup[] = [
  { id: 'basin-intelligence', name: 'Basin Intelligence', question: 'Where should we focus?', tabs: [
    { id: 'atlas-benchmark', name: 'Atlas & Benchmark', purpose: 'Compare the selected province or basin against the global petroleum catalogue without requiring seismic or wells.', software: 'WoodMac Lens · S&P EDIN · Rystad UCube-lite', output: 'BasinBenchmark', legacyStrength: 'Legacy Basemap already proves interactive spatial scope and sourced overlays.', legacyGap: 'Volve-local framing, no global benchmark cohort or governed comparison artifact.', widgets: [
      widget('Global basin position', 'Locate and compare the selected basin in its global peer set.', 'OSDU catalogue · USGS provinces/AUs · GOGET fields', '2D choropleth + ranked peers', 'MapLibre GL · deck.gl', 'BasinBenchmarkMap', 'adapt', 'Legacy Basemap canvas and cockpit spatial index'),
      widget('Basin scorecard', 'Summarize discovered fields, maturity, resource class and catalogue coverage.', 'Public regulator/USGS facts · ATLAS aggregates', 'KPI matrix + percentile bars', 'React · d3-scale', 'BasinScorecard', 'new', 'Legacy Overview KPI language'),
      widget('Peer-basin comparator', 'Explain why each analogue basin was selected.', 'Cycle-signature analogue engine · Knowledge Bank', 'Similarity table + radar glyphs', 'd3-array · SVG', 'BasinPeerComparator', 'reuse', 'engine/analog.ts; no equivalent integrated viewer'),
    ]},
    { id: 'basin-framework', name: 'Basin Framework', purpose: 'Build a map- and chronology-based tectonostratigraphic framework from public and interpreted knowledge.', software: 'Neftex · ArcGIS Pro-lite', output: 'BasinFramework', legacyStrength: 'Legacy has a strong stratigraphic column and formation evidence cards.', legacyGap: 'Framework is static and Volve-specific; no basin-cycle hierarchy, chronology or versioned interpretation.', widgets: [
      widget('Tectonic cycle column', 'Organize basin evolution into cycle families and stages.', 'Knowledge Bank canon · public basin literature', 'Interactive chronostratigraphic column', 'd3-scale · SVG', 'TectonicCycleColumn', 'adapt', 'Legacy Overview stratigraphic column'),
      widget('Framework map', 'Display province, AU, play and field relationships without seismic interpretation.', 'USGS polygons · OSDU spatial spine · user annotations', 'Layered 2D GIS map', 'MapLibre GL · deck.gl', 'BasinFrameworkMap', 'adapt', 'Legacy Basemap; seismic layers excluded'),
      widget('Framework evidence', 'Track citations, assumptions and interpretation maturity.', 'Knowledge graph · source manifests · user notes', 'Evidence matrix + lineage graph', 'React · SVG', 'FrameworkEvidencePanel', 'new', 'Legacy citations exist but are not a versioned framework artifact'),
    ]},
    { id: 'basin-analogs', name: 'Basin Analog Library', purpose: 'Find explainable basin and play analogues using cycle signature rather than hidden similarity.', software: 'C&C Reservoirs · Neftex analogue workflow-lite', output: 'BasinAnalogSet', legacyStrength: 'The deterministic analog scorer is truth-locked with calibrated P10–P90 coverage.', legacyGap: 'Legacy exposes field analogs late in the workflow and does not curate reusable basin/play cohorts.', widgets: [
      widget('Analogue finder', 'Rank basins by geodynamic context, cycle, fill, climate and lithology.', 'Knowledge Bank cycle signatures · public catalogue', 'Ranked cards + similarity decomposition', 'd3-array · React', 'BasinAnalogFinder', 'reuse', 'engine/analog.ts and basin-cycle concept'),
      widget('Analogue world map', 'Show where selected analogues occur and how far evidence travels.', 'Selected analogue records · OSDU spatial index', 'Linked world map', 'MapLibre GL · deck.gl', 'BasinAnalogMap', 'new', 'No Legacy global analogue map'),
      widget('Prior library', 'Inspect property/risk priors and their citations before reuse.', 'Versioned Knowledge Bank methods and distributions', 'Distribution cards + provenance table', 'd3-scale · SVG', 'AnalogPriorLibrary', 'adapt', 'Legacy Risk and Volumetrics distributions'),
    ]},
  ]},
  { id: 'petroleum-system', name: 'Petroleum-System Screening', question: 'Can a working play exist?', tabs: [
    { id: 'strat-depositional', name: 'Stratigraphy & Depositional Systems', purpose: 'Describe source, reservoir and seal intervals from public knowledge and analogues; no well or seismic data assumed.', software: 'Neftex-lite', output: 'StratigraphicFramework', legacyStrength: 'Legacy includes formation ages, petroleum-system roles and evidence citations.', legacyGap: 'Hard-coded regional story; no editable, reusable interval model or uncertainty range.', widgets: [
      widget('Petroleum-system column', 'Assign source, reservoir, seal and overburden roles through time.', 'Public stratigraphy · Knowledge Bank canon · user interpretation', 'Role-coded stratigraphic column', 'd3-scale · SVG', 'PetroleumSystemColumn', 'adapt', 'Legacy Overview stratigraphic column'),
      widget('Depositional-system matrix', 'Compare expected facies and reservoir presence by cycle.', 'Cycle-family templates · basin analogues', 'Chronology × environment heatmap', 'd3-scale · Canvas', 'DepositionalSystemMatrix', 'new', 'Legacy GDE concepts are not generalized'),
      widget('Interval evidence ledger', 'Separate public reference, analogue prior and user interpretation.', 'Citation graph · artifact lineage', 'Evidence table with nature badges', 'React · CSS Grid', 'IntervalEvidenceLedger', 'adapt', 'Legacy citations and NatureBadge pattern'),
    ]},
    { id: 'basin-model', name: 'Basin Model', purpose: 'Run transparent screening-grade burial, maturity and generation timing from user/public inputs.', software: 'PetroMod · ZetaWare Trinity-lite', output: 'BasinModelCase', legacyStrength: 'Concept and deterministic engine plan define 1D decompaction, EasyRo and generation timing.', legacyGap: 'No live case manager, input editor, calibration record or map-level result viewer.', widgets: [
      widget('1D burial model', 'Edit ages, thickness, erosion and heat-flow assumptions.', 'Public stratigraphy · analogue priors · user inputs', 'Burial/temperature/maturity tracks', 'd3-scale · d3-shape · SVG', 'BurialModel1D', 'new', 'Basin-modeling plan; no Legacy live viewer'),
      widget('Maturity & generation timing', 'Show transformation and charge-window overlap.', 'Deterministic basin engine outputs', 'Multi-track line chart + event bands', 'd3-shape · SVG', 'GenerationTimingChart', 'new', 'Legacy petroleum-system evidence is qualitative'),
      widget('Basin-model cases', 'Clone, compare and truth-label alternative assumptions.', 'Versioned user cases · engine manifests', 'Case table + delta panel', 'React · Zustand', 'BasinModelCaseManager', 'new', 'Legacy has no case/version model'),
    ]},
    { id: 'play-fairway', name: 'Play Fairway & CRS', purpose: 'Combine charge, reservoir, seal and trap evidence into an auditable common-risk screen.', software: 'GeoX · Play Chance Mapping-lite', output: 'PlayFairwayAssessment', legacyStrength: 'Legacy has five-factor GCoS, evidence text and deterministic risk multiplication.', legacyGap: 'Risk is prospect-centric and Volve-seeded; no basin-wide common-risk layer or calibration workflow.', widgets: [
      widget('Common-risk map', 'Map charge, reservoir and seal chance using user/public polygons.', 'Play polygons · basin-model outputs · analogue priors', 'Layered probability map', 'MapLibre GL · deck.gl', 'CommonRiskMap', 'adapt', 'Legacy Risk factors; no generalized map'),
      widget('Chance-factor editor', 'Expose every factor, source and override.', 'Play evidence · user judgement · Knowledge Bank priors', 'Factor matrix + probability sliders', 'React · Zustand', 'ChanceFactorEditor', 'reuse', 'engine/explore.ts GCoS core'),
      widget('Play calibration', 'Compare predicted chance with analogue outcomes.', 'Global field outcomes · selected analogue cohort', 'Reliability plot + calibration table', 'd3-scale · SVG', 'PlayCalibrationPanel', 'new', 'Legacy has no play-level calibration'),
    ]},
  ]},
  { id: 'opportunity', name: 'Opportunity Evaluation', question: 'What should we mature?', tabs: [
    { id: 'prospect-register', name: 'Prospect Register', purpose: 'Maintain user-defined opportunities and their evidence without requiring seismic interpretation.', software: 'GeoX opportunity register-lite', output: 'OpportunitySet', legacyStrength: 'Legacy has selectable prospect cards, status, polygons and decision framing.', legacyGap: 'Prospects are seeded constants; no import/user-authoring, ownership, versioning or multi-basin register.', widgets: [
      widget('Opportunity inventory', 'Create, filter and mature prospects or leads.', 'User-entered records · public discoveries · client polygons when supplied', 'Filterable register', 'React · CSS Grid', 'OpportunityRegister', 'adapt', 'Legacy Plays & Prospects cards'),
      widget('Opportunity map', 'Display user-defined geometry and play context.', 'User/client polygons · OSDU basemap', '2D map + selection linking', 'MapLibre GL · deck.gl', 'OpportunityMap', 'adapt', 'Legacy Basemap and prospect rings'),
      widget('Maturity gate', 'Track lead → prospect → drill/drop evidence requirements.', 'Opportunity artifact states · approval record', 'Stage gate + checklist', 'React · Zustand', 'OpportunityGateTracker', 'new', 'Legacy state is not persisted as governed decisions'),
    ]},
    { id: 'volumetrics-risk', name: 'Volumetrics & Risk', purpose: 'Calculate transparent deterministic and probabilistic resources from user geometry and cited priors.', software: 'GeoX · Oracle Crystal Ball-lite', output: 'VolumetricCase', legacyStrength: 'Legacy Monte Carlo, percentile convention, GCoS and EMV engines are truth-locked.', legacyGap: 'Inputs are Volve/prospect seeds; no reusable case object, dependency/correlation handling or client import gate.', widgets: [
      widget('Volumetric input deck', 'Edit area, thickness, NTG, porosity, saturation, FVF and recovery ranges.', 'User geometry · analogue priors · client inputs when supplied', 'P90/P50/P10 parameter table', 'React · Zustand', 'VolumetricInputDeck', 'reuse', 'Legacy Volumetrics controls + engine/mc.ts'),
      widget('Resource distributions', 'Compare unrisked, recoverable and risked distributions.', 'Deterministic Monte Carlo engine', 'Histogram + CDF + percentile markers', 'd3-array · d3-scale · Canvas', 'ResourceDistributionViewer', 'reuse', 'Legacy Volumetrics distribution viewer'),
      widget('Risk and value bridge', 'Connect chance factors to EMV and decision threshold.', 'GCoS artifact · cost/value assumptions', 'Decision tree + EMV tornado', 'd3-shape · SVG', 'RiskValueBridge', 'adapt', 'Legacy Risk & Uncertainty and EMV logic'),
    ]},
    { id: 'portfolio-ranking', name: 'Portfolio Ranking', purpose: 'Rank opportunities under value, risk, evidence maturity and capital constraints.', software: 'GeoX · Merak Peep-lite', output: 'ExplorationPortfolio', legacyStrength: 'Legacy ranks a small prospect set using deterministic EMV.', legacyGap: 'No portfolio constraints, dependency handling, scenario comparison or approval record.', widgets: [
      widget('Opportunity ranking', 'Sort by EMV, risked volume, maturity and confidence.', 'OpportunitySet · VolumetricCase · GCoS', 'Bubble chart + ranked table', 'd3-scale · SVG', 'OpportunityRanking', 'adapt', 'Legacy Overview/Prospect ranking'),
      widget('Portfolio scenarios', 'Compare capital-limited combinations and drill sequences.', 'Costs · dependencies · user capital envelope', 'Efficient-frontier scatter + scenario cards', 'd3-array · SVG', 'ExplorationPortfolioScenarios', 'new', 'No Legacy portfolio optimizer'),
      widget('Drill/drop record', 'Capture recommendation, evidence and approver.', 'Selected portfolio · artifact lineage', 'Decision memo panel', 'React · CSS Grid', 'DrillDropDecisionRecord', 'new', 'Legacy recommendations are not immutable artifacts'),
    ]},
  ]},
];
