// The Exploration workspace: 3 groups × 3 tabs × 3 widgets.
//
// Each widget carries TWO data-source strings on purpose. `dataSource` is what the
// concept doc planned; `dataSourceActual` is what resolves on disk today, audited
// file by file with record counts. Where the two disagree, `remark` says so on the
// card rather than in a footnote — a card that quietly under-delivers is worse than
// one that declares its gap.
//
// Provenance grades are the WORST input, never the best. `n` is always printed.
// See docs/arganta-energy/EXPLORATION-CANVAS-SPEC.md for the full audit.
import { Flame, Globe2, Layers, Library, ListTree, Map, Sigma, Trophy, Waves } from 'lucide-react';
import { widget, type WorkflowGroup } from '../workspace-blueprint/types';

export const EXPLORATION_WORKFLOWS: WorkflowGroup[] = [
  { id: 'basin-intelligence', name: 'Basin Intelligence', short: 'Basin', question: 'Where should we focus?', tabs: [
    { id: 'atlas-benchmark', name: 'Atlas & Benchmark', short: 'Atlas', blurb: 'World catalogue and benchmarks', icon: Globe2, purpose: 'Compare the selected province or basin against the global petroleum catalogue without requiring seismic or wells.', software: 'WoodMac Lens · S&P EDIN · Rystad UCube-lite', output: 'BasinBenchmark', legacyStrength: 'Legacy Basemap already proves interactive spatial scope and sourced overlays.', legacyGap: 'Volve-local framing, no global benchmark cohort or governed comparison artifact.', widgets: [
      widget('Global basin position', 'Locate and compare the selected basin in its global peer set.', 'OSDU catalogue · USGS provinces/AUs · GOGET fields', 'Choropleth + log-sized field scatter, hover card, click-to-pin', 'maplibre-gl · @deck.gl/layers (GeoJsonLayer, ScatterplotLayer)', 'BasinBenchmarkMap', 'adapt', 'Legacy Basemap canvas and cockpit spatial index',
        { dataSourceActual: 'world/provinces.geojson 179 polygons (boeMean) · osdu/cockpit-points.geojson 7,787 field points · cockpit-reserve-towers 3,861 MMBOE', provenance: 'SOURCED', n: 7787, hero: true }),
      widget('Basin scorecard', 'Summarize discovered fields, maturity, resource class and catalogue coverage.', 'Public regulator/USGS facts · ATLAS aggregates', 'Six percentile bars — the global distribution is the track, the basin is the marker', 'd3-scale · d3-array (quantile) · d3-format', 'BasinScorecard', 'new', 'Legacy Overview KPI language',
        { dataSourceActual: 'spine.province 179 (oilMean, gasMean) · scope-fields.provinces · reserve-towers', provenance: 'DERIVED', n: 179, remark: 'USGS gives a MEAN only — no F95/F50/F5 — so the bars show position, not spread. Gap G1.' }),
      widget('Peer-basin comparator', 'Explain why each analogue basin was selected.', 'Cycle-signature analogue engine · Knowledge Bank', 'Ranked table with a stacked per-axis similarity bar per row', 'd3-array · d3-scale · SVG', 'BasinPeerComparator', 'reuse', 'engine/analog.ts; no equivalent integrated viewer',
        { dataSourceActual: '9-axis signature over spine.basin 179 + basinCycle 630 + psElement 1,544', provenance: 'RECALLED', n: 179, remark: 'Similarity inherits the recalled-cycle grade; the cohort chip shows the worst input.' }),
    ]},
    { id: 'basin-framework', name: 'Basin Framework', short: 'Framework', blurb: 'Basin architecture and cycles', icon: Layers, purpose: 'Build a map- and chronology-based tectonostratigraphic framework from public and interpreted knowledge.', software: 'Neftex · ArcGIS Pro-lite', output: 'BasinFramework', legacyStrength: 'Legacy has a strong stratigraphic column and formation evidence cards.', legacyGap: 'Framework is static and Volve-specific; no basin-cycle hierarchy, chronology or versioned interpretation.', widgets: [
      widget('Tectonic cycle column', 'Organize basin evolution into cycle families and stages.', 'Knowledge Bank canon · public basin literature', 'Chronostratigraphic column on a TIME axis; fill = geodynamics, hatch = lithology, opacity = confidence. Compare mode puts N columns on one shared axis.', 'd3-scale · d3-axis · d3-shape · SVG', 'TectonicCycleColumn', 'adapt', 'Legacy Overview stratigraphic column',
        { dataSourceActual: 'spine.basinCycle 630 across all 179 basins · spine.geologicTimescale 12 (ICS 2026/06)', provenance: 'RECALLED', n: 630, remark: 'Two gaps. (a) 626 of 630 cycles are literature-recalled — only 4 are interpreted. (b) No thickness exists anywhere, so this is TIME-scaled, not depth-scaled. Gaps G9, G5.', hero: true }),
      widget('Framework map', 'Display province, AU, play and field relationships without seismic interpretation.', 'USGS polygons · OSDU spatial spine · user annotations', 'Layered 2D GIS: province fill, AU membership by point colour, no seismic', 'maplibre-gl · @deck.gl/layers', 'BasinFrameworkMap', 'adapt', 'Legacy Basemap; seismic layers excluded',
        { dataSourceActual: 'world/provinces.geojson 179 · scope-fields.assessmentUnits 339 · field points', provenance: 'SOURCED', n: 339, remark: 'Assessment units have NO geometry — membership is shown by point colour, not polygon. Gap G2.' }),
      widget('Framework evidence', 'Track citations, assumptions and interpretation maturity.', 'Knowledge graph · source manifests · user notes', 'Ranked completion bars coloured by stage; each row expands to its gap and next action', 'd3-scale · d3-array · CSS Grid', 'FrameworkEvidencePanel', 'new', 'Legacy citations exist but are not a versioned framework artifact',
        { dataSourceActual: 'spine.basinCompletion 179 (completion_pct, primary_gap, next_action) · basinCompletionRule 7 · citation 69', provenance: 'SOURCED', n: 179 }),
    ]},
    { id: 'basin-analogs', name: 'Basin Analog Library', short: 'Analogs', blurb: 'Analog basin library', icon: Library, purpose: 'Find explainable basin and play analogues using cycle signature rather than hidden similarity.', software: 'C&C Reservoirs · Neftex analogue workflow-lite', output: 'BasinAnalogSet', legacyStrength: 'The deterministic analog scorer is truth-locked with calibrated P10–P90 coverage.', legacyGap: 'Legacy exposes field analogs late in the workflow and does not curate reusable basin/play cohorts.', widgets: [
      widget('Analogue finder', 'Rank basins by geodynamic context, cycle, fill, climate and lithology.', 'Knowledge Bank cycle signatures · public catalogue', 'Ranked cards; similarity is a stacked per-axis contribution bar. Click a segment to re-rank on that axis alone.', 'd3-array · d3-scale · SVG', 'BasinAnalogFinder', 'reuse', 'engine/analog.ts and basin-cycle concept',
        { dataSourceActual: '9-axis signature: geodynamic sequence · setting · fill · lithology · age span · PS role profile · charge-timing shape · endowment decile · realisation', provenance: 'RECALLED', n: 179, hero: true }),
      widget('Analogue world map', 'Show where selected analogues occur and how far evidence travels.', 'Selected analogue records · OSDU spatial index', 'Great-circle arcs from the pinned basin, weighted by similarity', 'maplibre-gl · @deck.gl/layers (ArcLayer)', 'BasinAnalogMap', 'new', 'No Legacy global analogue map',
        { dataSourceActual: 'selected cohort + province centroids from world/provinces.geojson', provenance: 'DERIVED', n: 179 }),
      widget('Prior library', 'Inspect property/risk priors and their citations before reuse.', 'Versioned Knowledge Bank methods and distributions', 'Distribution cards (histogram + fitted lognormal) + provenance table + "use as prior" handoff', 'd3-array (bin, quantile) · d3-scale · d3-shape', 'AnalogPriorLibrary', 'adapt', 'Legacy Risk and Volumetrics distributions',
        { dataSourceActual: 'cohort-pooled: reserve-towers field sizes · field-detail.discoveryYear 5,172 · offshore share · role mix', provenance: 'DERIVED', n: 3861, remark: 'Priors are empirical from DISCOVERED fields, so they are biased toward what has already been found.' }),
    ]},
  ]},
  { id: 'petroleum-system', name: 'Petroleum-System Screening', short: 'System', question: 'Can a working play exist?', tabs: [
    { id: 'strat-depositional', name: 'Stratigraphy & Depositional Systems', short: 'Stratigraphy', blurb: 'Sequences and depositional systems', icon: Waves, purpose: 'Describe source, reservoir and seal intervals from public knowledge and analogues; no well or seismic data assumed.', software: 'Neftex-lite', output: 'StratigraphicFramework', legacyStrength: 'Legacy includes formation ages, petroleum-system roles and evidence citations.', legacyGap: 'Hard-coded regional story; no editable, reusable interval model or uncertainty range.', widgets: [
      widget('Petroleum-system column', 'Assign source, reservoir, seal and overburden roles through time.', 'Public stratigraphy · Knowledge Bank canon · user interpretation', 'Role-coded column on the ICS axis, rendered as a second lane beside the cycle column — what the basin did ‖ what it made', 'd3-scale · d3-axis · d3-shape · SVG', 'PetroleumSystemColumn', 'adapt', 'Legacy Overview stratigraphic column',
        { dataSourceActual: 'spine.psElement 1,544 across all 212 models — source 457 · reservoir 591 · seal 281 · overburden 215', provenance: 'RECALLED', n: 1544, remark: 'effectiveness is mostly not-assessed — rendered as hatch, never as a filled claim.', hero: true }),
      widget('Depositional-system matrix', 'Compare expected facies and reservoir presence by cycle.', 'Cycle-family templates · basin analogues', 'Chronology × environment heatmap; cell value = cycle count, hue = dominant role', 'd3-scale (scaleSequential) · d3-array (rollup) · Canvas', 'DepositionalSystemMatrix', 'new', 'Legacy GDE concepts are not generalized',
        { dataSourceActual: 'basinCycle fill/lithology/proximity/climate × geologicTimescale 12 periods', provenance: 'RECALLED', n: 630, remark: 'A COUNT heatmap, not a mapped facies area — the legend must say so.' }),
      widget('Interval evidence ledger', 'Separate public reference, analogue prior and user interpretation.', 'Citation graph · artifact lineage', 'Evidence table with nature badges, expanding to the authority sentence', 'React · CSS Grid', 'IntervalEvidenceLedger', 'adapt', 'Legacy citations and NatureBadge pattern',
        { dataSourceActual: 'formation 618 · petroleumSystem.essential_elements_note 211 narratives · USGS AU Evidence 272 · citation 69', provenance: 'SOURCED', n: 618 }),
    ]},
    { id: 'basin-model', name: 'Charge Timing', short: 'Charge', blurb: 'Generation, migration, critical moment', icon: Flame, purpose: 'Establish when the system charged and whether the trap was there in time — from evidence-timed events, not from an uncalibrated burial model.', software: 'PetroMod · ZetaWare Trinity-lite', output: 'ChargeTimingCase', legacyStrength: 'Concept and deterministic engine plan define 1D decompaction, EasyRo and generation timing.', legacyGap: 'No thickness, heat flow or calibration point exists outside Volve, so the burial half cannot be auto-populated — only the event-timing half is real today.', widgets: [
      widget('Petroleum-system events chart', 'Show element and process timing against the critical moment.', 'Deterministic basin engine outputs', 'Magoon–Dow chart: element bars above, process bars below, critical moment as a vertical marker; certainty → bar texture', 'd3-scale · d3-axis · d3-shape · SVG', 'GenerationTimingChart', 'new', 'Legacy petroleum-system evidence is qualitative',
        { dataSourceActual: 'spine.psEvent 1,484 — a COMPLETE 7 × 212 grid (generation, expulsion, migration, accumulation, trap-formation, preservation, critical-moment) + psElement bars', provenance: 'SOURCED', n: 1484, hero: true }),
      widget('1D burial model', 'Edit ages, thickness, erosion and heat-flow assumptions.', 'Public stratigraphy · analogue priors · user inputs', 'Burial / temperature / maturity tracks over an editable layer grid', 'd3-scale · d3-shape · SVG · zustand', 'BurialModel1D', 'client-gated', 'Basin-modeling plan; no Legacy live viewer',
        { dataSourceActual: 'NONE — user-typed layer table, seeded by analogue priors', provenance: 'USER', n: 0, remark: 'BLOCKED as an auto-populated chart. Needs present-day depth, thickness, erosion, heat flow and one calibration point (vitrinite/Tmax/corrected BHT) — we hold none outside Volve. Ships as a sandbox badged uncalibrated. Gaps G5, G6.' }),
      widget('Timing-risk readout', 'Test whether the trap existed before peak generation.', 'Versioned user cases · engine manifests', 'Interval-overlap diagram, one row per system, plus the case/completion ledger', 'd3-scale · React · zustand', 'BasinModelCaseManager', 'new', 'Legacy has no case/version model',
        { dataSourceActual: 'derived from psEvent trap-formation vs generation intervals · psChartCompletion 212 (chart_row_completion_pct, next_gap)', provenance: 'DERIVED', n: 212, remark: 'This boolean IS the timing chance factor consumed by Play Fairway.' }),
    ]},
    { id: 'play-fairway', name: 'Play Fairway & CRS', short: 'Play fairway', blurb: 'Common risk and calibration', icon: Map, purpose: 'Combine charge, reservoir, seal and trap evidence into an auditable common-risk screen.', software: 'GeoX · Play Chance Mapping-lite', output: 'PlayFairwayAssessment', legacyStrength: 'Legacy has five-factor GCoS, evidence text and deterministic risk multiplication.', legacyGap: 'Risk is prospect-centric and Volve-seeded; no basin-wide common-risk layer or calibration workflow.', widgets: [
      widget('Common-risk matrix', 'Score charge, reservoir, seal, trap and timing from the evidence we actually hold.', 'Play polygons · basin-model outputs · analogue priors', 'System × 5-factor matrix; cell = evidence grade, not a fake probability. Click → the authority sentence and citation.', 'd3-scale · CSS Grid · SVG', 'CommonRiskMap', 'adapt', 'Legacy Risk factors; no generalized map',
        { dataSourceActual: 'derived per TPS from psElement role counts + psEvent certainty + essential_elements_note parse + the timing overlap test', provenance: 'DERIVED', n: 212, remark: 'A GRIDDED fairway map is not possible: AUs have no geometry and the Play tab holds 1 row. A province-resolution "fairway" would be a lie with a legend. Gaps G2, G4.', hero: true }),
      widget('Chance-factor editor', 'Expose every factor, source and override.', 'Play evidence · user judgement · Knowledge Bank priors', 'Factor matrix + probability sliders; the override is written as a separate layer, never over the evidence', 'React · zustand', 'ChanceFactorEditor', 'reuse', 'engine/explore.ts GCoS core',
        { dataSourceActual: 'the matrix above + the truth-locked engine/explore.ts GCoS core', provenance: 'USER', n: 212 }),
      widget('Play calibration', 'Compare predicted chance with analogue outcomes.', 'Global field outcomes · selected analogue cohort', 'Reliability plot (binned predicted vs observed) + calibration table with n per bin', 'd3-array (bin) · d3-scale · d3-shape', 'PlayCalibrationPanel', 'new', 'Legacy has no play-level calibration',
        { dataSourceActual: '90 provinces with ≥3 dated discoveries; outcome proxy = discovered Σ MMBOE / (discovered + USGS undiscovered mean)', provenance: 'DERIVED', n: 90, remark: 'The outcome is a PROXY, not a drill-success rate — we have no dry-hole record. Gap G7.' }),
    ]},
  ]},
  { id: 'opportunity', name: 'Opportunity Evaluation', short: 'Opportunity', question: 'What should we mature?', tabs: [
    { id: 'prospect-register', name: 'Prospect Register', short: 'Prospects', blurb: 'Opportunities and leads', icon: ListTree, purpose: 'Maintain user-defined opportunities and their evidence without requiring seismic interpretation.', software: 'GeoX opportunity register-lite', output: 'OpportunitySet', legacyStrength: 'Legacy has selectable prospect cards, status, polygons and decision framing.', legacyGap: 'Prospects are seeded constants; no import/user-authoring, ownership, versioning or multi-basin register.', widgets: [
      widget('Opportunity inventory', 'Create, filter and mature prospects or leads.', 'User-entered records · public discoveries · client polygons when supplied', 'Filterable register, dual-badged, with an inline creaming sparkline per parent basin', 'React · CSS Grid · d3-shape', 'OpportunityRegister', 'adapt', 'Legacy Plays & Prospects cards',
        { dataSourceActual: 'SEEDED: 339 assessmentUnit rows as statistical opportunities (oilMean, gasMean, parent TPS chance) + user rows (currently 2)', provenance: 'SOURCED', n: 339, remark: 'Seeds are badged USGS STATISTICAL · not a mapped prospect, and can never share a legend series with user prospects.', hero: true }),
      widget('Opportunity map', 'Display user-defined geometry and play context.', 'User/client polygons · OSDU basemap', '2D map with selection linked to the register', 'maplibre-gl · @deck.gl/layers', 'OpportunityMap', 'adapt', 'Legacy Basemap and prospect rings',
        { dataSourceActual: 'AU member field points + province polygon', provenance: 'SOURCED', n: 339, remark: 'No AU or prospect geometry exists — points only. Gap G2.' }),
      widget('Maturity gate', 'Track lead → prospect → drill/drop evidence requirements.', 'Opportunity artifact states · approval record', 'Stage gate + evidence checklist, auto-ticked from what actually exists', 'React · zustand', 'OpportunityGateTracker', 'new', 'Legacy state is not persisted as governed decisions',
        { dataSourceActual: 'basinCompletion.primary_gap + psChartCompletion.next_gap + artifact states', provenance: 'DERIVED', n: 179 }),
    ]},
    { id: 'volumetrics-risk', name: 'Volumetrics & Risk', short: 'Volumetrics', blurb: 'Field-size priors and risked volume', icon: Sigma, purpose: 'Calculate transparent deterministic and probabilistic resources from user geometry and cited priors.', software: 'GeoX · Oracle Crystal Ball-lite', output: 'VolumetricCase', legacyStrength: 'Legacy Monte Carlo, percentile convention, GCoS and EMV engines are truth-locked.', legacyGap: 'Inputs are Volve/prospect seeds; no reusable case object, dependency/correlation handling or client import gate.', widgets: [
      widget('Empirical field-size distribution', 'Ground the volumetric prior in measured field sizes rather than an assumed curve.', 'Deterministic Monte Carlo engine', 'Log-x histogram + CDF + P90/P50/P10 markers + fitted lognormal, with the reserve-class mix as a stacked strip beneath', 'd3-array (bin, quantile) · d3-scale (scaleLog) · d3-shape · Canvas', 'ResourceDistributionViewer', 'reuse', 'Legacy Volumetrics distribution viewer',
        { dataSourceActual: 'cockpit-reserve-towers 3,861 fields with real MMBOE (p50 48.7 · p90 1,193 · p99 17,200 · max 557,000)', provenance: 'SOURCED', n: 3861, remark: '170+ distinct reserve-class strings (2P 624 · remaining 1,505 · STOIIP 12 · Cyrillic А+В1+В2+С1). Never pool in-place with recoverable. Gap G3.', hero: true }),
      widget('Volumetric input deck', 'Edit area, thickness, NTG, porosity, saturation, FVF and recovery ranges.', 'User geometry · analogue priors · client inputs when supplied', 'P90/P50/P10 parameter table, each row badged with the origin of its number', 'React · zustand', 'VolumetricInputDeck', 'reuse', 'Legacy Volumetrics controls + engine/mc.ts',
        { dataSourceActual: 'user geometry + analogue priors + field-detail.reserves 4,258 fields', provenance: 'USER', n: 4258, remark: 'Reservoir parameters (φ, Sw, NTG) exist for VOLVE ONLY. Everywhere else they are analogue priors or user input.' }),
      widget('Risk and value bridge', 'Connect chance factors to EMV and decision threshold.', 'GCoS artifact · cost/value assumptions', 'Decision tree + EMV tornado', 'd3-shape · d3-hierarchy (tree) · SVG', 'RiskValueBridge', 'adapt', 'Legacy Risk & Uncertainty and EMV logic',
        { dataSourceActual: 'CRS composite × volume × a single per-region unit-cost slider', provenance: 'USER', n: 0, remark: 'No cost data exists anywhere in the corpus. The slider is badged ASSUMPTION. Gap G8.' }),
    ]},
    { id: 'portfolio-ranking', name: 'Portfolio Ranking', short: 'Ranking', blurb: 'Ranked opportunities and decision', icon: Trophy, purpose: 'Rank opportunities under value, risk, evidence maturity and capital constraints.', software: 'GeoX · Merak Peep-lite', output: 'ExplorationPortfolio', legacyStrength: 'Legacy ranks a small prospect set using deterministic EMV.', legacyGap: 'No portfolio constraints, dependency handling, scenario comparison or approval record.', widgets: [
      widget('Opportunity ranking', 'Sort by EMV, risked volume, maturity and confidence.', 'OpportunitySet · VolumetricCase · GCoS', 'Bubble chart — x = chance, y = resource, size = parent endowment, colour = evidence grade — with median quadrant lines; brush → ranked table', 'd3-scale · d3-array · d3-shape · SVG', 'OpportunityRanking', 'adapt', 'Legacy Overview/Prospect ranking',
        { dataSourceActual: '339 AU seeds + user prospects, joined to the CRS composite and the volumetric P50', provenance: 'DERIVED', n: 339, remark: 'In World scope this is a global exploration-opportunity map in one chart.', hero: true }),
      widget('Portfolio scenarios', 'Compare capital-limited combinations and drill sequences.', 'Costs · dependencies · user capital envelope', 'Efficient-frontier scatter + scenario cards', 'd3-array · d3-scale · SVG', 'ExplorationPortfolioScenarios', 'new', 'No Legacy portfolio optimizer',
        { dataSourceActual: 'ranked set + capital slider + the assumed unit cost', provenance: 'USER', n: 339, remark: 'Costs are assumed, so the frontier is badged SCENARIO. No dependency or correlation data exists — opportunities are treated as independent and the card says so.' }),
      widget('Drill/drop record', 'Capture recommendation, evidence and approver.', 'Selected portfolio · artifact lineage', 'Immutable decision memo capturing scope, pins, facets and the provenance grade of every input', 'React · CSS Grid', 'DrillDropDecisionRecord', 'new', 'Legacy recommendations are not immutable artifacts',
        { dataSourceActual: 'the selected portfolio + the full artifact lineage from stages 1–8', provenance: 'DERIVED', n: 9 }),
    ]},
  ]},
];
