import { BookOpen, CalendarCheck, ClipboardList, Crosshair, FileText, History, Layers, Navigation, Radar } from 'lucide-react';
import { widget, type WorkflowGroup } from '../workspace-blueprint/types';

export const WELLDELIVERY_WORKFLOWS: WorkflowGroup[] = [
  { id: 'define', name: 'Define the Well', short: 'Define', question: 'What must this well achieve?', tabs: [
    { id: 'proposal-intent', name: 'Proposal & Well Intent', short: 'Proposal', blurb: 'Well intent and objectives', icon: FileText, purpose: 'Receive a planned well or client opportunity and define measurable objectives and success criteria.', software: 'SLB DrillPlan-lite', output: 'WellStatementOfRequirements', legacyStrength: 'Legacy Proposal provides an excellent non-scroll well-on-a-page gate cockpit.', legacyGap: 'Candidates are Volve-seeded and localStorage-bound; no client import, shared well identity or versioned SOR.', widgets: [
      widget('Well-on-a-page', 'Summarize objective, target, cost, schedule, risk and maturity.', 'Client well proposal · Field Development planned-well handoff', 'Decision cockpit', 'React · CSS Grid', 'WellProposalCockpit', 'adapt', 'Legacy Proposal'),
      widget('Objective & success criteria', 'Capture why the well exists and how success will be measured.', 'Client SOR · user-authored decisions', 'Structured requirements editor', 'React · Zustand', 'WellIntentEditor', 'new', 'Legacy Basis objective fields'),
      widget('Gate readiness', 'Show evidence completeness against WDP/CVP gates.', 'Artifact checklist · approval record', 'Stage gate + readiness matrix', 'React · SVG', 'WellGateReadiness', 'adapt', 'Legacy GateTrack/GateLocked'),
    ]},
    { id: 'offset-review', name: 'Client Offset Review', short: 'Offsets', blurb: 'Client offset well review', icon: History, purpose: 'Review client-provided offset wells, hazards, performance and lessons.', software: 'Landmark EDM · OpenWells-lite', output: 'OffsetWellBasis', legacyStrength: 'Legacy generates offset lists and uses trajectories in clearance and steering.', legacyGap: 'Offsets are anchored to bundled Volve wells; no client ingest/QC, similarity ranking or lesson provenance.', widgets: [
      widget('Offset selector', 'Rank candidate offsets by geometry, formation, hazard and outcome.', 'Client-provided well headers, trajectories and reports', 'Ranked table + similarity factors', 'd3-array · React', 'OffsetWellSelector', 'client-gated', 'Legacy candidate offsets'),
      widget('Offset comparison', 'Compare depth, duration, casing, mud and NPT by section.', 'Client end-of-well and drilling reports', 'Small-multiple profiles + benchmark bands', 'd3-scale · SVG', 'OffsetComparisonViewer', 'client-gated', 'Legacy Debrief plan-vs-actual patterns'),
      widget('Lessons register', 'Turn offset observations into traceable design requirements.', 'Client lessons · user dispositions', 'Evidence-to-requirement matrix', 'React · CSS Grid', 'OffsetLessonsRegister', 'new', 'Legacy lessons are not linked to design changes'),
    ]},
    { id: 'concept-bod', name: 'Concept & Basis of Design', short: 'Concept', blurb: 'Basis of design', icon: ClipboardList, purpose: 'Select the well concept and freeze the design envelope before detailed engineering.', software: 'SLB DrillPlan-lite', output: 'WellBasisOfDesign', legacyStrength: 'Legacy Basis includes target, envelope, rig sizing, cost and risk controls.', legacyGap: 'No concept alternatives, scored trade-off, immutable BOD revision or explicit requirement traceability.', widgets: [
      widget('Concept options', 'Compare vertical, deviated, horizontal, sidetrack and completion concepts.', 'Well intent · client constraints · analog rules', 'Option cards + decision matrix', 'React · d3-scale', 'WellConceptSelector', 'new', 'Legacy has one generated candidate design'),
      widget('Design envelope', 'Define target, depth, pressure, temperature and operational boundaries.', 'Client subsurface/pressure inputs · selected concept', 'Envelope chart + parameter table', 'd3-shape · SVG', 'WellDesignEnvelope', 'adapt', 'Legacy Basis and mud-window inputs'),
      widget('BOD revision', 'Freeze assumptions, risks and selected concept with approval.', 'Structured decisions · artifact lineage', 'Version diff + sign-off panel', 'React · Zustand', 'WellBodManager', 'new', 'Legacy mutates candidate state in place'),
    ]},
  ]},
  { id: 'design-assure', name: 'Design and Assure', short: 'Design', question: 'Can it be drilled safely?', tabs: [
    { id: 'target-trajectory', name: 'Target & Trajectory', short: 'Trajectory', blurb: 'Targets and well path', icon: Crosshair, purpose: 'Design a simplified trajectory against client targets and surface constraints.', software: 'Landmark COMPASS-lite', output: 'TrajectoryDesign', legacyStrength: 'Legacy has deterministic stations, DLS math, target geometry and trajectory views.', legacyGap: 'Generated arithmetic trajectories, limited survey methods, no client target import or scenario comparison.', widgets: [
      widget('Trajectory editor', 'Edit KOP, build/turn rates, landing point and TD.', 'Client targets/surface location · user constraints', 'Plan/profile interactive plot', 'Canvas · d3-scale', 'TrajectoryDesigner', 'adapt', 'Legacy trajectory-math and candidateStations'),
      widget('Directional KPIs', 'Track MD/TVD, inclination, azimuth, DLS and target miss.', 'Computed trajectory stations', 'KPI strip + depth tracks', 'd3-shape · SVG', 'TrajectoryKpiPanel', 'reuse', 'Legacy trajectory deterministic calculations'),
      widget('Trajectory cases', 'Clone and compare design alternatives.', 'Versioned trajectory scenarios', 'Overlay viewer + delta table', 'React · Zustand', 'TrajectoryCaseComparator', 'new', 'Legacy supports one candidate trajectory'),
    ]},
    { id: 'clearance-operability', name: 'Clearance, Hydraulics & Operability', short: 'Clearance', blurb: 'Anti-collision, hydraulics, operability', icon: Radar, purpose: 'Screen anti-collision, mud window and operational constraints.', software: 'Landmark WELLPLAN · COMPASS-lite', output: 'OperabilityAssessment', legacyStrength: 'Legacy Clearance has mud-window canvas, closest approach and separation factor.', legacyGap: 'Synthetic mud window, simplified ISCWSA, no client surveys/uncertainty or hydraulics model.', widgets: [
      widget('Anti-collision screen', 'Calculate simplified separation against client offsets.', 'Client definitive surveys and uncertainty models', 'Separation-factor track + 3D proximity view', 'Three.js/R3F · d3-scale', 'AntiCollisionViewer', 'client-gated', 'Legacy Clearance + closestApproaches'),
      widget('Mud-window screen', 'Compare pore pressure, collapse, mud and fracture limits.', 'Client PP/FG/geomechanics curves', 'Depth envelope plot', 'd3-shape · SVG', 'MudWindowViewer', 'client-gated', 'Legacy Clearance synthetic envelope'),
      widget('Hydraulics & operability', 'Screen ECD, hole cleaning and rig operating limits.', 'Client fluid/geometry inputs · user operating assumptions', 'Operating envelope + limit table', 'd3-scale · SVG', 'HydraulicsScreen', 'new', 'No Legacy hydraulics engine'),
    ]},
    { id: 'architecture-assurance', name: 'Architecture, Barriers & Assurance', short: 'Architecture', blurb: 'Casing, barriers, assurance', icon: Layers, purpose: 'Define hole sections, casing, completion and barrier verification.', software: 'DrillPlan · NORSOK D-010 workflow-lite', output: 'AssuredWellDesign', legacyStrength: 'Legacy displays casing architecture, barriers, risk register and verification state.', legacyGap: 'Scenario architecture only; no load cases, standards rule engine or evidence-linked assurance actions.', widgets: [
      widget('Well architecture', 'Lay out hole sections, casing seats and completion concept.', 'Selected trajectory · client pressure/formation constraints', 'Depth schematic + section table', 'SVG · React', 'WellArchitectureDesigner', 'adapt', 'Legacy Proposal/Basis casing schematic'),
      widget('Barrier schematic', 'Define primary/secondary envelopes and verification evidence.', 'Client design · NORSOK D-010 method library', 'Dual-envelope schematic', 'SVG', 'BarrierEnvelopeViewer', 'adapt', 'Legacy Clearance barrier diagram'),
      widget('Assurance register', 'Close design risks, actions, deviations and approvals.', 'Risk register · reviews · client evidence', 'Assurance matrix + action aging', 'React · CSS Grid', 'WellAssuranceRegister', 'new', 'Legacy risk list lacks workflow ownership/closure'),
    ]},
  ]},
  { id: 'execute-close', name: 'Execute and Close', short: 'Execute', question: 'Did we deliver and learn?', tabs: [
    { id: 'programme-readiness', name: 'Programme & Readiness', short: 'Programme', blurb: 'Programme and readiness', icon: CalendarCheck, purpose: 'Assemble the drilling programme and verify execution readiness.', software: 'DrillPlan · OpenWells-lite', output: 'ApprovedDrillingProgramme', legacyStrength: 'Legacy proposal/gates cover readiness, cost, duration and top risks.', legacyGap: 'No document assembly, long-lead readiness, responsibility tracking or integrated Drilling handoff.', widgets: [
      widget('Programme outline', 'Assemble design sections, procedures and contingencies.', 'Approved design artifacts · client templates', 'Document tree + completeness meter', 'React · CSS Grid', 'DrillingProgrammeAssembler', 'new', 'Legacy Report links are separate from cockpit'),
      widget('Readiness matrix', 'Track permits, materials, services, rig interfaces and approvals.', 'Client readiness checklist · owners/dates', 'RAG matrix + due-date timeline', 'React · d3-scale', 'ExecutionReadinessMatrix', 'new', 'Legacy gate readiness is coarse'),
      widget('Drilling handoff', 'Publish the sanctioned well and duration basis to campaign planning.', 'Approved programme · P10/P50/P90 duration/cost', 'Handoff contract + validation panel', 'React · Zustand', 'DrillingHandoffPanel', 'adapt', 'Legacy emitToDrillingSequence bridge'),
    ]},
    { id: 'well-steering', name: 'Well Steering', short: 'Steering', blurb: 'Geosteering and execution', icon: Navigation, purpose: 'Compare client real-time trajectory/log feeds with the approved plan during execution.', software: 'ROGII StarSteer-lite', output: 'SteeringDecisionLog', legacyStrength: 'Legacy Steering has a polished TVT section, in-zone KPIs and deterministic synthetic steering model.', legacyGap: 'Synthetic feed, no WITSML/client stream, no decision log, uncertainty cone or approved-plan version link.', widgets: [
      widget('Geosteering section', 'Overlay planned and actual path against client formation interpretation.', 'Client WITSML/LWD feed · approved trajectory', 'TVT cross-section', 'Canvas · d3-scale', 'GeosteeringSection', 'client-gated', 'Legacy Steering'),
      widget('In-zone monitor', 'Track distance to boundaries, GR response and target compliance.', 'Client LWD measurements · steering interpretation', 'Live KPI tracks + alarms', 'SVG · React', 'InZoneMonitor', 'client-gated', 'Legacy Steering KPI rail'),
      widget('Steering decisions', 'Record recommendation, evidence, approver and resulting plan revision.', 'User decisions · trajectory versions', 'Decision timeline + diff', 'React · Zustand', 'SteeringDecisionLog', 'new', 'Legacy steering actions are not persisted'),
    ]},
    { id: 'debrief-handover', name: 'Debrief & Handover', short: 'Debrief', blurb: 'Lessons and handover', icon: BookOpen, purpose: 'Reconcile plan versus actual and deliver client-verified as-built knowledge downstream.', software: 'OpenWells-lite', output: 'FinalWellReport · AsBuiltHandover', legacyStrength: 'Legacy Debrief/Handover covers plan-vs-actual, NPT, casing, barriers and checklist.', legacyGap: 'Actuals are scenario-derived, lessons are not normalized, and downstream handoff has no governed reader.', widgets: [
      widget('Plan versus actual', 'Compare days, cost, depths, tops and section performance.', 'Client daily drilling report · approved programme', 'Variance waterfall + section timeline', 'd3-scale · SVG', 'WellDeliveryVariance', 'client-gated', 'Legacy Debrief'),
      widget('NPT & lessons', 'Classify loss events and connect lessons to future requirements.', 'Client DDR/NPT codes · user lessons', 'Pareto + lessons register', 'd3-array · SVG', 'NptLessonsViewer', 'client-gated', 'Legacy Debrief NPT summary'),
      widget('As-built handover', 'Validate final trajectory, architecture, barriers and deliverables.', 'Client as-built package · verification checklist', 'Package manifest + acceptance gate', 'React · CSS Grid', 'AsBuiltHandover', 'adapt', 'Legacy Handover'),
    ]},
  ]},
];
