// Kingdom data pipeline
// Reads the scraped ATLAS_* globals from the Nexus RPG Prototype folder and emits
// normalized JSON snapshots into apps/kingdom/data/core/, plus mirrors the local
// asset library into apps/kingdom/data/assets/.
//
// Usage: node scripts/build-data.mjs [--skip-assets]
//
// Layering model:
//   data/core/*.json      — immutable scraped source layer (regenerated by this script)
//   data/overrides/*.json — hand/tool-edited tuning layer (never touched here)
// Consumers merge core + overrides at load time.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const KINGDOM = path.resolve(__dirname, '..');
const SRC = 'C:/Users/aldhy/OneDrive/Documents/Baginda\'s App/RPG/Prototype';
const CORE = path.join(KINGDOM, 'data', 'core');
const ASSETS = path.join(KINGDOM, 'data', 'assets');
const skipAssets = process.argv.includes('--skip-assets');

function loadGlobals(file) {
  const w = {};
  new Function('window', fs.readFileSync(path.join(SRC, file), 'utf8'))(w);
  return w;
}

fs.mkdirSync(CORE, { recursive: true });
fs.mkdirSync(path.join(KINGDOM, 'data', 'overrides'), { recursive: true });

console.log('Loading ATLAS_* source files...');
const monstersFile = loadGlobals('app.data.monsters.js');
const itemsFile = loadGlobals('app.data.items.js');
const skillsFile = loadGlobals('app.data.skills.js');
const assetsFile = loadGlobals('app.data.assets.js');
const mapsFile = loadGlobals('app.data.maps.js');
const navFile = loadGlobals('app.data.mapNav.js');
const hierarchyFile = loadGlobals('app.data.mapHierarchy.js');
const metadataFile = loadGlobals('app.data.metadata.js');
const worldSpineFile = loadGlobals('app.data.worldSpine.js');

// Local asset paths in the source data look like "./assets/game-images/..." or
// "./assets/map-images/...". In the kingdom app they live under "data/assets/".
function relocal(p) {
  if (typeof p !== 'string') return p;
  return p.replace(/^\.\/assets\//, 'data/assets/');
}
function deepRelocal(value) {
  if (Array.isArray(value)) return value.map(deepRelocal);
  if (value && typeof value === 'object') {
    const out = {};
    for (const [k, v] of Object.entries(value)) out[k] = deepRelocal(v);
    return out;
  }
  return relocal(value);
}

// --- Maps: merge curated maps (app.data.maps.js) over nav maps (app.data.mapNav.js),
// mirroring what app.core.js mergeMapNavigationData() did at runtime.
const curatedMaps = new Map(mapsFile.ATLAS_MAPS.map((m) => [m.id, m]));
const navMaps = navFile.ATLAS_MAP_NAV.maps || [];
const mapIds = new Set([...curatedMaps.keys(), ...navMaps.map((m) => m.id)]);
const uniq = (a) => [...new Set((a || []).filter(Boolean))];
const navById = new Map(navMaps.map((m) => [m.id, m]));

const maps = [...mapIds].map((id) => {
  const nav = navById.get(id) || {};
  const base = curatedMaps.get(id) || {};
  return deepRelocal({
    ...nav,
    ...base,
    name: base.name || nav.name,
    kind: base.kind || nav.kind,
    mapType: nav.mapType || base.mapType,
    source: { ...(nav.source || {}), ...(base.source || {}) },
    content: { ...(nav.content || {}), ...(base.content || {}) },
    stats: { ...(nav.stats || {}), ...(base.stats || {}) },
    mapImage: nav.mapImage || base.mapImage || null,
    hotspotIds: uniq([...(base.hotspotIds || []), ...(nav.hotspotIds || [])]),
    monsterAppearanceIds: uniq([
      ...(base.monsterAppearanceIds || []),
      ...(nav.monsterAppearanceIds || [])
    ]),
    tags: uniq([...(base.tags || []), ...(nav.tags || [])])
  });
});

// Some curated maps carry monsterAppearanceIds while nav maps don't; also build the
// reverse index from appearances so every map knows its monsters.
const appearances = monstersFile.ATLAS_MONSTER_APPEARANCES.map(deepRelocal);
const appsByMap = {};
for (const app of appearances) {
  (appsByMap[app.mapId] ||= []).push(app.id);
}
for (const m of maps) {
  m.monsterAppearanceIds = uniq([...(m.monsterAppearanceIds || []), ...(appsByMap[m.id] || [])]);
}

// --- Hotspots: curated hotspots (app.data.maps.js top section) over nav hotspots.
const curatedHotspots = new Map((mapsFile.ATLAS_HOTSPOTS || []).map((h) => [h.id, h]));
const navHotspots = navFile.ATLAS_MAP_NAV.hotspots || [];
const hotspotIds = new Set([...curatedHotspots.keys(), ...navHotspots.map((h) => h.id)]);
const navHotById = new Map(navHotspots.map((h) => [h.id, h]));
const hotspots = [...hotspotIds].map((id) => {
  const nav = navHotById.get(id) || {};
  const base = curatedHotspots.get(id) || {};
  return deepRelocal({
    ...nav,
    ...base,
    coords: nav.coords || base.coords || [],
    targetMapId: nav.targetMapId || base.targetMapId || null,
    targetImageUrl: nav.targetImageUrl || base.targetImageUrl || null,
    ui: { ...(nav.ui || {}), ...(base.ui || {}) }
  });
});

// --- Regions: flatten each of the 17 map-hierarchy roots' descendant trees into a
// flat list of member mapIds, resolved via each map's own source.pageUrl. This turns
// the crawler's per-region tree (map-hierarchy.json) into a lookup the UI can use to
// group any of the 866 maps under "which of the 17 regions is this in".
const urlToMapId = new Map();
for (const m of maps) if (m.source?.pageUrl) urlToMapId.set(m.source.pageUrl, m.id);

function flattenTree(node, bag) {
  if (node.url && urlToMapId.has(node.url)) bag.add(urlToMapId.get(node.url));
  for (const child of node.children || []) flattenTree(child, bag);
}

const regions = hierarchyFile.ATLAS_MAP_HIERARCHY.roots.map((root) => {
  const bag = new Set();
  flattenTree(root, bag);
  return {
    id: root.slug,
    label: root.label,
    rootMapId: urlToMapId.get(root.url) || null,
    rootSubtype: root.rootSubtype,
    mapIds: [...bag]
  };
});

// --- Cave systems: hub -> ordered room list, resolved the same way. Rooms whose URL
// didn't resolve to a scraped map (broken source pages) are dropped.
const caveSystems = hierarchyFile.ATLAS_MAP_HIERARCHY.caveSystems
  .map((sys) => ({
    hubMapId: urlToMapId.get(sys.hubUrl) || null,
    hubLabel: sys.hubLabel,
    roomMapIds: (sys.rooms || []).map((r) => urlToMapId.get(r.url)).filter(Boolean)
  }))
  .filter((sys) => sys.hubMapId);

const datasets = {
  'maps.json': maps,
  'regions.json': regions,
  'cave-systems.json': caveSystems,
  'hotspots.json': hotspots,
  'edges.json': (navFile.ATLAS_MAP_NAV.edges || []).map(deepRelocal),
  'monsters.json': monstersFile.ATLAS_MONSTERS.map(deepRelocal),
  'appearances.json': appearances,
  'items.json': itemsFile.ATLAS_ITEMS.map(deepRelocal),
  'drops.json': itemsFile.ATLAS_DROPS.map(deepRelocal),
  'shop-inventory.json': itemsFile.ATLAS_SHOP_INVENTORY.map(deepRelocal),
  'skills.json': skillsFile.ATLAS_SKILLS.map(deepRelocal),
  'skill-requirements.json': skillsFile.ATLAS_SKILL_REQUIREMENTS.map(deepRelocal),
  'path-map-links.json': skillsFile.ATLAS_PATH_MAP_LINKS.map(deepRelocal),
  'data-gaps.json': skillsFile.ATLAS_DATA_GAPS.map(deepRelocal),
  'assets.json': assetsFile.ATLAS_ASSETS.map(deepRelocal),
  'metadata.json': metadataFile.ATLAS_METADATA.map(deepRelocal),
  'world-spine.json': worldSpineFile.ATLAS_WORLD_SPINE.map(deepRelocal),
  'map-hierarchy.json': deepRelocal(hierarchyFile.ATLAS_MAP_HIERARCHY)
};

const summary = {
  generatedAt: new Date().toISOString(),
  source: SRC,
  scrapeSummary: skillsFile.ATLAS_MASTER_DATA_SUMMARY || null,
  counts: Object.fromEntries(
    Object.entries(datasets).map(([k, v]) => [k.replace('.json', ''), Array.isArray(v) ? v.length : 1])
  )
};
datasets['summary.json'] = summary;

for (const [file, data] of Object.entries(datasets)) {
  const out = path.join(CORE, file);
  fs.writeFileSync(out, JSON.stringify(data));
  console.log(`  wrote core/${file} (${Array.isArray(data) ? data.length + ' rows' : 'object'})`);
}

// --- Asset mirror ---
if (!skipAssets) {
  console.log('Mirroring assets (this can take a minute)...');
  fs.cpSync(path.join(SRC, 'assets', 'map-images'), path.join(ASSETS, 'map-images'), { recursive: true });
  fs.cpSync(path.join(SRC, 'assets', 'game-images'), path.join(ASSETS, 'game-images'), { recursive: true });
  console.log('  assets mirrored to data/assets/');
} else {
  console.log('Skipping asset mirror (--skip-assets).');
}

console.log('Done.');
